"use client";
import {AlertTriangle,ArrowLeft,Barcode,BookOpenCheck,Camera,CheckCircle2,ClipboardCheck,FileText,LocateFixed,MapPin,Mic,PenLine,Play,Printer,RotateCcw,Save,Send,ShieldCheck,Sparkles,Square,Target,Trash2,Upload,Users,Video} from "lucide-react";
import {useEffect,useMemo,useRef,useState,type ChangeEvent} from "react";
import type {FieldDef,WorkflowTool,WorkspaceConfig} from "@/lib/smart-workflow-config";
import {ScannerModal,SignatureModal} from "./CaptureModals";
import {bytes,iconMap,makeRecordId,otherSelected,today,uid,visible,type Evidence,type RecordMeta,type ScanResult,type SubmissionRecord} from "./shared";

export function GuidedWorkflow({config,tool,onBack}:{config:WorkspaceConfig;tool:WorkflowTool;onBack:()=>void}){
 const Icon=iconMap[tool.icon]??ClipboardCheck;
 const photoRef=useRef<HTMLInputElement>(null),docRef=useRef<HTMLInputElement>(null),videoRef=useRef<HTMLInputElement>(null),visionRef=useRef<HTMLInputElement>(null),recorderRef=useRef<MediaRecorder|null>(null),audio=useRef<Blob[]>([]);
 const blank=Object.fromEntries(tool.fields.map(f=>[f.key,""]));
 const [values,setValues]=useState<Record<string,string>>(blank),[meta,setMeta]=useState<RecordMeta>({organization:"QMSPilot Design Partner",site:"Primary Site",recordId:makeRecordId(config,tool),eventDate:today()}),[priority,setPriority]=useState("Normal"),[owner,setOwner]=useState(""),[due,setDue]=useState(""),[checks,setChecks]=useState<Record<string,boolean>>(Object.fromEntries(tool.controls.map(c=>[c,false]))),[role,setRole]=useState(tool.approvalRoles[0]||"Authorized Approver"),[approver,setApprover]=useState(""),[decision,setDecision]=useState(""),[conditions,setConditions]=useState(""),[evidence,setEvidence]=useState<Evidence[]>([]),[notice,setNotice]=useState(""),[issues,setIssues]=useState<string[]>([]),[submitted,setSubmitted]=useState<SubmissionRecord|null>(null),[scanner,setScanner]=useState(false),[signature,setSignature]=useState(false),[recording,setRecording]=useState(false),[stage,setStage]=useState(0);
 const key=`qmspilot:guided:${config.discipline}:${tool.id}`;
 const fields=useMemo(()=>tool.fields.filter(f=>visible(f,values)),[tool.fields,values]);
 const sections=["Record Context","Evaluation","Response & Action","Closure"] as const;
 const completion=useMemo(()=>{const all=[...fields.filter(f=>f.required).map(f=>!!values[f.key]?.trim()),...tool.controls.map(c=>!!checks[c]),!!meta.organization,!!meta.site,!!meta.recordId,!!meta.eventDate,!!owner,!!due,!!approver,!!decision,...(tool.evidenceRequired?[evidence.length>0]:[])];return Math.round(all.filter(Boolean).length/Math.max(all.length,1)*100)},[fields,values,tool.controls,tool.evidenceRequired,checks,meta,owner,due,approver,decision,evidence.length]);
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(key)||"null");if(d){setValues({...blank,...d.values});setMeta(d.meta||meta);setPriority(d.priority||"Normal");setOwner(d.owner||"");setDue(d.due||"");setChecks(d.checks||checks);setRole(d.role||role);setApprover(d.approver||"");setDecision(d.decision||"");setConditions(d.conditions||"");setEvidence((d.evidence||[]).map((x:Evidence)=>({...x,url:undefined})));setNotice("Saved draft restored. Reattach source files if this is a new browser session.")}}catch{localStorage.removeItem(key)}},[]);
 const set=(k:string,v:string)=>{setValues(x=>({...x,[k]:v}));setIssues([]);setSubmitted(null)};
 const add=(kind:Evidence["kind"],list:FileList|null,note?:string)=>{if(!list?.length)return;setEvidence(x=>[...x,...Array.from(list).map(f=>({id:uid(),kind,name:f.name,size:f.size,url:f.type.startsWith("image/")?URL.createObjectURL(f):undefined,note}))]);setNotice("Evidence attached.")};
 const scan=(r:ScanResult)=>{const next={...values};const norm=Object.fromEntries(Object.entries(r.fields).map(([k,v])=>[k.toLowerCase().replace(/[^a-z0-9]/g,""),v]));fields.forEach(f=>{const k=`${f.key}${f.label}`.toLowerCase().replace(/[^a-z0-9]/g,"");const m=Object.keys(norm).find(n=>k.includes(n)||n.includes(f.key.replace(/_/g,"")));if(m&&!next[f.key])next[f.key]=norm[m]});if(!Object.keys(r.fields).length&&fields[0])next[fields[0].key]=r.raw;setValues(next);setEvidence(x=>[...x,{id:uid(),kind:"scan",name:"Barcode / QR capture",size:r.raw.length,note:r.raw}]);setScanner(false);setNotice("Scan captured and matching fields populated.")};
 const audioStart=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const rec=new MediaRecorder(stream);audio.current=[];rec.ondataavailable=e=>e.data.size&&audio.current.push(e.data);rec.onstop=()=>{const blob=new Blob(audio.current,{type:rec.mimeType||"audio/webm"});setEvidence(x=>[...x,{id:uid(),kind:"audio",name:`voice-note-${Date.now()}.webm`,size:blob.size,url:URL.createObjectURL(blob)}]);stream.getTracks().forEach(t=>t.stop());setRecording(false)};recorderRef.current=rec;rec.start();setRecording(true)}catch{setNotice("Microphone access was unavailable.")}};
 const location=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{const n=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} · ±${Math.round(p.coords.accuracy)} m`;setEvidence(x=>[...x,{id:uid(),kind:"location",name:"Verified location",size:n.length,note:n}])},()=>setNotice("Location permission was not granted.")):setNotice("Location capture is not supported.");
 const save=()=>{localStorage.setItem(key,JSON.stringify({values,meta,priority,owner,due,checks,role,approver,decision,conditions,evidence:evidence.map(({url,...x})=>x)}));setNotice("Draft saved in this browser.")};
 const validate=()=>{const x:string[]=[];if(!meta.organization)x.push("Organization");if(!meta.site)x.push("Site");if(!meta.recordId)x.push("Record ID");if(!meta.eventDate)x.push("Date");fields.filter(f=>f.required).forEach(f=>{if(!values[f.key]?.trim())x.push(f.label);if(otherSelected(values[f.key]||"")&&!values[`${f.key}_other`]?.trim())x.push(`${f.label} detail`)});if(!owner)x.push("Owner");if(!due)x.push("Due date");tool.controls.forEach(c=>!checks[c]&&x.push(c));if(tool.evidenceRequired&&!evidence.length)x.push("Required evidence");if(!approver)x.push("Approver");if(!decision)x.push("Decision");if(decision==="Approved with conditions"&&!conditions)x.push("Approval conditions");setIssues(x);return x};
 const submit=()=>{if(validate().length){setNotice("Submission blocked until required fields, evidence, controls, and approval are complete.");return}const record:SubmissionRecord={schema:"qmspilot.northstar.guided-workflow.v2",workspace:config.name,toolId:tool.id,toolName:tool.name,recordMeta:meta,procedure:tool.procedure,values,priority,owner,dueDate:due,controls:checks,approval:{role,name:approver,decision,conditions},evidence:evidence.map(({url,...x})=>x),status:decision.startsWith("Approved")?"Submitted / approved":"Submitted / returned",submittedAt:new Date().toISOString()};const records=JSON.parse(localStorage.getItem("qmspilot:northstar:guided-records")||"[]");localStorage.setItem("qmspilot:northstar:guided-records",JSON.stringify([record,...records].slice(0,250)));localStorage.removeItem(key);window.dispatchEvent(new CustomEvent("qmspilot:record-submitted",{detail:record}));setSubmitted(record);setNotice("Controlled record submitted to Northstar.");window.scrollTo({top:0,behavior:"smooth"})};
 const assign=()=>{if(!owner||!due){setNotice("Enter an owner and due date first.");return}const a={id:`ACT-${uid()}`,sourceRecord:meta.recordId,sourceTool:tool.name,owner,dueDate:due,priority,status:"Open",createdAt:new Date().toISOString()};const list=JSON.parse(localStorage.getItem("qmspilot:northstar:assigned-actions")||"[]");localStorage.setItem("qmspilot:northstar:assigned-actions",JSON.stringify([a,...list].slice(0,250)));setNotice(`Action assigned to ${owner}.`)};
 const reset=()=>{localStorage.removeItem(key);setValues(blank);setMeta({organization:"QMSPilot Design Partner",site:"Primary Site",recordId:makeRecordId(config,tool),eventDate:today()});setOwner("");setDue("");setChecks(Object.fromEntries(tool.controls.map(c=>[c,false])));setApprover("");setDecision("");setConditions("");setEvidence([]);setIssues([]);setSubmitted(null);setNotice("New record started.")};
 const guidance=priority==="Critical"?"Critical priority requires immediate containment and leadership escalation.":tool.evidenceRequired&&!evidence.length?"Attach objective evidence before closure.":completion<50?"Complete the facts and requirement before deciding the response.":"Complete closure gates and authorized approval before submission.";
 return <section className="guided-workflow"><button className="guided-back" onClick={onBack}><ArrowLeft size={16}/> Back to {config.name}</button><div className="guided-head"><span><Icon/></span><div><small>{tool.group.toUpperCase()}</small><h1>{tool.name}</h1><p>{tool.description}</p></div><div className="completion"><strong>{completion}%</strong><small>record readiness</small><div><i style={{width:`${completion}%`}}/></div></div></div>{notice&&<div className="guided-notice"><Sparkles size={17}/>{notice}</div>}{submitted&&<div className="guided-success"><CheckCircle2/><div><strong>Submitted to Northstar</strong><span>{submitted.recordMeta.recordId} · {submitted.status}</span></div></div>}
 <section className="procedure-banner"><div><BookOpenCheck/><span><small>APPLICABLE CONTROLLED PROCEDURE</small><strong>{tool.procedure.id} · {tool.procedure.title}</strong><em>{tool.procedure.revision} · Owner: {tool.procedure.owner}</em></span></div><div className="standard-tags">{tool.procedure.standards.map(s=><span key={s}>{s}</span>)}</div><p>QMSPilot baseline workflow. Customer procedure IDs, terminology, options, authorities, risk thresholds, numbering, and retention rules remain configurable.</p></section>
 <section className="stage-strip">{tool.stages.map((s,i)=><button key={s} className={i===stage?"active":i<stage?"complete":""} onClick={()=>setStage(i)}><span>{i<stage?"✓":i+1}</span><strong>{s}</strong></button>)}</section>
 <div className="guided-layout"><div className="guided-form-column"><article className="guided-card"><div className="guided-title"><div><small>RECORD CONTROL</small><h2>Identity, context, and accountability</h2></div><FileText/></div><div className="record-grid"><label>Organization *<input value={meta.organization} onChange={e=>setMeta({...meta,organization:e.target.value})}/></label><label>Site *<input value={meta.site} onChange={e=>setMeta({...meta,site:e.target.value})}/></label><label>Record ID *<input value={meta.recordId} onChange={e=>setMeta({...meta,recordId:e.target.value})}/></label><label>Date *<input type="date" value={meta.eventDate} onChange={e=>setMeta({...meta,eventDate:e.target.value})}/></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Normal</option><option>High</option><option>Critical</option></select></label><label>Accountable owner *<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Due / review date *<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div></article>{sections.map(section=>{const list=fields.filter(f=>f.section===section);return list.length?<article className="guided-card" key={section}><div className="guided-title"><div><small>{section.toUpperCase()}</small><h2>{section}</h2></div><ClipboardCheck/></div><div className="field-grid">{list.map(f=><Field key={f.key} field={f} value={values[f.key]||""} other={values[`${f.key}_other`]||""} change={v=>set(f.key,v)} otherChange={v=>set(`${f.key}_other`,v)}/>)}</div></article>:null})}</div>
 <aside className="guided-side"><article className="guided-card evidence-card"><div className="guided-title"><div><small>OBJECTIVE EVIDENCE</small><h2>{evidence.length} captured</h2></div><Camera/></div><div className={`evidence-requirement ${tool.evidenceRequired?"required":"optional"}`}><strong>{tool.evidenceRequired?"Required before submission":"Available when needed"}</strong><span>Prove the condition, decision, action, verification, or approval.</span></div><div className="evidence-guidance">{tool.evidenceGuidance.map(x=><span key={x}>• {x}</span>)}</div><div className="evidence-buttons rich"><button onClick={()=>photoRef.current?.click()}><Camera size={16}/>Photos</button><button onClick={()=>docRef.current?.click()}><Upload size={16}/>Documents</button><button onClick={()=>videoRef.current?.click()}><Video size={16}/>Video</button><button onClick={()=>visionRef.current?.click()}><Sparkles size={16}/>AI Vision</button><button onClick={()=>setScanner(true)}><Barcode size={16}/>Barcode / QR</button><button onClick={recording?()=>recorderRef.current?.stop():audioStart}>{recording?<Square size={16}/>:<Mic size={16}/>}Voice note</button><button onClick={location}><LocateFixed size={16}/>Location</button><button onClick={()=>setSignature(true)}><PenLine size={16}/>Signature</button><input hidden ref={photoRef} type="file" accept="image/*" multiple capture="environment" onChange={(e:ChangeEvent<HTMLInputElement>)=>add("photo",e.target.files)}/><input hidden ref={docRef} type="file" multiple onChange={(e:ChangeEvent<HTMLInputElement>)=>add("document",e.target.files)}/><input hidden ref={videoRef} type="file" accept="video/*" capture="environment" onChange={(e:ChangeEvent<HTMLInputElement>)=>add("video",e.target.files)}/><input hidden ref={visionRef} type="file" accept="image/*" capture="environment" onChange={(e:ChangeEvent<HTMLInputElement>)=>add("vision",e.target.files,"AI-assisted review queued; human verification required")}/></div>{evidence.length>0&&<div className="evidence-list">{evidence.map(x=><div key={x.id}>{x.url&&["photo","vision","signature"].includes(x.kind)?<img src={x.url} alt="Evidence"/>:<span>{x.kind==="video"?<Video/>:x.kind==="audio"?<Play/>:x.kind==="location"?<MapPin/>:x.kind==="scan"?<Barcode/>:<FileText/>}</span>}<p><strong>{x.name}</strong><small>{x.kind.toUpperCase()} · {bytes(x.size)}</small>{x.note&&<em>{x.note}</em>}</p><button onClick={()=>setEvidence(y=>y.filter(z=>z.id!==x.id))}><Trash2/></button></div>)}</div>}</article>
 <article className="guided-card gate-card"><div className="guided-title"><div><small>CLOSURE GATES</small><h2>Required controls</h2></div><ShieldCheck/></div>{tool.controls.map(c=><label key={c}><input type="checkbox" checked={!!checks[c]} onChange={e=>setChecks({...checks,[c]:e.target.checked})}/><span>{c}</span></label>)}</article><article className="guided-card approval-card"><div className="guided-title"><div><small>HUMAN AUTHORITY</small><h2>Approval decision</h2></div><Users/></div><label>Role *<select value={role} onChange={e=>setRole(e.target.value)}>{tool.approvalRoles.map(r=><option key={r}>{r}</option>)}</select></label><label>Approver *<input value={approver} onChange={e=>setApprover(e.target.value)}/></label><label>Decision *<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Select</option><option>Approved</option><option>Approved with conditions</option><option>Rejected</option><option>Returned for revision</option></select></label>{decision&&decision!=="Approved"&&<label>Conditions / reason *<textarea value={conditions} onChange={e=>setConditions(e.target.value)}/></label>}</article><article className="guided-card ai-card"><div className="guided-title"><div><small>PILOT GUIDANCE</small><h2>Workflow coaching</h2></div><Sparkles/></div><p>{guidance}</p><small>Qualified humans retain authority for disposition, release, commitments, regulatory decisions, and closure.</small></article><article className="guided-card escalation-card"><div className="guided-title"><div><small>ESCALATION LOGIC</small><h2>Required routing</h2></div><AlertTriangle/></div>{tool.escalations.map(r=><div key={r.when}><strong>{r.when}</strong><span>{r.route}</span></div>)}</article></aside></div>
 {issues.length>0&&<section className="validation-box"><AlertTriangle/><div><strong>Submission blocked.</strong><p>{issues.slice(0,10).join(" · ")}</p></div></section>}<div className="guided-actions"><button className="secondary" onClick={save}><Save/>Save draft</button><button className="secondary" onClick={()=>window.print()}><Printer/>PDF / Print</button><button className="secondary" onClick={assign}><Target/>Assign action</button><button className="secondary danger" onClick={reset}><RotateCcw/>New record</button><button className="primary" onClick={submit}><Send/>Submit to Northstar</button></div>{scanner&&<ScannerModal onClose={()=>setScanner(false)} onResult={scan}/>} {signature&&<SignatureModal onClose={()=>setSignature(false)} onSave={(url,size)=>{setEvidence(x=>[...x,{id:uid(),kind:"signature",name:`signature-${today()}.png`,size,url}]);setSignature(false)}}/>}</section>
}
function Field({field,value,other,change,otherChange}:{field:FieldDef;value:string;other:string;change:(v:string)=>void;otherChange:(v:string)=>void}){return <label className={field.type==="textarea"?"wide":""}><span>{field.label}{field.required?" *":""}</span>{field.type==="select"?<select value={value} onChange={e=>change(e.target.value)}><option value="">Select an option</option>{field.options?.map(x=><option key={x}>{x}</option>)}</select>:field.type==="textarea"?<textarea value={value} onChange={e=>change(e.target.value)}/>:<input type={field.type} value={value} onChange={e=>change(e.target.value)}/>} {field.help&&<small>{field.help}</small>}{otherSelected(value)&&<textarea className="other-detail" value={other} onChange={e=>otherChange(e.target.value)} placeholder="Enter customer-defined detail *"/>}</label>}
