import { smartWorkspaceConfigs } from "@/lib/smart-workflow-config";
import { F, RISK, RESULT, YES_NO, YES_NO_NA, escalation, procedure, specializeWorkspace, type ToolProfiles } from "@/lib/smart-specialization-helpers";

const profiles: ToolProfiles = {
  verify: {
    procedure: procedure("DL-08.01", "Shipment Verification and Final Dispatch", "Logistics / Quality", ["ISO 9001:2015 8.5.4", "ISO 9001:2015 8.6"]),
    stages: ["Identify order", "Verify product", "Verify quantity / traceability", "Verify packaging", "Verify documents", "Inspect vehicle", "Release", "Confirm shipment"],
    fields: [
      F("shipment", "Shipment / load / order", "text", "Record Context", true), F("customer", "Customer / ship-to", "text", "Record Context", true), F("carrier", "Carrier / service level", "text", "Record Context", true), F("scheduled_ship", "Scheduled ship date / time", "datetime-local", "Record Context", true),
      F("product", "Product / part / package", "textarea", "Evaluation", true), F("qty_required", "Quantity required", "number", "Evaluation", true), F("qty_loaded", "Quantity loaded", "number", "Evaluation", true), F("serial_lot", "Serial / lot / package traceability", "textarea", "Evaluation", true), F("quality_release", "Quality / customer release status", "select", "Evaluation", true, RESULT), F("packaging", "Packaging, preservation, blocking, and bracing", "select", "Evaluation", true, RESULT), F("labels", "Labels, marks, routing, and customer identification", "select", "Evaluation", true, RESULT), F("documents", "Packing list, CoC, test reports, and customer documents", "select", "Evaluation", true, RESULT), F("vehicle", "Trailer / container cleanliness, condition, and compatibility", "select", "Evaluation", true, RESULT),
      F("exception", "Exception / missing requirement", "textarea", "Response & Action"), F("hold_reference", "Hold / deviation / approval reference", "text", "Response & Action"), F("seal", "Seal number / final security control", "text", "Closure"), F("release", "Shipment release decision", "select", "Closure", true, ["Released", "Released with approved condition", "Held", "Rejected / unload"]), F("shipment_confirmation", "ERP / TMS shipment confirmation", "text", "Closure", true), F("actual_departure", "Actual departure date / time", "datetime-local", "Closure", true),
    ],
    controls: ["Correct customer, product, quantity, and traceability are verified", "Quality release, packaging, labels, and documents are complete", "Vehicle / container and load securement are acceptable", "Authorized release and shipment confirmation are documented"],
    approvalRoles: ["Shipping Verifier", "Logistics Coordinator", "Quality Release Authority", "Warehouse Supervisor"], evidenceRequired: true,
    evidenceGuidance: ["Product / serial / lot photographs", "Packaging and load-securement evidence", "Labels and customer documents", "Trailer / container / seal / departure evidence"],
    escalations: [escalation("Quality release, customer document, or securement is incomplete", "Hold shipment and route to responsible authority"), escalation("Shipment will miss customer commitment", "Delivery Assurance, Operations, and customer owner")],
  },
  photos: {
    procedure: procedure("DL-08.02", "Shipping Photographic Evidence and Customer Report", "Logistics / Quality", ["ISO 9001:2015 8.5.4"]),
    stages: ["Identify shipment", "Capture product", "Capture packaging", "Capture labels", "Capture securement", "Capture seal / vehicle", "Review completeness", "Publish"],
    fields: [
      F("shipment", "Shipment / order / load", "text", "Record Context", true), F("customer", "Customer / destination", "text", "Record Context", true), F("product_scope", "Products, serials, packages, and quantities", "textarea", "Record Context", true), F("evidence_standard", "Required evidence set", "select", "Evaluation", true, ["Standard shipment set", "Customer-specific report", "High-value / oversized", "Export / container", "Warranty / claim protection"]),
      F("identity_views", "Product identity / serial / condition captured?", "select", "Evaluation", true, YES_NO), F("packaging_views", "Packaging / preservation captured?", "select", "Evaluation", true, YES_NO), F("label_views", "Labels / marks / routing captured?", "select", "Evaluation", true, YES_NO), F("securement_views", "Blocking / bracing / tie-downs captured?", "select", "Evaluation", true, YES_NO), F("vehicle_views", "Trailer / container / door / seal captured?", "select", "Evaluation", true, YES_NO),
      F("exceptions", "Missing, obscured, or nonconforming view", "textarea", "Response & Action"), F("recapture", "Recapture / correction completed", "select", "Response & Action", true, YES_NO_NA), F("report_reference", "Customer-facing report / archive reference", "text", "Closure", true), F("review_result", "Evidence review result", "select", "Closure", true, ["Complete", "Complete with approved exception", "Incomplete - hold / recapture"]), F("released_to_customer", "Evidence package released to customer / record system", "select", "Closure", true, YES_NO),
    ],
    controls: ["Evidence is tied to correct shipment and customer", "Identity, condition, packaging, labels, securement, and vehicle views are complete", "Images are clear and time-relevant", "Evidence package is reviewed and controlled before publication"],
    approvalRoles: ["Shipping Photographer / Verifier", "Warehouse Lead", "Quality Reviewer", "Customer / Logistics Owner"], evidenceRequired: true,
    evidenceGuidance: ["Product identity and condition", "Packaging / preservation", "Labels and customer marks", "Blocking, bracing, trailer, and seal"],
    escalations: [escalation("Image reveals damage, wrong product, or poor securement", "Stop shipment and correct"), escalation("Required views cannot be captured", "Hold or document authorized exception")],
  },
  packaging: {
    procedure: procedure("DL-08.03", "Packaging, Preservation, and Load Securement", "Packaging Engineering / Logistics", ["ISO 9001:2015 8.5.4"]),
    stages: ["Confirm requirement", "Inspect product", "Apply preservation", "Package", "Block / brace", "Label", "Verify", "Release"],
    fields: [
      F("shipment", "Shipment / order", "text", "Record Context", true), F("product", "Product / serial / package", "textarea", "Record Context", true), F("packaging_spec", "Packaging / customer specification", "text", "Evaluation", true), F("mode", "Transportation mode", "select", "Evaluation", true, ["Parcel", "LTL", "Truckload", "Air", "Ocean / container", "Customer pickup", "Specialized / flatbed"]), F("product_condition", "Product clean, dry, complete, and protected", "select", "Evaluation", true, RESULT), F("preservation", "Rust prevention, caps, plugs, desiccant, wrap, or environmental control", "select", "Evaluation", true, RESULT), F("container", "Crate, skid, pallet, carton, or container condition / rating", "select", "Evaluation", true, RESULT), F("cushioning", "Cushioning, separation, edge / surface protection", "select", "Evaluation", true, RESULT), F("securement", "Blocking, bracing, tie-down, center of gravity, and load distribution", "select", "Evaluation", true, RESULT), F("hazmat", "Hazardous-material / battery / fluid requirements", "select", "Evaluation", true, YES_NO_NA), F("labels", "Handling, orientation, center-of-gravity, and customer labels", "select", "Evaluation", true, RESULT),
      F("exception", "Packaging exception / deviation", "textarea", "Response & Action"), F("correction", "Correction / repackaging performed", "textarea", "Response & Action"), F("weight_dimensions", "Final weight and dimensions", "text", "Closure", true), F("verification", "Final packaging verification", "select", "Closure", true, ["Accepted", "Accepted with approval", "Rejected / repackage"]), F("approval_reference", "Packaging-engineering / customer approval", "text", "Closure"),
    ],
    controls: ["Applicable customer and transportation requirements are known", "Product preservation and package strength are suitable", "Blocking / bracing and labels control foreseeable transit risk", "Final weight, dimensions, and approval are verified"],
    approvalRoles: ["Packaging Verifier", "Packaging Engineer", "Quality Authority", "Logistics / Customer Authority"], evidenceRequired: true,
    evidenceGuidance: ["Product condition before packaging", "Preservation and package build", "Blocking / bracing / tie-down", "Final labels, dimensions, and approval"],
    escalations: [escalation("Packaging cannot meet customer or transport requirement", "Packaging Engineering and customer approval"), escalation("Unsafe weight distribution or securement", "Stop loading and correct")],
  },
  documents: {
    procedure: procedure("DL-08.04", "Shipping Documentation Control", "Logistics / Quality / Trade Compliance", ["ISO 9001:2015 7.5", "ISO 9001:2015 8.6"]),
    stages: ["Load requirements", "Create documents", "Verify data", "Collect certificates", "Review compliance", "Approve", "Transmit / archive"],
    fields: [
      F("shipment", "Shipment / order", "text", "Record Context", true), F("customer", "Customer / destination", "text", "Record Context", true), F("document_set", "Required document set", "textarea", "Evaluation", true), F("packing_list", "Packing list", "select", "Evaluation", true, RESULT), F("coc", "Certificate of conformance", "select", "Evaluation", true, YES_NO_NA), F("test_reports", "Inspection / test reports", "select", "Evaluation", true, YES_NO_NA), F("material_certificates", "Material / special-process certificates", "select", "Evaluation", true, YES_NO_NA), F("commercial_invoice", "Commercial invoice / customs value", "select", "Evaluation", true, YES_NO_NA), F("export_docs", "Export / origin / classification documents", "select", "Evaluation", true, YES_NO_NA), F("customer_forms", "Customer-specific portal / form / ASN", "select", "Evaluation", true, YES_NO_NA),
      F("data_match", "Part, quantity, serial, revision, customer, and address match", "select", "Evaluation", true, RESULT), F("exception", "Missing / incorrect document or data", "textarea", "Response & Action"), F("correction", "Correction / reissue / approval", "textarea", "Response & Action"), F("transmission", "Customer / broker / carrier transmission reference", "text", "Closure", true), F("archive", "Controlled archive / retention location", "text", "Closure", true), F("release", "Document-release status", "select", "Closure", true, ["Complete / released", "Released with approved exception", "Held"]),
    ],
    controls: ["Document requirements are loaded from customer / order controls", "Product, quantity, serial, revision, value, and address data match", "Certificates and trade documents are complete", "Released documents are transmitted and retained in controlled location"],
    approvalRoles: ["Shipping Documentation Specialist", "Quality Release Authority", "Trade Compliance", "Customer / Program Owner"], evidenceRequired: true,
    evidenceGuidance: ["Final document set", "Order / customer requirement", "Certificate / test-report evidence", "Transmission and archive confirmation"],
    escalations: [escalation("Required customer / export document is missing", "Hold shipment"), escalation("Data mismatch affects customs or product identity", "Trade Compliance / Quality correction")],
  },
  release: {
    procedure: procedure("DL-08.05", "Customer Release Authorization", "Quality / Customer Program", ["ISO 9001:2015 8.6"]),
    stages: ["Identify release", "Verify quality", "Verify configuration", "Verify documents", "Resolve holds", "Obtain authority", "Release"],
    fields: [
      F("shipment", "Shipment / order / product", "text", "Record Context", true), F("customer", "Customer / program", "text", "Record Context", true), F("release_type", "Release type", "select", "Record Context", true, ["Standard quality release", "Customer source inspection", "First article / launch", "Conditional / deviation", "Milestone / progress release", "Export / regulatory release"]), F("product_status", "Product complete and acceptable", "select", "Evaluation", true, RESULT), F("inspection_status", "Required inspections / tests complete", "select", "Evaluation", true, RESULT), F("configuration", "Part, revision, serial / lot, and configuration verified", "select", "Evaluation", true, RESULT), F("ncr_holds", "Open NCR, deviation, or hold status", "select", "Evaluation", true, ["None", "Approved deviation / concession", "Open hold - not releasable", "Pending review"]), F("documentation", "Required release documents complete", "select", "Evaluation", true, RESULT), F("customer_approval", "Customer / source-inspector approval", "select", "Evaluation", true, YES_NO_NA),
      F("conditions", "Release conditions / limitations", "textarea", "Response & Action"), F("authority_reference", "Approval / signature / portal reference", "text", "Closure", true), F("release_date", "Release date", "date", "Closure", true), F("release_status", "Release status", "select", "Closure", true, ["Released", "Released with conditions", "Held", "Rejected / rework"]), F("validity", "Release validity / expiration / shipment scope", "textarea", "Closure", true),
    ],
    controls: ["Product, inspection, configuration, holds, and documents are verified", "Conditional release has approved authority and explicit scope", "Customer / source approval is documented where required", "Release is traceable to shipment and validity period"],
    approvalRoles: ["Quality Release Authority", "Customer / Source Inspector", "Program Manager", "Engineering / MRB Authority"], evidenceRequired: true,
    evidenceGuidance: ["Inspection / test release", "Configuration / serial evidence", "Deviation / concession approval", "Customer / source approval"],
    escalations: [escalation("Open hold or unresolved product requirement", "Do not release"), escalation("Conditional release lacks customer authority", "Quality / Program escalation")],
  },
  exception: {
    procedure: procedure("DL-08.06", "Delivery Exception and Customer Recovery", "Logistics / Customer Service", ["ISO 9001:2015 8.2.1", "ISO 9001:2015 8.4.2"]),
    stages: ["Detect", "Assess commitment", "Contain", "Build recovery", "Communicate", "Execute", "Verify delivery", "Close / improve"],
    fields: [
      F("shipment", "Shipment / order", "text", "Record Context", true), F("customer", "Customer / contact", "text", "Record Context", true), F("exception_type", "Exception type", "select", "Evaluation", true, ["Late / missed ship", "Carrier delay", "Misroute", "Shortage / partial", "Documentation hold", "Quality hold", "Appointment miss", "Customs / export", "Weather / force majeure"]), F("original_commit", "Original customer commitment", "datetime-local", "Evaluation", true), F("current_forecast", "Current forecast / ETA", "datetime-local", "Evaluation", true), F("affected_qty", "Affected quantity / orders", "textarea", "Evaluation", true), F("impact", "Customer / business impact", "select", "Evaluation", true, RISK), F("cause", "Known cause / constraint", "textarea", "Evaluation", true),
      F("containment", "Immediate containment / shipment protection", "textarea", "Response & Action", true), F("recovery", "Recovery plan / alternate route / expedite", "textarea", "Response & Action", true), F("customer_communication", "Customer communication, owner, and date", "textarea", "Response & Action", true), F("approval", "New commitment / commercial approval", "text", "Response & Action"), F("premium_cost", "Premium freight / recovery cost ($)", "number", "Response & Action"),
      F("actual_delivery", "Actual delivery / recovery result", "datetime-local", "Closure"), F("customer_acceptance", "Customer acceptance / impact status", "select", "Closure", true, ["Accepted / recovered", "Accepted with issue", "Customer claim / escalation", "No confirmation"]), F("systemic", "Corrective action / carrier / supplier action required?", "select", "Closure", true, ["No", "Internal CAPA", "Carrier action", "Supplier action", "Planning / capacity action"]), F("status", "Exception status", "select", "Closure", true, ["Closed", "Recovery active", "Customer escalation", "Claim open", "Systemic action open"]),
    ],
    controls: ["Original commitment, current forecast, and affected scope are clear", "Containment and recovery protect customer product and information", "Customer communication and new commitment are authorized", "Actual delivery, cost, customer outcome, and systemic follow-up are verified"],
    approvalRoles: ["Logistics Coordinator", "Customer Service / Account Owner", "Operations / Supply Chain Leader", "Executive / Commercial Authority"], evidenceRequired: true,
    evidenceGuidance: ["Shipment / carrier status", "Recovery / expedite evidence", "Customer communication", "Delivery and cost verification"],
    escalations: [escalation("Critical customer line-down or contractual miss", "Executive customer-response team"), escalation("New commitment cannot be met", "Immediate reforecast and leadership escalation")],
  },
  damage: {
    procedure: procedure("DL-08.07", "Freight Damage and Claim Management", "Logistics / Claims / Quality", ["ISO 9001:2015 8.5.4", "ISO 9001:2015 9.1.2"]),
    stages: ["Receive notice", "Preserve evidence", "Control product", "Notify carrier", "Assess damage", "File claim", "Recover", "Close"],
    fields: [
      F("shipment", "Shipment / BOL / PRO / tracking", "text", "Record Context", true), F("customer", "Customer / consignee", "text", "Record Context", true), F("carrier", "Carrier", "text", "Record Context", true), F("delivery_date", "Delivery date", "date", "Record Context", true), F("notice_date", "Damage notice date", "date", "Record Context", true), F("product", "Affected product / serial / package", "textarea", "Evaluation", true), F("qty_damaged", "Quantity damaged", "number", "Evaluation", true), F("damage_type", "Damage type", "select", "Evaluation", true, ["Impact / crushed", "Water / moisture", "Puncture / abrasion", "Load shift / tip", "Missing / shortage", "Temperature exposure", "Concealed damage", "Contamination"]), F("delivery_receipt", "Delivery receipt exception / notation", "text", "Evaluation", true), F("packaging_condition", "Packaging / securement condition", "textarea", "Evaluation", true), F("product_risk", "Product-use / safety / customer risk", "select", "Evaluation", true, RISK),
      F("containment", "Customer / internal product containment", "textarea", "Response & Action", true), F("carrier_notice", "Carrier notification / inspection request", "textarea", "Response & Action", true), F("claim_value", "Estimated claim / replacement value ($)", "number", "Response & Action", true), F("claim_reference", "Claim reference", "text", "Response & Action"), F("replacement", "Replacement / repair / customer recovery", "textarea", "Response & Action", true),
      F("responsibility", "Responsibility determination", "select", "Closure", true, ["Carrier", "Packaging / shipper", "Customer unloading / storage", "Supplier / drop ship", "Shared", "Undetermined"]), F("settlement", "Claim settlement / commercial outcome", "textarea", "Closure"), F("systemic_action", "Packaging / carrier / process improvement", "textarea", "Closure"), F("status", "Claim status", "select", "Closure", true, ["Closed", "Carrier inspection pending", "Claim submitted", "Settlement pending", "Customer recovery open"]),
    ],
    controls: ["Delivery condition and evidence are preserved promptly", "Damaged product is controlled", "Carrier notice and claim timing are met", "Customer recovery, responsibility, settlement, and prevention are documented"],
    approvalRoles: ["Logistics / Claims Coordinator", "Quality Authority", "Customer Service", "Finance / Commercial Authority"], evidenceRequired: true,
    evidenceGuidance: ["Delivered condition and packaging photographs", "Delivery receipt / carrier notation", "Product damage assessment", "Claim, replacement, and settlement evidence"],
    escalations: [escalation("Customer may use unsafe or damaged product", "Immediate Quality / customer containment"), escalation("Claim notice deadline is at risk", "Claims / Logistics leadership")],
  },
  carrier: {
    procedure: procedure("DL-08.08", "Carrier Qualification and Performance Scorecard", "Logistics / Supply Chain", ["ISO 9001:2015 8.4.1"]),
    stages: ["Define period", "Collect shipments", "Validate events", "Calculate", "Rate", "Review claims / cost", "Set status", "Improve"],
    fields: [
      F("carrier", "Carrier / service", "text", "Record Context", true), F("period", "Review period", "text", "Record Context", true), F("shipments", "Shipments", "number", "Evaluation", true), F("on_time_pickup", "On-time pickup (%)", "number", "Evaluation", true), F("on_time_delivery", "On-time delivery (%)", "number", "Evaluation", true), F("damage_claims", "Damage / loss claims", "number", "Evaluation", true), F("claim_value", "Claim value ($)", "number", "Evaluation"), F("tracking_score", "Tracking / status accuracy (%)", "number", "Evaluation"), F("response_score", "Responsiveness score (%)", "number", "Evaluation"), F("invoice_accuracy", "Invoice / accessorial accuracy (%)", "number", "Evaluation"), F("premium_cost", "Premium / expedite / accessorial cost ($)", "number", "Evaluation"),
      F("risk", "Carrier risk", "select", "Evaluation", true, RISK), F("rating", "Overall rating", "select", "Evaluation", true, ["Preferred", "Acceptable", "Needs improvement", "Conditional", "Unacceptable"]), F("improvement", "Improvement commitments / corrective action", "textarea", "Response & Action"), F("status", "Approved-carrier status", "select", "Closure", true, ["Approved", "Approved with conditions", "Probation", "Restricted lanes", "Removed"]), F("next_review", "Next review", "date", "Closure", true),
    ],
    controls: ["Shipment, delivery, damage, claim, cost, and response data are validated", "Rating criteria are consistent", "High-risk / poor performance has improvement action", "Carrier status and lane restrictions are communicated"],
    approvalRoles: ["Logistics Analyst", "Logistics Manager", "Supply Chain Leader", "Risk / Finance Authority"], evidenceRequired: false,
    evidenceGuidance: ["Validated shipment data", "Damage / claim trend", "Cost / invoice analysis", "Improvement and status communication"],
    escalations: [escalation("Unacceptable safety, damage, or delivery performance", "Carrier executive review / removal"), escalation("Critical lane lacks alternative", "Continuity and sourcing review")],
  },
  pod: {
    procedure: procedure("DL-08.09", "Proof of Delivery and Delivery Confirmation", "Logistics / Customer Service", ["ISO 9001:2015 8.5.4", "ISO 9001:2015 9.1.2"]),
    stages: ["Track shipment", "Confirm delivery", "Capture recipient", "Verify condition", "Resolve exception", "Archive", "Close"],
    fields: [
      F("shipment", "Shipment / BOL / tracking", "text", "Record Context", true), F("customer", "Customer / delivery location", "text", "Record Context", true), F("carrier", "Carrier", "text", "Record Context", true), F("scheduled_delivery", "Scheduled delivery", "datetime-local", "Evaluation", true), F("actual_delivery", "Actual delivery", "datetime-local", "Evaluation", true), F("recipient", "Recipient name / department", "text", "Evaluation", true), F("signature_reference", "Signature / electronic POD reference", "text", "Evaluation", true), F("delivered_qty", "Quantity / packages delivered", "number", "Evaluation", true), F("condition", "Delivered condition", "select", "Evaluation", true, ["Accepted clean", "Accepted with notation", "Damaged", "Short / missing", "Refused", "Unable to deliver"]),
      F("exception", "Delivery exception / notation", "textarea", "Response & Action", undefined, undefined, undefined, { field: "condition", equals: ["Accepted with notation", "Damaged", "Short / missing", "Refused", "Unable to deliver"] }), F("follow_up", "Customer / carrier follow-up", "textarea", "Response & Action"), F("claim_exception", "Claim / exception reference", "text", "Response & Action"), F("archive", "POD archive / customer record", "text", "Closure", true), F("invoice_release", "Billing / revenue recognition released?", "select", "Closure", true, YES_NO_NA), F("status", "Delivery confirmation status", "select", "Closure", true, ["Complete", "Exception open", "POD missing", "Customer dispute", "Carrier investigation"]),
    ],
    controls: ["Delivery timing, recipient, quantity, and condition are confirmed", "Exception is linked to follow-up / claim", "POD is archived and accessible", "Billing / customer record status is correctly controlled"],
    approvalRoles: ["Logistics Coordinator", "Customer Service", "Finance / Billing", "Claims / Quality Authority"], evidenceRequired: true,
    evidenceGuidance: ["Signed / electronic POD", "Delivery photographs", "Carrier tracking", "Exception / claim and customer confirmation"],
    escalations: [escalation("POD shows damage, shortage, refusal, or dispute", "Customer recovery / claims workflow"), escalation("POD missing beyond customer-defined SLA", "Carrier escalation")],
  },
  export: {
    procedure: procedure("DL-08.10", "Export and Trade Compliance Verification", "Trade Compliance / Logistics", ["Applicable export, customs, and sanctions requirements"]),
    stages: ["Classify item", "Screen parties", "Determine license", "Verify destination / end use", "Prepare documents", "Authorize", "File / retain"],
    fields: [
      F("shipment", "Shipment / order", "text", "Record Context", true), F("customer_consignee", "Customer, consignee, end user", "textarea", "Record Context", true), F("destination", "Destination country / route", "text", "Record Context", true), F("items", "Items, quantities, values, and origin", "textarea", "Evaluation", true), F("eccn", "ECCN / export classification", "text", "Evaluation", true), F("hts", "HTS / customs classification", "text", "Evaluation", true), F("country_origin", "Country of origin", "text", "Evaluation", true), F("party_screening", "Restricted-party screening", "select", "Evaluation", true, RESULT), F("end_use", "End-use / end-user verification", "select", "Evaluation", true, RESULT), F("license", "License / authorization determination", "select", "Evaluation", true, ["NLR / no license required", "License exception", "License required / obtained", "Prohibited / hold", "Pending classification"]), F("incoterms", "Incoterms / importer of record", "text", "Evaluation", true),
      F("documents", "Commercial invoice, packing list, origin, license, and filing", "textarea", "Response & Action", true), F("aes_reference", "AES / filing / broker reference", "text", "Response & Action"), F("hold_reason", "Compliance hold / review", "textarea", "Response & Action", undefined, undefined, undefined, { field: "license", equals: ["Prohibited / hold", "Pending classification"] }), F("authorization", "Trade-compliance authorization", "text", "Closure", true), F("record_location", "Export-record retention location", "text", "Closure", true), F("release", "Export release", "select", "Closure", true, ["Released", "Released with license / exception", "Held", "Prohibited"]),
    ],
    controls: ["Items, origin, classification, parties, destination, and end use are verified", "License determination and filings are complete", "Prohibited / uncertain transactions are held", "Authorization and record retention are documented"],
    approvalRoles: ["Trade Compliance Specialist", "Empowered Official", "Logistics Coordinator", "Legal / Executive Authority"], evidenceRequired: true,
    evidenceGuidance: ["Classification record", "Restricted-party screening", "License / exception / filing", "Commercial documents and authorization"],
    escalations: [escalation("Restricted-party, diversion, or prohibited-end-use concern", "Immediate Trade Compliance / Legal hold"), escalation("Classification or license is unresolved", "Do not export")],
  },
  appointment: {
    procedure: procedure("DL-08.11", "Delivery Appointment and Dock Scheduling", "Logistics", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.4.2"]),
    stages: ["Review requirement", "Request slot", "Confirm carrier", "Communicate instructions", "Monitor", "Check in", "Complete"],
    fields: [
      F("shipment", "Shipment / order", "text", "Record Context", true), F("customer", "Customer / delivery facility", "text", "Record Context", true), F("carrier", "Carrier / driver", "text", "Record Context", true), F("requested_window", "Requested delivery window", "text", "Evaluation", true), F("confirmed_window", "Confirmed appointment date / time", "datetime-local", "Evaluation", true), F("confirmation", "Appointment confirmation / reference", "text", "Evaluation", true), F("dock_instructions", "Dock, gate, PPE, contact, and site instructions", "textarea", "Evaluation", true), F("equipment", "Trailer / liftgate / equipment requirements", "textarea", "Evaluation"), F("documents", "Pre-arrival documents / ASN / portal status", "select", "Evaluation", true, RESULT),
      F("eta", "Carrier ETA / status", "datetime-local", "Response & Action"), F("risk", "Appointment risk", "select", "Response & Action", true, ["On plan", "At risk", "Late", "Reschedule required", "Customer hold"]), F("communication", "Customer / carrier communication", "textarea", "Response & Action", true), F("reschedule", "New appointment / approval", "textarea", "Response & Action", undefined, undefined, undefined, { field: "risk", equals: ["Late", "Reschedule required", "Customer hold"] }),
      F("check_in", "Carrier check-in / arrival", "datetime-local", "Closure"), F("unload_complete", "Unload / delivery complete", "datetime-local", "Closure"), F("status", "Appointment status", "select", "Closure", true, ["Completed", "On schedule", "Late but accepted", "Rescheduled", "Missed / exception"]),
    ],
    controls: ["Customer appointment and site requirements are known", "Carrier has confirmed window and instructions", "ETA and risk are actively monitored", "Arrival, completion, and exception are recorded"],
    approvalRoles: ["Logistics Coordinator", "Carrier Dispatcher", "Customer Receiving Contact", "Customer Service"], evidenceRequired: false,
    evidenceGuidance: ["Appointment confirmation", "Portal / ASN / instructions", "Carrier status / communication", "Check-in / completion evidence"],
    escalations: [escalation("Carrier will miss confirmed window", "Customer and carrier recovery before cutoff"), escalation("Customer hold / no appointment available", "Delivery exception and operations review")],
  },
  return: {
    procedure: procedure("DL-08.12", "Return Material Authorization and Reverse Logistics", "Customer Service / Quality / Logistics", ["ISO 9001:2015 8.5.5", "ISO 9001:2015 8.7"]),
    stages: ["Request return", "Authorize", "Issue instructions", "Receive", "Inspect", "Disposition", "Credit / replace", "Close"],
    fields: [
      F("rma", "RMA / return number", "text", "Record Context", true), F("customer", "Customer / return origin", "text", "Record Context", true), F("product", "Product / part / serial / lot", "textarea", "Record Context", true), F("original_order", "Original order / shipment / invoice", "text", "Record Context", true), F("return_reason", "Return reason", "select", "Evaluation", true, ["Quality defect", "Warranty", "Shipping damage", "Wrong item / quantity", "Customer cancellation", "No defect found / evaluation", "Repair / service", "Recall / field action"]), F("qty_authorized", "Quantity authorized", "number", "Evaluation", true), F("customer_condition", "Customer-reported condition / evidence", "textarea", "Evaluation", true), F("hazards", "Hazardous residue, battery, pressure, or special handling", "textarea", "Evaluation"),
      F("instructions", "Packaging, labeling, carrier, and return instructions", "textarea", "Response & Action", true), F("authorization_status", "Return authorization", "select", "Response & Action", true, ["Authorized", "Authorized with conditions", "Rejected", "More information required"]), F("receipt_date", "Return receipt date", "date", "Closure"), F("qty_received", "Quantity received", "number", "Closure"), F("received_condition", "Received condition / identity verification", "textarea", "Closure"), F("inspection", "Inspection / teardown / evaluation reference", "text", "Closure"), F("disposition", "Disposition", "select", "Closure", true, ["Repair", "Replace", "Credit", "Return to customer", "Scrap", "Supplier return", "Engineering / CAPA hold"]), F("financial_action", "Credit / replacement / charge reference", "text", "Closure"), F("status", "RMA status", "select", "Closure", true, ["Closed", "Awaiting return", "Inspection active", "Disposition pending", "Customer / financial action pending"]),
    ],
    controls: ["Return is authorized and traceable to original transaction", "Customer receives controlled packaging / handling instructions", "Receipt quantity, identity, condition, and hazards are verified", "Inspection, disposition, and financial / customer action are linked"],
    approvalRoles: ["Customer Service", "Quality / Warranty Authority", "Logistics Coordinator", "Finance / Commercial Authority"], evidenceRequired: true,
    evidenceGuidance: ["Customer return evidence", "RMA authorization / instructions", "Receipt and condition photographs", "Inspection, disposition, and financial action"],
    escalations: [escalation("Return presents safety / contamination / pressure hazard", "EHS / Quality controlled receipt"), escalation("Systemic defect or recall signal", "CAPA / field-action leadership review")],
  },
};

export const smartDeliveryConfig = specializeWorkspace(
  smartWorkspaceConfigs.delivery,
  profiles,
  "Verify, document, release, ship, track, recover, and close customer deliveries through purpose-built packaging, documentation, export, appointment, carrier, proof-of-delivery, exception, damage, and return workflows.",
  "DELIVERY EXECUTION, CUSTOMER RELEASE & LOGISTICS ASSURANCE",
);
