import { smartWorkspaceConfigs } from "@/lib/smart-workflow-config";
import { F, RISK, RESULT, YES_NO, escalation, procedure, specializeWorkspace, type ToolProfiles } from "@/lib/smart-specialization-helpers";

const profiles: ToolProfiles = {
  receiving: {
    procedure: procedure("WH-08.01", "Material Receiving and Receipt Control", "Warehouse / Receiving", ["ISO 9001:2015 8.4.2", "ISO 9001:2015 8.5.2", "ISO 9001:2015 8.5.4"]),
    stages: ["Identify receipt", "Verify supplier / PO", "Count", "Inspect condition", "Record traceability", "Assign status", "Route"],
    fields: [
      F("supplier", "Supplier / source", "text", "Record Context", true), F("po", "PO / transfer / RMA", "text", "Record Context", true), F("packing_list", "Packing list / BOL", "text", "Record Context", true), F("carrier", "Carrier / delivery method", "text", "Record Context"),
      F("part", "Part / material / product", "text", "Evaluation", true), F("revision", "Revision / specification", "text", "Evaluation"), F("qty_expected", "Quantity expected", "number", "Evaluation", true), F("qty_received", "Quantity received", "number", "Evaluation", true), F("uom", "Unit of measure", "text", "Evaluation", true),
      F("lot_serial", "Lot / heat / batch / serial", "text", "Evaluation"), F("shelf_life", "Expiration / shelf-life date", "date", "Evaluation"), F("condition", "Packaging and material condition", "select", "Evaluation", true, ["Acceptable", "Damage observed", "Wet / contaminated", "Packaging compromised", "Identification concern", "Quantity discrepancy"]),
      F("condition_detail", "Damage, shortage, overage, or identification details", "textarea", "Response & Action", true, undefined, undefined, { field: "condition", equals: ["Damage observed", "Wet / contaminated", "Packaging compromised", "Identification concern", "Quantity discrepancy"] }),
      F("inspection_required", "Receiving inspection required?", "select", "Response & Action", true, YES_NO), F("status", "Receipt status", "select", "Response & Action", true, ["Accepted for put-away", "Inspection pending", "Quarantine / hold", "Rejected / return", "Customer-owned property"]),
      F("temporary_location", "Controlled staging / hold location", "text", "Response & Action", true), F("erp_receipt", "ERP / inventory receipt transaction", "text", "Closure", true), F("routing", "Next destination / queue", "select", "Closure", true, ["Put-away", "Receiving inspection", "Quarantine", "Production / cross-dock", "Return processing"]),
    ],
    controls: ["Supplier, PO, item, quantity, and UOM are reconciled", "Condition and traceability are verified before transaction", "Material status is physically and electronically controlled", "Receipt is routed to the correct next queue"],
    approvalRoles: ["Receiver", "Inventory Control", "Receiving Supervisor", "Quality Release Authority"], evidenceRequired: false,
    evidenceGuidance: ["Packing list / BOL", "Label and traceability photographs", "Damage or discrepancy evidence", "ERP receipt confirmation"],
    escalations: [escalation("Damage, shortage, or identification mismatch is found", "Receiving supervisor, Purchasing, and Quality"), escalation("Customer-owned or shelf-life-controlled material lacks traceability", "Quarantine pending Quality review")],
  },
  inspection: {
    procedure: procedure("WH-08.02", "Receiving Inspection and Material Release", "Quality / Receiving", ["ISO 9001:2015 8.4.2", "ISO 9001:2015 8.6"]),
    stages: ["Identify lot", "Verify plan", "Sample", "Inspect / test", "Record results", "Control failure", "Release"],
    fields: [
      F("receipt", "Receipt / PO / lot", "text", "Record Context", true), F("supplier", "Supplier", "text", "Record Context", true), F("part", "Part / material", "text", "Record Context", true), F("qty_received", "Quantity received", "number", "Evaluation", true),
      F("inspection_level", "Inspection plan / level", "text", "Evaluation", true), F("sample_size", "Sample size", "number", "Evaluation", true), F("characteristics", "Characteristics / documents verified", "textarea", "Evaluation", true), F("specification", "Specification / acceptance criteria", "textarea", "Evaluation", true),
      F("qty_passed", "Sample quantity passed", "number", "Evaluation", true), F("qty_failed", "Sample quantity failed", "number", "Evaluation", true), F("result", "Inspection result", "select", "Evaluation", true, RESULT),
      F("defect_detail", "Defect / discrepancy detail", "textarea", "Response & Action", true, undefined, undefined, { field: "result", equals: ["Fail", "Conditional", "Unable to verify"] }), F("ncr", "NCR / supplier issue reference", "text", "Response & Action", undefined, undefined, undefined, { field: "result", equals: ["Fail", "Conditional"] }),
      F("disposition", "Material decision", "select", "Closure", true, ["Release", "Conditional release", "Hold", "Reject / return", "Sort / screen"]), F("released_location", "Released / hold location", "text", "Closure", true),
    ],
    controls: ["Current inspection plan and supplier status are verified", "Sampling and results are traceable to the receipt lot", "Failed material is controlled and linked to NCR / supplier action", "Release is completed by authorized personnel"],
    approvalRoles: ["Receiving Inspector", "Quality Technician", "Quality Engineer", "Authorized Release Personnel"], evidenceRequired: true,
    evidenceGuidance: ["Inspection plan and results", "Certificates / documentation", "Defect photographs", "Release or hold evidence"],
    escalations: [escalation("Failed material threatens production", "Quality, Purchasing, Operations, and Supplier response"), escalation("Inspection cannot be completed due to missing requirements", "Hold and technical review")],
  },
  damage: {
    procedure: procedure("WH-08.03", "Incoming Damage and Freight Claim Control", "Receiving / Logistics", ["ISO 9001:2015 8.4", "ISO 9001:2015 8.5.4"]),
    stages: ["Stop / protect", "Document carrier condition", "Quantify damage", "Notify", "Contain", "Claim / disposition", "Close"],
    fields: [
      F("receipt", "Receipt / PO / BOL", "text", "Record Context", true), F("carrier", "Carrier", "text", "Record Context", true), F("trailer", "Trailer / vehicle / seal", "text", "Record Context"), F("delivery_date", "Delivery date", "date", "Record Context", true),
      F("part", "Affected item / product", "text", "Evaluation", true), F("qty_damaged", "Quantity damaged", "number", "Evaluation", true), F("damage_type", "Damage type", "select", "Evaluation", true, ["Crushed / impact", "Water / moisture", "Puncture / abrasion", "Tip-over / load shift", "Missing / shortage", "Temperature exposure", "Contamination", "Other / customer-defined"]),
      F("packaging_condition", "Packaging / blocking / bracing condition", "textarea", "Evaluation", true), F("concealed", "Concealed damage?", "select", "Evaluation", true, YES_NO), F("risk", "Product / business risk", "select", "Evaluation", true, RISK),
      F("carrier_notation", "Carrier receipt notation / exception number", "text", "Response & Action", true), F("notifications", "Carrier, supplier, Purchasing, and Quality notifications", "textarea", "Response & Action", true), F("containment", "Segregation and preservation action", "textarea", "Response & Action", true),
      F("claim_value", "Estimated claim value ($)", "number", "Response & Action"), F("claim_reference", "Freight claim / supplier claim reference", "text", "Closure"), F("disposition", "Disposition", "select", "Closure", true, ["Accept after inspection", "Repair / repackage", "Return", "Scrap", "Claim pending", "Replacement requested"]), F("closure", "Claim / recovery status", "select", "Closure", true, ["Closed", "Carrier pending", "Supplier pending", "Commercial settlement pending", "Internal disposition pending"]),
    ],
    controls: ["Condition was documented before unloading or alteration where practical", "Carrier exception and affected quantity are recorded", "Damaged material is segregated and protected", "Claim, disposition, and recovery are traceable"],
    approvalRoles: ["Receiver", "Logistics Coordinator", "Warehouse Supervisor", "Quality / Claims Authority"], evidenceRequired: true,
    evidenceGuidance: ["Trailer, seal, pallet, and packaging photographs", "BOL / delivery receipt notation", "Product damage evidence", "Claim and disposition records"],
    escalations: [escalation("Damage may affect safety or customer-owned product", "Quality and leadership immediately"), escalation("Carrier leaves before exception is recorded", "Logistics / claims escalation")],
  },
  putaway: {
    procedure: procedure("WH-08.04", "Controlled Put-Away and Location Management", "Warehouse", ["ISO 9001:2015 8.5.2", "ISO 9001:2015 8.5.4"]),
    stages: ["Confirm release", "Scan identity", "Validate location", "Move", "Confirm quantity", "Update system", "Close"],
    fields: [
      F("receipt", "Receipt / inventory transaction", "text", "Record Context", true), F("item", "Item / part", "text", "Record Context", true), F("lot_serial", "Lot / serial / batch", "text", "Record Context"), F("quantity", "Quantity to put away", "number", "Evaluation", true),
      F("material_status", "Material status", "select", "Evaluation", true, ["Released", "Inspection pending", "Quarantine", "Customer-owned", "Restricted / controlled"]), F("from_location", "From staging location", "text", "Evaluation", true), F("recommended_location", "System-recommended location", "text", "Evaluation"), F("destination", "Actual destination location", "text", "Evaluation", true),
      F("location_class", "Location suitability", "select", "Evaluation", true, ["Standard rack / bin", "Heavy / oversized", "Hazardous / chemical", "Temperature controlled", "Secure / customer-owned", "Quarantine", "Outdoor / covered"]), F("capacity_check", "Location capacity and compatibility", "select", "Evaluation", true, RESULT),
      F("variance", "Deviation from recommended location / reason", "textarea", "Response & Action", undefined, undefined, undefined, { field: "capacity_check", equals: ["Fail", "Conditional"] }), F("system_update", "ERP / WMS location update", "text", "Closure", true), F("quantity_confirmed", "Quantity confirmed at destination", "number", "Closure", true), F("label_visible", "Identity / status label visible and protected?", "select", "Closure", true, YES_NO),
    ],
    controls: ["Material release and status are verified", "Destination is compatible with weight, hazard, preservation, and security needs", "Quantity and traceability remain intact", "Physical and system locations agree"],
    approvalRoles: ["Material Handler", "Inventory Control", "Warehouse Lead", "Quality Authority for restricted status"], evidenceRequired: false,
    evidenceGuidance: ["Barcode / label scan", "Destination location photograph", "Location-capacity exception", "WMS / ERP transaction"],
    escalations: [escalation("Material status or location suitability is uncertain", "Stop movement and Warehouse / Quality review"), escalation("Physical and system location cannot be reconciled", "Inventory Control investigation")],
  },
  lookup: {
    procedure: procedure("WH-08.05", "Inventory Identity, Status, and Location Verification", "Inventory Control", ["ISO 9001:2015 8.5.2"]),
    stages: ["Search", "Verify identity", "Verify status", "Verify location", "Check allocation", "Resolve mismatch"],
    fields: [
      F("search_type", "Lookup method", "select", "Record Context", true, ["Part number", "Barcode / QR", "Lot / serial", "Location", "Work order allocation", "Customer-owned property"]), F("search_value", "Search value", "text", "Record Context", true),
      F("item", "Confirmed item / description", "text", "Evaluation", true), F("lot_serial", "Lot / serial / batch", "text", "Evaluation"), F("quantity_on_hand", "Quantity on hand", "number", "Evaluation", true), F("uom", "UOM", "text", "Evaluation", true),
      F("system_location", "System location", "text", "Evaluation", true), F("physical_location", "Physical location verified", "text", "Evaluation", true), F("status", "Inventory status", "select", "Evaluation", true, ["Available", "Allocated", "Inspection pending", "Quarantine / hold", "Rejected", "Expired", "Customer-owned"]),
      F("allocation", "Allocated job / order / customer", "text", "Evaluation"), F("match", "Physical-to-system match", "select", "Closure", true, ["Match", "Quantity mismatch", "Location mismatch", "Identity mismatch", "Status mismatch"]), F("resolution", "Mismatch containment / correction", "textarea", "Closure", undefined, undefined, undefined, { field: "match", equals: ["Quantity mismatch", "Location mismatch", "Identity mismatch", "Status mismatch"] }),
    ],
    controls: ["Item identity, quantity, status, and location are verified", "Allocation and ownership restrictions are visible", "Mismatch is contained before material movement", "Correction preserves transaction traceability"],
    approvalRoles: ["Inventory Control", "Warehouse Lead", "Quality Authority", "Customer Property Coordinator"], evidenceRequired: false,
    evidenceGuidance: ["Barcode / label scan", "Physical location photograph", "ERP / WMS inquiry", "Mismatch correction evidence"],
    escalations: [escalation("Status or customer ownership mismatch is found", "Quality / Customer Property review"), escalation("Inventory cannot be physically located", "Cycle count and loss investigation")],
  },
  transfer: {
    procedure: procedure("WH-08.06", "Inventory Transfer and Traceability", "Warehouse / Inventory Control", ["ISO 9001:2015 8.5.2", "ISO 9001:2015 8.5.4"]),
    stages: ["Request", "Verify item", "Authorize", "Pick", "Move", "Confirm destination", "Reconcile"],
    fields: [
      F("item", "Item / part", "text", "Record Context", true), F("lot_serial", "Lot / serial / batch", "text", "Record Context"), F("quantity", "Transfer quantity", "number", "Evaluation", true), F("uom", "UOM", "text", "Evaluation", true),
      F("from", "From location", "text", "Evaluation", true), F("to", "To location", "text", "Evaluation", true), F("reason", "Transfer reason", "select", "Evaluation", true, ["Production demand", "Replenishment", "Quarantine / hold", "Inspection", "Consolidation", "Customer allocation", "Return / RMA", "Location correction"]),
      F("status", "Material status", "select", "Evaluation", true, ["Available", "Allocated", "Inspection pending", "Quarantine", "Rejected", "Customer-owned"]), F("authorization", "Required authorization / request reference", "text", "Response & Action", true),
      F("picked_qty", "Quantity picked", "number", "Response & Action", true), F("received_qty", "Quantity confirmed at destination", "number", "Closure", true), F("transaction", "ERP / WMS transfer transaction", "text", "Closure", true), F("reconciled", "Transfer reconciled?", "select", "Closure", true, YES_NO), F("variance", "Transfer variance / corrective action", "textarea", "Closure", undefined, undefined, undefined, { field: "reconciled", equals: "No" }),
    ],
    controls: ["Identity, status, ownership, and quantity are verified before movement", "Source and destination are authorized", "Picked and received quantities are reconciled", "System transaction matches physical movement"],
    approvalRoles: ["Material Handler", "Warehouse Lead", "Inventory Control", "Quality Authority for held material"], evidenceRequired: false,
    evidenceGuidance: ["Transfer request", "Barcode scans", "Source / destination evidence", "ERP / WMS transaction"],
    escalations: [escalation("Held, rejected, or customer-owned material is moved without authority", "Immediate Quality / Warehouse leadership review"), escalation("Quantity variance remains unresolved", "Inventory Control investigation")],
  },
  cycle: {
    procedure: procedure("WH-09.01", "Cycle Counting and Inventory Adjustment", "Inventory Control / Finance", ["ISO 9001:2015 7.1.3", "ISO 9001:2015 8.5.2"]),
    stages: ["Freeze / define scope", "Blind count", "Recount", "Investigate variance", "Approve adjustment", "Post", "Verify"],
    fields: [
      F("count_type", "Count type", "select", "Record Context", true, ["Scheduled cycle count", "ABC count", "Location count", "Item count", "Triggered variance count", "Physical inventory"]), F("location", "Location / count zone", "text", "Record Context", true), F("item", "Item / part", "text", "Record Context", true), F("lot_serial", "Lot / serial / batch", "text", "Record Context"),
      F("system_qty", "System quantity", "number", "Evaluation", true), F("first_count", "Blind first count", "number", "Evaluation", true), F("recount_required", "Independent recount required?", "select", "Evaluation", true, YES_NO), F("second_count", "Independent recount", "number", "Evaluation", undefined, undefined, undefined, { field: "recount_required", equals: "Yes" }),
      F("variance_reason", "Variance category", "select", "Evaluation", true, ["No variance", "Unposted transaction", "Wrong location", "UOM / conversion", "Pick / issue error", "Receipt error", "Scrap / damage", "Identity / lot error", "Possible loss / unknown"]), F("investigation", "Transaction and physical investigation", "textarea", "Response & Action", true),
      F("approved_qty", "Approved final quantity", "number", "Closure", true), F("adjustment", "Adjustment transaction / approval", "text", "Closure", true), F("root_cause_action", "Systemic corrective action", "textarea", "Closure"), F("verified", "Post-adjustment verification", "select", "Closure", true, RESULT),
    ],
    controls: ["Count scope was controlled and first count was blind", "Required recount is independent", "Variance is investigated before adjustment", "Adjustment authority and post-transaction verification are documented"],
    approvalRoles: ["Cycle Counter", "Inventory Control", "Warehouse Manager", "Finance / Controller"], evidenceRequired: true,
    evidenceGuidance: ["Count sheets / scanner records", "Location and label photographs", "Transaction-history review", "Adjustment approval and verification"],
    escalations: [escalation("Large, repeated, or unexplained variance", "Warehouse Manager, Finance, and process investigation"), escalation("Customer-owned or controlled material variance", "Quality / customer-property authority")],
  },
  request: {
    procedure: procedure("WH-08.07", "Production Material Request and Delivery", "Warehouse / Operations", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.5.1"]),
    stages: ["Request", "Prioritize", "Verify availability", "Pick", "Deliver", "Confirm", "Close"],
    fields: [
      F("requesting_area", "Requesting area / work center", "text", "Record Context", true), F("requester", "Requester", "text", "Record Context", true), F("work_order", "Work order / job", "text", "Record Context", true), F("item", "Item / part / material", "text", "Evaluation", true), F("quantity", "Quantity required", "number", "Evaluation", true), F("uom", "UOM", "text", "Evaluation", true),
      F("need_by", "Need-by date / time", "datetime-local", "Evaluation", true), F("priority", "Operational priority", "select", "Evaluation", true, ["Routine replenishment", "Scheduled job", "Line at risk", "Line stopped", "Customer expedite"]), F("allocation_status", "Availability / allocation status", "select", "Evaluation", true, ["Available", "Partial", "Not available", "Inspection pending", "Quality hold", "Substitute proposed"]),
      F("shortage_plan", "Shortage, substitute, or recovery plan", "textarea", "Response & Action", undefined, undefined, undefined, { field: "allocation_status", equals: ["Partial", "Not available", "Inspection pending", "Quality hold", "Substitute proposed"] }), F("picked_qty", "Quantity picked", "number", "Response & Action", true), F("delivered_to", "Delivery point / recipient", "text", "Closure", true), F("delivered_at", "Delivery date / time", "datetime-local", "Closure", true), F("received_qty", "Quantity received by production", "number", "Closure", true), F("status", "Request status", "select", "Closure", true, ["Fulfilled", "Partially fulfilled", "Backordered", "Cancelled", "Escalated"]),
    ],
    controls: ["Request is linked to valid demand", "Availability, status, and allocation are verified", "Pick and delivery preserve identity and traceability", "Production confirms quantity and receipt timing"],
    approvalRoles: ["Material Handler", "Warehouse Lead", "Production Supervisor", "Inventory Control"], evidenceRequired: false,
    evidenceGuidance: ["Material request / Kanban signal", "Pick / barcode evidence", "Delivery confirmation", "Shortage escalation"],
    escalations: [escalation("Line is stopped or customer commitment is at risk", "Warehouse and Operations leadership immediately"), escalation("Material is held or substitute is proposed", "Quality / Engineering approval")],
  },
  kit: {
    procedure: procedure("WH-08.08", "Production Job Kitting", "Warehouse / Production Control", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.5.1"]),
    stages: ["Load BOM / pick list", "Pick", "Verify identity", "Check completeness", "Control shortages", "Stage", "Release"],
    fields: [
      F("work_order", "Work order / job", "text", "Record Context", true), F("product", "Product / assembly", "text", "Record Context", true), F("kit_id", "Kit / container ID", "text", "Record Context", true), F("required_lines", "Required BOM / pick-list lines", "number", "Evaluation", true), F("complete_lines", "Complete lines", "number", "Evaluation", true), F("short_lines", "Short / missing lines", "number", "Evaluation", true),
      F("substitutions", "Substitution / alternate material", "textarea", "Evaluation"), F("lot_serial_control", "Lot / serial / heat traceability verified?", "select", "Evaluation", true, YES_NO), F("quality_status", "All material released and acceptable?", "select", "Evaluation", true, YES_NO),
      F("shortage_detail", "Shortage, ETA, and impact", "textarea", "Response & Action", undefined, undefined, undefined, { field: "short_lines", equals: "1" }), F("staging_location", "Controlled staging location", "text", "Response & Action", true), F("packaging_protection", "Protection / separation / preservation", "select", "Response & Action", true, RESULT),
      F("kit_status", "Kit status", "select", "Closure", true, ["Complete / released", "Complete with approved substitute", "Partial / controlled shortage", "Held", "Cancelled"]), F("production_acceptance", "Production recipient / acceptance", "text", "Closure", true),
    ],
    controls: ["Kit is tied to current BOM / pick list and work order", "Identity, quantity, status, and traceability are verified", "Shortages and substitutions are controlled", "Kit is protected, staged, and accepted by production"],
    approvalRoles: ["Kitter / Material Handler", "Warehouse Lead", "Production Control", "Quality / Engineering for substitutions"], evidenceRequired: true,
    evidenceGuidance: ["Pick list / BOM", "Kit and label photographs", "Shortage / substitution approval", "Production acceptance"],
    escalations: [escalation("Kit shortage prevents planned start", "Production Control and Operations"), escalation("Substitute or held material is included", "Quality / Engineering review")],
  },
  quarantine: {
    procedure: procedure("WH-08.09", "Quarantine and Held Inventory Control", "Quality / Warehouse", ["ISO 9001:2015 8.7"]),
    stages: ["Place hold", "Identify", "Segregate", "Track aging / value", "Assign disposition", "Verify action", "Release / close"],
    fields: [
      F("hold_id", "Hold / quarantine ID", "text", "Record Context", true), F("reason", "Hold reason", "select", "Record Context", true, ["NCR", "Receiving inspection", "Supplier issue", "Customer return", "Expired / shelf life", "Identification uncertainty", "Engineering review", "Investigation / legal hold"]), F("item", "Item / product", "text", "Record Context", true), F("lot_serial", "Lot / serial / batch", "text", "Record Context"),
      F("quantity", "Quantity on hold", "number", "Evaluation", true), F("estimated_value", "Estimated inventory value ($)", "number", "Evaluation"), F("hold_date", "Hold start date", "date", "Evaluation", true), F("location", "Quarantine location", "text", "Evaluation", true), F("physical_control", "Physical identification / segregation", "select", "Evaluation", true, RESULT), F("system_control", "ERP / WMS hold status", "select", "Evaluation", true, RESULT),
      F("owner", "Disposition owner", "text", "Response & Action", true), F("disposition_due", "Disposition due date", "date", "Response & Action", true), F("disposition", "Disposition", "select", "Response & Action", true, ["Pending", "Release", "Rework", "Return", "Scrap", "Use as-is / concession", "Sort / screen"]), F("action_reference", "NCR / MRB / supplier / customer reference", "text", "Response & Action", true),
      F("verification", "Disposition execution and quantity verification", "textarea", "Closure", true), F("release_authority", "Release / removal authorization", "text", "Closure", true), F("status", "Final status", "select", "Closure", true, ["Closed / removed", "Released", "Partially dispositioned", "Open / aging", "Escalated"]),
    ],
    controls: ["Held inventory is physically and electronically controlled", "Quantity, value, age, and owner are visible", "Disposition authority and linked record are documented", "Final quantity and location are verified before closure"],
    approvalRoles: ["Quality Authority", "Warehouse Supervisor", "MRB / Engineering Authority", "Customer / Supplier Authority"], evidenceRequired: true,
    evidenceGuidance: ["Hold labels and segregation photographs", "ERP / WMS hold evidence", "NCR / MRB / disposition authorization", "Final quantity and location verification"],
    escalations: [escalation("Hold age or value exceeds site threshold", "Quality and Operations management review"), escalation("Physical and system hold controls disagree", "Immediate inventory containment")],
  },
  fifo: {
    procedure: procedure("WH-08.10", "FIFO, FEFO, and Shelf-Life Control", "Warehouse / Quality", ["ISO 9001:2015 8.5.4"]),
    stages: ["Select item", "Review lots", "Verify dates", "Confirm rotation", "Control exception", "Release"],
    fields: [
      F("item", "Item / material", "text", "Record Context", true), F("location", "Storage / pick location", "text", "Record Context", true), F("rotation_rule", "Rotation rule", "select", "Evaluation", true, ["FIFO", "FEFO", "Customer-specific sequence", "Lot-controlled issue", "No aging requirement"]),
      F("oldest_lot", "Oldest / earliest-expiring lot", "text", "Evaluation", true), F("oldest_date", "Receipt / manufacture / expiration date", "date", "Evaluation", true), F("selected_lot", "Lot selected for issue", "text", "Evaluation", true), F("selected_date", "Selected lot date", "date", "Evaluation", true), F("remaining_shelf_life", "Minimum remaining shelf-life requirement", "text", "Evaluation"),
      F("rotation_result", "Rotation verification", "select", "Evaluation", true, RESULT), F("exception", "Rotation / shelf-life exception", "textarea", "Response & Action", undefined, undefined, undefined, { field: "rotation_result", equals: ["Fail", "Conditional", "Unable to verify"] }), F("disposition", "Exception disposition", "select", "Response & Action", undefined, ["Re-sequence stock", "Hold expired / aged material", "Quality concession", "Return / scrap", "Customer approval", "Not applicable"]),
      F("pick_release", "Pick / issue release", "select", "Closure", true, ["Released", "Held", "Released with approval"]), F("next_review", "Next aging / shelf-life review", "date", "Closure"),
    ],
    controls: ["Applicable rotation rule and shelf-life requirement are known", "Selected lot is compared with available stock", "Exception is controlled before issue", "Expired or noncompliant stock cannot be released without authority"],
    approvalRoles: ["Material Handler", "Inventory Control", "Warehouse Lead", "Quality Authority"], evidenceRequired: false,
    evidenceGuidance: ["Lot and expiration labels", "Inventory age report", "Exception / concession approval", "Re-sequenced stock evidence"],
    escalations: [escalation("Expired or insufficient-shelf-life material is found", "Quality hold and disposition"), escalation("System cannot identify correct lot sequence", "Inventory Control correction")],
  },
  shipment: {
    procedure: procedure("WH-08.11", "Outbound Shipment Verification", "Warehouse / Quality / Logistics", ["ISO 9001:2015 8.5.4", "ISO 9001:2015 8.6"]),
    stages: ["Identify order", "Verify product", "Verify packaging", "Verify documents", "Inspect load", "Authorize", "Ship"],
    fields: [
      F("shipment", "Shipment / load / order", "text", "Record Context", true), F("customer", "Customer / destination", "text", "Record Context", true), F("carrier", "Carrier / service", "text", "Record Context", true), F("product", "Product / part", "text", "Evaluation", true), F("qty_required", "Quantity required", "number", "Evaluation", true), F("qty_loaded", "Quantity loaded", "number", "Evaluation", true), F("serial_lot", "Serial / lot / package traceability", "textarea", "Evaluation", true),
      F("product_status", "Quality release / hold status", "select", "Evaluation", true, RESULT), F("packaging", "Packaging, preservation, blocking, and bracing", "select", "Evaluation", true, RESULT), F("labels", "Labels, marks, and customer identification", "select", "Evaluation", true, RESULT), F("documents", "Packing list, certificates, reports, and customer documents", "select", "Evaluation", true, RESULT), F("vehicle_condition", "Trailer / vehicle condition and seal", "select", "Evaluation", true, RESULT),
      F("exception", "Shipment exception / missing requirement", "textarea", "Response & Action", undefined, undefined, undefined, { field: "product_status", equals: ["Fail", "Conditional", "Unable to verify"] }), F("release", "Shipment release decision", "select", "Closure", true, ["Released to ship", "Held", "Conditional release", "Rejected / unload"]), F("seal_number", "Seal number / final control", "text", "Closure"), F("ship_confirmation", "ERP / TMS shipment confirmation", "text", "Closure", true),
    ],
    controls: ["Correct product, quantity, serial / lot, and customer are verified", "Quality release, packaging, labels, and documents are complete", "Vehicle condition and load securement are acceptable", "Authorized release and shipment transaction are documented"],
    approvalRoles: ["Shipping Verifier", "Warehouse Supervisor", "Quality Release Authority", "Logistics Coordinator"], evidenceRequired: true,
    evidenceGuidance: ["Product and serial / lot photographs", "Packaging / blocking / bracing photographs", "Labels and documents", "Trailer, seal, and final load evidence"],
    escalations: [escalation("Quality release, documentation, or customer requirement is incomplete", "Hold shipment and route to responsible authority"), escalation("Load securement or vehicle condition is unsafe", "Stop loading and Logistics / EHS review")],
  },
  photos: {
    procedure: procedure("WH-08.12", "Shipping Photographic Evidence", "Warehouse / Logistics", ["ISO 9001:2015 8.5.4"]),
    stages: ["Identify shipment", "Capture product", "Capture packaging", "Capture labels", "Capture load", "Verify completeness", "Release evidence"],
    fields: [
      F("shipment", "Shipment / load / order", "text", "Record Context", true), F("customer", "Customer / destination", "text", "Record Context", true), F("product", "Product / serial / package", "textarea", "Record Context", true),
      F("required_views", "Required photographic views", "select", "Evaluation", true, ["Standard shipment set", "Customer-specific set", "High-value / oversized", "Export / container", "Damage / exception follow-up"]), F("product_views", "Product identity / condition captured?", "select", "Evaluation", true, YES_NO), F("packaging_views", "Packaging / preservation captured?", "select", "Evaluation", true, YES_NO), F("label_views", "Labels / marks / serials captured?", "select", "Evaluation", true, YES_NO), F("securement_views", "Blocking / bracing / load securement captured?", "select", "Evaluation", true, YES_NO), F("trailer_views", "Trailer / container / seal captured?", "select", "Evaluation", true, YES_NO),
      F("exception", "Missing view / obstruction / exception", "textarea", "Response & Action"), F("file_reference", "Customer report / evidence package reference", "text", "Closure", true), F("review_result", "Evidence completeness review", "select", "Closure", true, ["Complete", "Complete with approved exception", "Incomplete - recapture required"]),
    ],
    controls: ["Evidence is tied to the correct shipment and customer", "Required identity, condition, packaging, label, and securement views are captured", "Images are clear enough to support customer-facing reporting", "Completeness is verified before shipment release"],
    approvalRoles: ["Shipping Photographer / Verifier", "Warehouse Lead", "Quality / Customer Requirement Reviewer", "Logistics Coordinator"], evidenceRequired: true,
    evidenceGuidance: ["Product identity and condition", "Packaging and preservation", "Labels and customer marks", "Blocking, bracing, trailer, and seal"],
    escalations: [escalation("Required evidence cannot be captured before departure", "Hold release or document authorized exception"), escalation("Image reveals damage or improper securement", "Stop shipment and correct condition")],
  },
  forklift: {
    procedure: procedure("WH-EHS-01", "Powered Industrial Truck Pre-Use Inspection", "Warehouse / EHS", ["OSHA 29 CFR 1910.178", "Company EHS requirements"]),
    stages: ["Identify truck", "Visual inspection", "Operational test", "Classify defect", "Tag out", "Authorize use"],
    fields: [
      F("truck_id", "Forklift / PIT ID", "text", "Record Context", true), F("operator", "Operator", "text", "Record Context", true), F("shift", "Shift", "select", "Record Context", true, ["1st", "2nd", "3rd", "Weekend / alternate"]), F("hours", "Hour-meter reading", "number", "Evaluation"),
      F("tires_forks", "Tires, forks, mast, chains, and carriage", "select", "Evaluation", true, RESULT), F("leaks", "Leaks, battery / propane, and connections", "select", "Evaluation", true, RESULT), F("guards", "Overhead guard, load backrest, and data plate", "select", "Evaluation", true, RESULT), F("controls", "Steering, brakes, horn, lights, alarms, and controls", "select", "Evaluation", true, RESULT), F("seatbelt", "Seat belt and operator restraint", "select", "Evaluation", true, RESULT), F("attachments", "Attachments and capacity compatibility", "select", "Evaluation", true, RESULT),
      F("defect", "Defect details", "textarea", "Response & Action"), F("out_of_service", "Removed from service?", "select", "Response & Action", true, YES_NO), F("tag_workorder", "Tag / maintenance work order", "text", "Response & Action", undefined, undefined, undefined, { field: "out_of_service", equals: "Yes" }), F("decision", "Operating decision", "select", "Closure", true, ["Safe for use", "Restricted use authorized", "Out of service"]),
    ],
    controls: ["Operator and equipment are correctly identified", "Required visual and operational checks are completed", "Safety-critical defect removes equipment from service", "Release / restriction is authorized"],
    approvalRoles: ["Qualified Operator", "Warehouse Supervisor", "Maintenance Technician", "EHS Authority"], evidenceRequired: true,
    evidenceGuidance: ["Defect photographs", "Out-of-service tag", "Maintenance work order", "Repair and return-to-service evidence"],
    escalations: [escalation("Safety-critical defect is identified", "Tag out immediately and notify supervisor / Maintenance"), escalation("Truck is operated after failed inspection", "EHS and management escalation")],
  },
  rack: {
    procedure: procedure("WH-EHS-02", "Rack, Dock, and Warehouse Safety Inspection", "Warehouse / EHS", ["Company EHS requirements", "ANSI / RMI-aligned inspection"]),
    stages: ["Define zone", "Inspect racks", "Inspect docks", "Inspect traffic controls", "Classify risk", "Control area", "Verify repair"],
    fields: [
      F("zone", "Warehouse zone / aisle / dock", "text", "Record Context", true), F("inspector", "Inspector", "text", "Record Context", true), F("rack_uprights", "Uprights, beams, anchors, and connectors", "select", "Evaluation", true, RESULT), F("load_signs", "Load plaques and capacity compliance", "select", "Evaluation", true, RESULT), F("guards", "Column guards, end barriers, and impact protection", "select", "Evaluation", true, RESULT),
      F("pallet_condition", "Pallet condition and storage practice", "select", "Evaluation", true, RESULT), F("dock", "Dock plates, levelers, restraints, doors, and edges", "select", "Evaluation", true, RESULT), F("traffic", "Pedestrian aisles, mirrors, signs, and traffic separation", "select", "Evaluation", true, RESULT), F("housekeeping", "Housekeeping, egress, and fire access", "select", "Evaluation", true, RESULT),
      F("damage_detail", "Damage / unsafe condition and exact location", "textarea", "Response & Action"), F("risk", "Risk classification", "select", "Response & Action", true, ["Green - acceptable", "Yellow - restrict / schedule repair", "Red - unload / isolate immediately"]), F("immediate_control", "Barricade, unload, restriction, or other control", "textarea", "Response & Action", undefined, undefined, undefined, { field: "risk", equals: ["Yellow - restrict / schedule repair", "Red - unload / isolate immediately"] }), F("work_order", "Repair / action reference", "text", "Closure"), F("verification", "Repair and safe-use verification", "textarea", "Closure", true),
    ],
    controls: ["Inspection covers structural, loading, dock, traffic, and egress conditions", "Damage location and risk are clearly classified", "Red conditions are isolated immediately", "Repair / action is independently verified"],
    approvalRoles: ["Warehouse Inspector", "Warehouse Manager", "EHS Authority", "Qualified Rack / Facilities Contractor"], evidenceRequired: true,
    evidenceGuidance: ["Rack / dock condition photographs", "Marked location map", "Barricade / unloading control", "Repair and verification evidence"],
    escalations: [escalation("Red structural or dock condition", "Isolate area and notify Warehouse / EHS leadership immediately"), escalation("Repeated impact damage", "Traffic-flow and root-cause review")],
  },
};

export const smartWarehouseConfig = specializeWorkspace(
  smartWorkspaceConfigs.warehouse,
  profiles,
  "Receive, inspect, identify, store, count, kit, move, quarantine, rotate, and ship material through purpose-built warehouse execution workflows with traceability and rich field evidence.",
  "WAREHOUSE EXECUTION, TRACEABILITY & MATERIAL FLOW",
);
