import type { FieldDef, WorkflowTool, WorkspaceConfig } from "@/lib/smart-workflow-config";

type ExtendedFieldType = FieldDef["type"] | "time" | "datetime-local";
type ExtendedField = Omit<FieldDef, "type"> & { type: ExtendedFieldType };
type OperationsTool = Omit<WorkflowTool, "fields"> & { fields: ExtendedField[] };

const YN = ["No", "Yes"];
const YNA = ["No", "Yes", "Not applicable"];
const RISK = ["Low", "Moderate", "High", "Critical"];
const SHIFT = ["1st shift", "2nd shift", "3rd shift", "Weekend / alternate", "Other / customer-defined"];
const STATUS = ["Not started", "In progress", "At risk", "Blocked", "Complete", "On hold"];
const SQDCP = ["Green - meeting target", "Yellow - risk / watch", "Red - target missed / escalation", "Gray - no current data"];
const COMPLETE = ["Completed", "Missed / incomplete", "Not required"];

const F = (
  key: string,
  label: string,
  type: ExtendedFieldType,
  section: ExtendedField["section"],
  required = false,
  options?: string[],
  help?: string,
  showWhen?: ExtendedField["showWhen"],
): ExtendedField => ({ key, label, type, section, required, options, help, showWhen });

const procedure = (id: string, title: string, owner: string, standards: string[]) => ({
  id,
  title,
  revision: "Baseline Rev B",
  owner,
  standards,
});

const escalation = (when: string, route: string) => ({ when, route });

const tools: OperationsTool[] = [
  {
    id: "handoff",
    name: "Shift Handoff",
    group: "Daily Execution",
    description: "Transfer production status, priorities, holds, equipment condition, staffing, safety risks, and accountable carryover between shifts.",
    icon: "Users",
    kind: "planning",
    procedure: procedure("OP-08.02", "Shift Handoff and Daily Execution Control", "Operations", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.5.1", "ISO 9001:2015 7.4"]),
    stages: ["Prepare", "Review production", "Review risk", "Transfer actions", "Acknowledge", "Release shift"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("outgoing_shift", "Outgoing shift", "select", "Record Context", true, SHIFT),
      F("incoming_shift", "Incoming shift", "select", "Record Context", true, SHIFT),
      F("outgoing_leader", "Outgoing supervisor / lead", "text", "Record Context", true),
      F("incoming_leader", "Incoming supervisor / lead", "text", "Record Context", true),
      F("production_state", "Overall production condition", "select", "Evaluation", true, ["On plan", "At risk", "Behind plan", "Stopped", "Shift complete"]),
      F("current_work", "Work currently running / WIP location", "textarea", "Evaluation", true, undefined, "List active work orders, operations, quantities, and where the work is physically located."),
      F("next_priorities", "Next jobs and priority sequence", "textarea", "Evaluation", true),
      F("planned_output", "Planned output for outgoing shift", "number", "Evaluation"),
      F("actual_output", "Actual good output", "number", "Evaluation"),
      F("quality_status", "Quality condition", "select", "Evaluation", true, ["Clear", "Inspection pending", "Product hold / quarantine", "Open NCR", "Customer concern / escape risk"]),
      F("quality_detail", "Quality holds, NCRs, or inspection details", "textarea", "Evaluation", true, undefined, undefined, { field: "quality_status", equals: ["Inspection pending", "Product hold / quarantine", "Open NCR", "Customer concern / escape risk"] }),
      F("equipment_status", "Equipment condition", "select", "Evaluation", true, ["Available", "Available with restriction", "Degraded / intermittent", "Down", "PM / maintenance in progress"]),
      F("equipment_detail", "Equipment issue, asset, and current response", "textarea", "Evaluation", true, undefined, undefined, { field: "equipment_status", equals: ["Available with restriction", "Degraded / intermittent", "Down", "PM / maintenance in progress"] }),
      F("material_status", "Material condition", "select", "Evaluation", true, ["Available", "Shortage risk", "Shortage stopping work", "Inspection / quality hold", "Expedite in progress"]),
      F("material_detail", "Material shortage, location, and ETA", "textarea", "Evaluation", true, undefined, undefined, { field: "material_status", equals: ["Shortage risk", "Shortage stopping work", "Inspection / quality hold", "Expedite in progress"] }),
      F("staffing_status", "Staffing and skill coverage", "select", "Evaluation", true, ["Fully staffed and qualified", "Covered through reassignment", "Headcount gap", "Critical skill gap", "Overtime / temporary coverage"]),
      F("staffing_detail", "Absences, reassignment, or qualification gaps", "textarea", "Evaluation", true, undefined, undefined, { field: "staffing_status", equals: ["Covered through reassignment", "Headcount gap", "Critical skill gap", "Overtime / temporary coverage"] }),
      F("safety_status", "Safety / permit condition", "select", "Evaluation", true, ["Clear", "Open controlled hazard", "Permit / LOTO active", "Incident response active", "Stop-work condition"]),
      F("safety_detail", "Safety risk, permit, restricted area, or stop-work details", "textarea", "Evaluation", true, undefined, undefined, { field: "safety_status", equals: ["Open controlled hazard", "Permit / LOTO active", "Incident response active", "Stop-work condition"] }),
      F("customer_commitments", "Customer, shipment, or completion commitments", "textarea", "Response & Action"),
      F("carryover_actions", "Carryover actions with owner and due time", "textarea", "Response & Action", true),
      F("incoming_questions", "Incoming-shift questions or unresolved items", "textarea", "Response & Action"),
      F("handoff_acknowledgement", "Incoming leader acknowledgement", "select", "Closure", true, ["Accepted", "Accepted with managed risks", "Questions unresolved", "Not accepted"]),
      F("shift_readiness", "Incoming shift readiness", "select", "Closure", true, ["Ready", "Ready with managed risks", "Not ready - escalation required"]),
      F("next_check", "Next required status check", "datetime-local", "Closure", true),
    ],
    controls: ["Current work, WIP, and next priorities were reviewed", "Quality, equipment, material, staffing, and safety conditions were transferred", "Every carryover item has an accountable owner and timing", "Incoming leadership acknowledged the handoff and readiness decision"],
    approvalRoles: ["Incoming Shift Supervisor", "Outgoing Shift Supervisor", "Area Manager", "Operations Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Production board or schedule snapshot", "Photographs of abnormal conditions or held product", "Maintenance, quality, or material status evidence", "Signed or recorded handoff acknowledgement"],
    escalations: [
      escalation("Incoming shift is not ready or a stop-work condition exists", "Area Manager and Operations Manager immediately"),
      escalation("Customer commitment, shipment, or priority order is at risk", "Production Control, Quality, and authorized customer-communication owner"),
      escalation("Critical skill, material, or equipment coverage is unavailable", "Operations leadership and responsible support function"),
    ],
  },
  {
    id: "production",
    name: "Production Tracker",
    group: "Production Control",
    description: "Track planned versus actual output, first-pass yield, run rate, constraints, schedule risk, and expected completion by work center and order.",
    icon: "BarChart3",
    kind: "planning",
    procedure: procedure("OP-08.01", "Production Planning, Dispatch, and Controlled Execution", "Operations / Production Control", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.5.1", "ISO 9001:2015 9.1.1"]),
    stages: ["Identify order", "Confirm plan", "Record output", "Assess variance", "Recover", "Commit completion"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("work_center", "Work center / line / cell", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("work_order", "Work order / job / batch", "text", "Record Context", true),
      F("product", "Part number / product / service", "text", "Record Context", true),
      F("customer", "Customer / program", "text", "Record Context"),
      F("operation", "Current routing operation", "text", "Record Context", true),
      F("scheduled_start", "Scheduled start", "datetime-local", "Evaluation", true),
      F("scheduled_finish", "Scheduled completion", "datetime-local", "Evaluation", true),
      F("planned_quantity", "Planned quantity", "number", "Evaluation", true),
      F("actual_good_quantity", "Actual good quantity", "number", "Evaluation", true),
      F("scrap_quantity", "Scrap quantity", "number", "Evaluation", true),
      F("rework_quantity", "Rework quantity", "number", "Evaluation", true),
      F("planned_rate_hour", "Planned run rate per hour", "number", "Evaluation"),
      F("actual_runtime_minutes", "Actual run time in minutes", "number", "Evaluation"),
      F("downtime_minutes", "Downtime minutes", "number", "Evaluation"),
      F("order_status", "Order / operation status", "select", "Evaluation", true, ["Not started", "Running on plan", "Running at risk", "Behind plan", "Stopped", "Complete", "On hold"]),
      F("constraint_category", "Primary constraint category", "select", "Evaluation", true, ["None", "Equipment", "Material", "Labor / skill", "Quality", "Tooling / fixture", "Engineering / information", "Schedule / priority conflict", "Utilities / IT", "Other / customer-defined"]),
      F("constraint_detail", "Constraint, cause, and production impact", "textarea", "Evaluation", true, undefined, undefined, { field: "constraint_category", equals: ["Equipment", "Material", "Labor / skill", "Quality", "Tooling / fixture", "Engineering / information", "Schedule / priority conflict", "Utilities / IT", "Other / customer-defined"] }),
      F("recovery_action", "Recovery action and expected gain", "textarea", "Response & Action", true, undefined, undefined, { field: "order_status", equals: ["Running at risk", "Behind plan", "Stopped", "On hold"] }),
      F("sequence_decision", "Sequence / priority decision", "textarea", "Response & Action"),
      F("support_required", "Support required and response timing", "textarea", "Response & Action"),
      F("projected_completion", "Current projected completion", "datetime-local", "Closure", true),
      F("completion_commitment", "Completion commitment status", "select", "Closure", true, ["On commitment", "Recoverable within shift", "New commitment required", "Awaiting decision", "Complete"]),
      F("next_shift_requirement", "Work remaining / next-shift requirement", "textarea", "Closure"),
    ],
    controls: ["Work order, routing operation, plan, and actual counts are reconciled", "Scrap, rework, downtime, and constraints are included in the status", "At-risk work has a recovery action or approved new commitment", "Projected completion was reviewed by the accountable production owner"],
    approvalRoles: ["Production Supervisor", "Production Control / Planner", "Operations Manager", "Value Stream Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Schedule or dispatch-list snapshot", "Machine counter / production report", "WIP and work-center condition photographs", "Constraint or recovery evidence"],
    escalations: [
      escalation("Projected completion misses a customer or interdepartmental commitment", "Production Control, Operations Manager, and Delivery Assurance"),
      escalation("Quality hold, stop-work, or equipment failure prevents production", "Quality, EHS, or Maintenance according to condition"),
      escalation("Recovery depends on priority or resource tradeoff", "Value Stream / Operations leadership decision"),
    ],
  },
  {
    id: "downtime",
    name: "Downtime Logger",
    group: "Equipment & Flow",
    description: "Time downtime events, classify loss, estimate lost output and cost, document response, verify restoration, and trigger reliability follow-up.",
    icon: "AlertTriangle",
    kind: "exception",
    procedure: procedure("OP-08.03", "Downtime, Andon, and Production Escalation", "Operations / Maintenance", ["ISO 9001:2015 7.1.3", "ISO 9001:2015 8.5.1", "ISO 9001:2015 10.2"]),
    stages: ["Start event", "Make safe", "Classify", "Respond", "Restore", "Verify", "Escalate / close"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("asset", "Asset / work center / line", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("affected_order", "Affected work order / product", "text", "Record Context"),
      F("event_start", "Downtime start", "datetime-local", "Record Context", true),
      F("event_end", "Downtime end / production restored", "datetime-local", "Closure"),
      F("event_type", "Planned or unplanned", "select", "Evaluation", true, ["Unplanned downtime", "Planned downtime", "Minor stop / micro-stop", "Reduced-speed loss"]),
      F("downtime_category", "Downtime category", "select", "Evaluation", true, ["Equipment breakdown", "Changeover / setup", "Material shortage", "Quality hold / inspection", "Labor / skill", "Tooling / fixture", "Engineering / information", "Utilities", "IT / system", "Safety / permit", "Planned maintenance", "Other / customer-defined"]),
      F("reason_code", "Reason code / failure mode", "text", "Evaluation", true),
      F("symptom", "Observed symptom and condition", "textarea", "Evaluation", true),
      F("line_condition", "Production condition", "select", "Evaluation", true, ["Fully stopped", "Partially running", "Running at reduced speed", "Alternate process in use"]),
      F("production_rate_hour", "Expected good units per hour", "number", "Evaluation"),
      F("estimated_cost_hour", "Estimated downtime cost per hour ($)", "number", "Evaluation"),
      F("safety_quality_impact", "Safety or product-quality impact", "select", "Evaluation", true, ["None identified", "Potential safety impact", "Potential product impact", "Confirmed product impact", "Stop-work / emergency"]),
      F("impact_detail", "Safety / quality impact and containment", "textarea", "Response & Action", true, undefined, undefined, { field: "safety_quality_impact", equals: ["Potential safety impact", "Potential product impact", "Confirmed product impact", "Stop-work / emergency"] }),
      F("initial_response", "Immediate response / troubleshooting", "textarea", "Response & Action", true),
      F("response_team", "Responding person / team", "text", "Response & Action", true),
      F("maintenance_work_order", "Maintenance work order / ticket", "text", "Response & Action"),
      F("temporary_fix", "Temporary repair or operating restriction", "textarea", "Response & Action"),
      F("repeat_event", "Repeat event within defined review period?", "select", "Response & Action", true, YN),
      F("cause_status", "Cause status", "select", "Closure", true, ["Cause confirmed", "Probable cause", "Unknown - investigation required", "Planned condition / no failure"]),
      F("functional_check", "Restoration / functional verification", "textarea", "Closure", true),
      F("follow_up_required", "Reliability or corrective follow-up required?", "select", "Closure", true, ["No", "Maintenance follow-up", "Reliability RCA", "CAPA / systemic action", "Engineering change", "Pending review"]),
      F("final_status", "Final equipment / production status", "select", "Closure", true, ["Returned to normal service", "Restricted operation", "Temporary repair", "Awaiting parts / support", "Out of service"]),
    ],
    controls: ["Start, restoration time, category, and reason code are verified", "Safety and product-impact conditions were evaluated and contained", "Functional restoration was verified by operations", "Repeat-event and reliability follow-up requirements were evaluated"],
    approvalRoles: ["Production Supervisor", "Maintenance Supervisor", "Reliability Engineer", "Operations Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Asset condition, alarm, or failure photographs", "Machine history, alarm, or PLC evidence", "Maintenance work order / repair evidence", "Functional test and restored-production evidence"],
    escalations: [
      escalation("Stop-work, injury potential, or product escape risk exists", "EHS / Quality and operations leadership immediately"),
      escalation("Critical asset or customer order exceeds response threshold", "Maintenance and Operations Manager escalation"),
      escalation("Repeat or chronic event is detected", "Reliability RCA and Value Ledger review"),
    ],
  },
  {
    id: "andon",
    name: "Andon / Escalation",
    group: "Escalation",
    description: "Raise and time visible support calls, establish containment, manage response SLA, escalate correctly, verify resolution, and authorize release.",
    icon: "Target",
    kind: "planning",
    procedure: procedure("OP-08.03", "Downtime, Andon, and Production Escalation", "Operations", ["ISO 9001:2015 7.4", "ISO 9001:2015 8.5.1", "ISO 9001:2015 8.7"]),
    stages: ["Raise", "Acknowledge", "Contain", "Respond", "Escalate", "Resolve", "Release"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("station", "Line / cell / station / location", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("raised_by", "Raised by", "text", "Record Context", true),
      F("raised_at", "Raised at", "datetime-local", "Record Context", true),
      F("category", "Andon category", "select", "Evaluation", true, ["Safety", "Quality", "Equipment", "Material", "Tooling / fixture", "Engineering / information", "Labor / skill", "IT / system", "Leadership decision", "Other / customer-defined"]),
      F("severity", "Severity / urgency", "select", "Evaluation", true, ["Level 1 - local response", "Level 2 - supervisor / support response", "Level 3 - leadership escalation", "Level 4 - stop work / emergency"]),
      F("line_stopped", "Production stopped?", "select", "Evaluation", true, YN),
      F("affected_order", "Affected work order / product / customer", "text", "Evaluation"),
      F("issue", "Condition and assistance needed", "textarea", "Evaluation", true),
      F("customer_product_risk", "Customer / product risk", "select", "Evaluation", true, RISK),
      F("target_response_minutes", "Target acknowledgement time in minutes", "number", "Evaluation", true),
      F("containment", "Immediate containment / safe condition", "textarea", "Response & Action", true),
      F("response_owner", "Primary response owner", "text", "Response & Action", true),
      F("acknowledged_at", "Acknowledged at", "datetime-local", "Response & Action"),
      F("support_team", "Support functions engaged", "textarea", "Response & Action"),
      F("escalation_level", "Current escalation level", "select", "Response & Action", true, ["Local team", "Supervisor", "Department support", "Operations leadership", "Executive / customer-impact review"]),
      F("resolved_at", "Resolved at", "datetime-local", "Closure"),
      F("resolution", "Resolution / condition restored", "textarea", "Closure", true),
      F("verification", "Verification that work may safely continue", "textarea", "Closure", true),
      F("released_by", "Released by", "text", "Closure", true),
      F("andon_status", "Andon status", "select", "Closure", true, ["Open", "Acknowledged", "Contained", "Response in progress", "Resolved pending release", "Closed"]),
    ],
    controls: ["Andon condition, category, severity, and affected work are clear", "The condition was acknowledged and contained within the required response", "Escalation level matches the unresolved risk and elapsed time", "Qualified personnel verified resolution and authorized release"],
    approvalRoles: ["Production Supervisor", "Responsible Support Leader", "Quality / EHS Authority", "Operations Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Condition photograph or video", "Alarm, drawing, specification, or system evidence", "Containment and response evidence", "Resolution and release verification"],
    escalations: [
      escalation("Level 4, stop-work, or critical customer/product risk", "Immediate EHS / Quality and Operations Manager notification"),
      escalation("Acknowledgement or resolution exceeds SLA", "Next escalation level automatically recommended"),
      escalation("Issue repeats or temporary correction is used", "Corrective action / reliability review"),
    ],
  },
  {
    id: "leader",
    name: "Leader Standard Work",
    group: "Leadership",
    description: "Verify the daily operating rhythm: floor presence, SQDCP reviews, abnormality response, coaching, accountability, and escalation.",
    icon: "ClipboardCheck",
    kind: "verification",
    procedure: procedure("OP-08.04", "Leader Standard Work and Daily Accountability", "Operations Leadership", ["ISO 9001:2015 5.1.1", "ISO 9001:2015 7.3", "ISO 9001:2015 9.1.1"]),
    stages: ["Plan routine", "Go to work", "Review SQDCP", "Coach", "Assign actions", "Verify completion"],
    fields: [
      F("leader", "Leader name", "text", "Record Context", true),
      F("leader_role", "Leader role", "select", "Record Context", true, ["Team Lead", "Supervisor", "Manager", "Value Stream Leader", "Plant Leadership", "Other / customer-defined"]),
      F("area", "Department / production area", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("cadence", "Routine cadence", "select", "Record Context", true, ["Daily", "Weekly", "Monthly", "Event-driven"]),
      F("pre_shift_review", "Pre-shift staffing, schedule, and risk review", "select", "Evaluation", true, COMPLETE),
      F("safety_walk", "Safety floor walk / hazard response", "select", "Evaluation", true, COMPLETE),
      F("quality_review", "Quality holds, defects, and process-control review", "select", "Evaluation", true, COMPLETE),
      F("production_review", "Production status, downtime, and constraint review", "select", "Evaluation", true, COMPLETE),
      F("material_review", "Material, WIP, and delivery-risk review", "select", "Evaluation", true, COMPLETE),
      F("skills_review", "Staffing, qualification, and coverage review", "select", "Evaluation", true, COMPLETE),
      F("action_review", "Overdue action and escalation review", "select", "Evaluation", true, COMPLETE),
      F("coaching_completed", "Coaching / recognition conversation", "select", "Evaluation", true, COMPLETE),
      F("process_confirmation", "Standard work / process confirmation at point of use", "select", "Evaluation", true, COMPLETE),
      F("abnormalities", "Abnormalities or missed routines identified", "textarea", "Evaluation"),
      F("immediate_actions", "Immediate actions and accountable owners", "textarea", "Response & Action"),
      F("coaching_notes", "Coaching, recognition, or support provided", "textarea", "Response & Action"),
      F("escalations", "Escalations made and response needed", "textarea", "Response & Action"),
      F("routine_status", "Leader-standard-work completion status", "select", "Closure", true, ["Complete", "Complete with open actions", "Partially complete", "Missed / reschedule required"]),
      F("next_follow_up", "Next follow-up", "datetime-local", "Closure", true),
    ],
    controls: ["Required leader routines were completed or formally dispositioned", "Abnormalities and missed routines have accountable follow-up", "Overdue commitments and unresolved risks were escalated", "Floor presence, coaching, and process confirmation are documented"],
    approvalRoles: ["Operations Supervisor", "Area Manager", "Value Stream Manager", "Plant Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Leader-standard-work checklist", "Board or floor-walk photographs", "Coaching / process-confirmation evidence", "Assigned-action and escalation evidence"],
    escalations: [
      escalation("Safety, quality, or delivery red condition is not controlled", "Responsible functional leader and Operations Manager"),
      escalation("Required leadership routine is repeatedly missed", "Next-level leader review"),
      escalation("Critical process has no qualified or accountable coverage", "Workforce Readiness and Operations leadership"),
    ],
  },
  {
    id: "accountability",
    name: "Daily Accountability",
    group: "Leadership",
    description: "Create clear operational commitments, track progress and blockers, enforce escalation, and verify closure against defined acceptance criteria.",
    icon: "CheckCircle2",
    kind: "planning",
    procedure: procedure("OP-08.04", "Leader Standard Work and Daily Accountability", "Operations Leadership", ["ISO 9001:2015 5.3", "ISO 9001:2015 7.4", "ISO 9001:2015 10.2"]),
    stages: ["Define", "Assign", "Execute", "Update", "Escalate", "Verify", "Close"],
    fields: [
      F("source", "Action source", "select", "Record Context", true, ["Tier meeting", "Shift handoff", "Production exception", "Andon", "Downtime", "Audit / assessment", "NCR / CAPA", "Customer commitment", "Leadership review", "Other / customer-defined"]),
      F("area", "Department / production area", "text", "Record Context", true),
      F("related_record", "Related record / order / asset", "text", "Record Context"),
      F("action_category", "Action category", "select", "Evaluation", true, ["Safety", "Quality", "Delivery", "Cost / productivity", "People / training", "Equipment / maintenance", "Material / supplier", "Engineering / process", "Customer", "Other / customer-defined"]),
      F("action_statement", "Specific action / deliverable", "textarea", "Evaluation", true, undefined, "State one accountable deliverable using a clear verb and measurable result."),
      F("expected_result", "Expected result / acceptance condition", "textarea", "Evaluation", true),
      F("business_impact", "Impact if not completed", "select", "Evaluation", true, RISK),
      F("action_status", "Current action status", "select", "Evaluation", true, STATUS),
      F("percent_complete", "Percent complete", "number", "Evaluation", true),
      F("blocker", "Current blocker / dependency", "textarea", "Evaluation", true, undefined, undefined, { field: "action_status", equals: ["At risk", "Blocked", "On hold"] }),
      F("next_step", "Next physical action and timing", "textarea", "Response & Action", true),
      F("support_needed", "Support / decision required", "textarea", "Response & Action"),
      F("last_update", "Latest factual update", "textarea", "Response & Action", true),
      F("closure_criteria", "Closure criteria", "textarea", "Closure", true),
      F("verification_method", "Closure verification method", "select", "Closure", true, ["Direct observation", "Record / document review", "Performance result", "Inspection / test", "Leader confirmation", "Customer confirmation"]),
      F("verification_result", "Verification result", "select", "Closure", true, ["Accepted", "Rejected / reopen", "Pending verification", "Not ready for closure"]),
      F("closure_date", "Verified closure date", "date", "Closure", false),
    ],
    controls: ["Action statement, expected result, accountable owner, and due date are unambiguous", "Current status and percent complete are supported by a factual update", "At-risk or blocked actions were escalated before the due date", "Closure was verified against the defined acceptance condition"],
    approvalRoles: ["Action Verifier", "Production Supervisor", "Area Manager", "Operations Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Before / after or completed-work evidence", "Updated document, schedule, or system record", "Inspection, test, or performance result", "Independent closure verification"],
    escalations: [
      escalation("Action is blocked, critical, or forecast to miss due date", "Owner's supervisor and source-meeting leader"),
      escalation("Action is overdue without an approved recovery date", "Area Manager / Operations Manager"),
      escalation("Closure evidence does not meet acceptance criteria", "Reject closure and reopen action"),
    ],
  },
  {
    id: "meeting",
    name: "Production Meeting",
    group: "Daily Execution",
    description: "Run a disciplined tier meeting around Safety, Quality, Delivery, Cost, and People; review prior commitments; make decisions; and escalate abnormalities.",
    icon: "Users",
    kind: "planning",
    procedure: procedure("OP-09.01", "Tiered Daily Management and Production Review", "Operations Leadership", ["ISO 9001:2015 9.1.1", "ISO 9001:2015 9.3", "ISO 9001:2015 7.4"]),
    stages: ["Prepare data", "Review SQDCP", "Review actions", "Decide", "Escalate", "Communicate"],
    fields: [
      F("tier_level", "Meeting tier", "select", "Record Context", true, ["Tier 1 - team / cell", "Tier 2 - department / value stream", "Tier 3 - plant leadership", "Special recovery meeting"]),
      F("area", "Department / production area", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("meeting_start", "Meeting start", "datetime-local", "Record Context", true),
      F("facilitator", "Facilitator", "text", "Record Context", true),
      F("attendees", "Required attendees / functions present", "textarea", "Record Context", true),
      F("safety_status", "Safety status", "select", "Evaluation", true, SQDCP),
      F("safety_comment", "Safety result, abnormality, or action", "textarea", "Evaluation"),
      F("quality_status", "Quality status", "select", "Evaluation", true, SQDCP),
      F("quality_comment", "Quality result, hold, defect, or action", "textarea", "Evaluation"),
      F("delivery_status", "Delivery / schedule status", "select", "Evaluation", true, SQDCP),
      F("delivery_comment", "Schedule attainment, order risk, or recovery", "textarea", "Evaluation"),
      F("cost_status", "Cost / productivity status", "select", "Evaluation", true, SQDCP),
      F("cost_comment", "Downtime, scrap, labor, or productivity result", "textarea", "Evaluation"),
      F("people_status", "People / readiness status", "select", "Evaluation", true, SQDCP),
      F("people_comment", "Staffing, qualification, attendance, or morale issue", "textarea", "Evaluation"),
      F("previous_actions_reviewed", "Previous actions reviewed", "select", "Evaluation", true, ["All reviewed", "Some not reviewed", "No previous actions", "Review deferred by authority"]),
      F("top_abnormalities", "Top abnormalities requiring action or decision", "textarea", "Evaluation", true),
      F("decisions", "Decisions made and decision owner", "textarea", "Response & Action", true),
      F("new_actions", "New actions with owner and due date", "textarea", "Response & Action", true),
      F("escalations", "Items escalated to next tier", "textarea", "Response & Action"),
      F("communication_required", "Communication outside the meeting", "textarea", "Response & Action"),
      F("meeting_end", "Meeting end", "datetime-local", "Closure", true),
      F("next_meeting", "Next meeting / required recovery review", "datetime-local", "Closure", true),
      F("minutes_status", "Meeting record status", "select", "Closure", true, ["Complete and distributed", "Complete - distribution pending", "Draft / follow-up required"]),
    ],
    controls: ["Current SQDCP data and red / yellow abnormalities were reviewed", "Previous actions and overdue commitments were dispositioned", "Every decision, action, and escalation has an owner and timing", "Required communication and next review are defined"],
    approvalRoles: ["Meeting Facilitator", "Area Manager", "Value Stream Manager", "Plant Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["SQDCP board or dashboard snapshot", "Attendance / participation record", "Action list and decision log", "Escalation or recovery-plan evidence"],
    escalations: [
      escalation("Any red SQDCP condition remains uncontrolled", "Next tier before the defined escalation cutoff"),
      escalation("Customer delivery, safety, or product risk requires cross-functional decision", "Plant leadership and responsible authority"),
      escalation("Prior action is overdue or repeatedly carried", "Owner's next-level leader"),
    ],
  },
  {
    id: "bottleneck",
    name: "Bottleneck Review",
    group: "Production Control",
    description: "Identify the real constraint using demand, demonstrated capacity, cycle time, WIP, downtime, and observation; then verify deconstraint actions with data.",
    icon: "Gauge",
    kind: "risk",
    procedure: procedure("OP-08.05", "Constraint, Capacity, and Flow Management", "Operations / Industrial Engineering", ["ISO 9001:2015 8.1", "ISO 9001:2015 8.5.1", "ISO 9001:2015 10.3"]),
    stages: ["Define demand", "Observe flow", "Quantify constraint", "Recover", "Deconstraint", "Verify capacity"],
    fields: [
      F("area", "Department / value stream", "text", "Record Context", true),
      F("process_step", "Suspected constraint process / step", "text", "Record Context", true),
      F("work_center", "Work center / asset", "text", "Record Context", true),
      F("product_family", "Product family / routing", "text", "Record Context", true),
      F("observation_period", "Observation period", "text", "Record Context", true),
      F("demand_rate_hour", "Required demand rate per hour", "number", "Evaluation", true),
      F("demonstrated_capacity_hour", "Demonstrated good-output capacity per hour", "number", "Evaluation", true),
      F("target_cycle_seconds", "Target / takt time in seconds", "number", "Evaluation"),
      F("actual_cycle_seconds", "Observed average cycle time in seconds", "number", "Evaluation"),
      F("queue_wip", "Queue / WIP before constraint", "number", "Evaluation"),
      F("downtime_minutes_period", "Downtime during observation period", "number", "Evaluation"),
      F("uptime_percent", "Observed uptime percent", "number", "Evaluation"),
      F("constraint_type", "Constraint type", "select", "Evaluation", true, ["Equipment capacity", "Changeover", "Labor / skill", "Material", "Quality / rework", "Tooling / fixture", "Method / standard work", "Engineering / information", "Scheduling / batch policy", "External supplier", "Other / customer-defined"]),
      F("constraint_evidence", "Observed constraint evidence and loss mechanism", "textarea", "Evaluation", true),
      F("lost_units_shift", "Estimated lost units per shift", "number", "Evaluation"),
      F("immediate_recovery", "Immediate flow-recovery action", "textarea", "Response & Action", true),
      F("deconstraint_action", "Longer-term deconstraint action", "textarea", "Response & Action", true),
      F("support_required", "Engineering, maintenance, tooling, labor, or capital support", "textarea", "Response & Action"),
      F("trial_plan", "Trial / verification plan", "textarea", "Response & Action", true),
      F("post_action_capacity", "Verified post-action capacity per hour", "number", "Closure"),
      F("verification_date", "Capacity verification date", "date", "Closure", true),
      F("verification_result", "Verification result", "select", "Closure", true, ["Constraint removed", "Capacity improved but still constrained", "No sustainable improvement", "Pending verification"]),
      F("residual_risk", "Residual delivery / capacity risk", "select", "Closure", true, RISK),
    ],
    controls: ["Constraint conclusion is based on demand, demonstrated capacity, and direct observation", "Immediate recovery and sustainable deconstraint are separated", "Actions protect safety, quality, and standard work", "Post-action capacity was verified over a representative operating period"],
    approvalRoles: ["Production Supervisor", "Industrial / Manufacturing Engineer", "Value Stream Manager", "Operations Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Time study, cycle-time, or production data", "WIP / queue and point-of-constraint photographs", "Downtime, quality, or changeover loss evidence", "Before / after capacity verification"],
    escalations: [
      escalation("Demonstrated capacity cannot meet customer demand", "Production Control and Operations leadership"),
      escalation("Deconstraint requires capital, design, or major process change", "Engineering and executive investment review"),
      escalation("Constraint action increases safety or quality risk", "Stop trial and route through controlled change"),
    ],
  },
  {
    id: "labor",
    name: "Labor & Skills Planner",
    group: "Resources",
    description: "Match demand to available qualified people, expose headcount and skill gaps, manage reassignment, and protect critical-process coverage.",
    icon: "Users",
    kind: "planning",
    procedure: procedure("OP-07.02", "Workforce Capacity, Competence, and Shift Coverage", "Operations / HR", ["ISO 9001:2015 7.1.2", "ISO 9001:2015 7.2", "ISO 9001:2015 8.1"]),
    stages: ["Define demand", "Verify attendance", "Verify skills", "Assign", "Cover gaps", "Approve plan", "Review shift"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("plan_date", "Plan date", "date", "Record Context", true),
      F("supervisor", "Supervisor / planner", "text", "Record Context", true),
      F("required_headcount", "Required productive headcount", "number", "Evaluation", true),
      F("available_headcount", "Available productive headcount", "number", "Evaluation", true),
      F("planned_absences", "Planned absences", "number", "Evaluation"),
      F("unplanned_absences", "Unplanned absences", "number", "Evaluation"),
      F("overtime_available", "Qualified overtime available", "number", "Evaluation"),
      F("temporary_labor", "Temporary / borrowed labor available", "number", "Evaluation"),
      F("critical_positions_required", "Critical qualified positions required", "number", "Evaluation", true),
      F("critical_positions_covered", "Critical qualified positions covered", "number", "Evaluation", true),
      F("required_skills", "Required roles, machines, certifications, or qualifications", "textarea", "Evaluation", true),
      F("skill_gaps", "Uncovered skills / qualifications", "textarea", "Evaluation"),
      F("single_point_dependency", "Single-person dependency exists?", "select", "Evaluation", true, YN),
      F("restricted_assignments", "Restrictions, accommodations, or supervision requirements", "textarea", "Evaluation"),
      F("planned_assignments", "Planned assignments by area / work center", "textarea", "Response & Action", true),
      F("reassignment_plan", "Reassignment, overtime, or temporary coverage plan", "textarea", "Response & Action"),
      F("cross_training_action", "Cross-training / succession action", "textarea", "Response & Action"),
      F("support_request", "Leadership or HR support required", "textarea", "Response & Action"),
      F("coverage_status", "Shift coverage status", "select", "Closure", true, ["Fully covered and qualified", "Covered with approved reassignment", "Headcount gap remains", "Critical skill gap remains", "Work plan reduced / resequenced"]),
      F("residual_gap", "Residual gap and production impact", "textarea", "Closure", true, undefined, undefined, { field: "coverage_status", equals: ["Headcount gap remains", "Critical skill gap remains", "Work plan reduced / resequenced"] }),
      F("next_review", "Next staffing review", "datetime-local", "Closure", true),
    ],
    controls: ["Required headcount and critical qualified positions are tied to the production plan", "Qualifications and restrictions were verified before assignment", "Critical headcount or skill gaps were escalated and the work plan adjusted", "Assignments and coverage expectations were communicated before shift execution"],
    approvalRoles: ["Production Supervisor", "Workforce / Training Coordinator", "Area Manager", "Operations Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Staffing roster / attendance snapshot", "Skills matrix or qualification evidence", "Production demand / labor plan", "Approved overtime, reassignment, or training action"],
    escalations: [
      escalation("Critical operation has no qualified coverage", "Workforce Readiness and Operations Manager immediately"),
      escalation("Headcount gap threatens customer commitment", "Production Control and Operations leadership"),
      escalation("Assignment conflicts with restriction or qualification", "Stop assignment and obtain authorized review"),
    ],
  },
  {
    id: "changeover",
    name: "Changeover Verification",
    group: "Equipment & Flow",
    description: "Control line clearance, tooling, materials, documents, programs, parameters, first-piece acceptance, changeover time, and release to production.",
    icon: "Settings",
    kind: "verification",
    procedure: procedure("OP-08.06", "Setup, Changeover, First-Piece, and Production Release", "Operations / Quality", ["ISO 9001:2015 8.5.1", "ISO 9001:2015 8.5.2", "ISO 9001:2015 8.6"]),
    stages: ["Stop prior job", "Clear line", "Install setup", "Verify inputs", "Run first piece", "Approve", "Release"],
    fields: [
      F("area", "Department / production area", "text", "Record Context", true),
      F("work_center", "Work center / line / machine", "text", "Record Context", true),
      F("from_order", "Previous work order / product", "text", "Record Context", true),
      F("to_order", "New work order / product", "text", "Record Context", true),
      F("changeover_start", "Changeover start", "datetime-local", "Record Context", true),
      F("changeover_end", "Changeover complete", "datetime-local", "Closure"),
      F("target_minutes", "Target changeover time in minutes", "number", "Evaluation", true),
      F("last_good_piece_time", "Last confirmed good piece time", "datetime-local", "Evaluation"),
      F("line_clearance", "Prior material, labels, documents, and tooling cleared", "select", "Evaluation", true, ["Verified", "Exception corrected", "Not verified / hold"]),
      F("tooling_verification", "Tooling / fixture / gage verification", "select", "Evaluation", true, ["Correct and serviceable", "Corrected before run", "Not acceptable / hold"]),
      F("material_verification", "Material, lot, and identity verification", "select", "Evaluation", true, ["Correct and released", "Corrected before run", "Inspection / release pending", "Incorrect / hold"]),
      F("document_verification", "Current drawing, router, work instruction, and revision verified", "select", "Evaluation", true, ["Current and available", "Corrected before run", "Revision conflict / hold"]),
      F("program_parameters", "Program, recipe, torque, temperature, or process parameters", "textarea", "Evaluation", true),
      F("safety_controls", "Guards, interlocks, LOTO removal, and safe-start verification", "select", "Evaluation", true, ["Verified safe", "Corrected before start", "Unsafe / hold"]),
      F("setup_exception", "Setup exception / abnormality", "textarea", "Response & Action"),
      F("correction", "Correction and re-verification", "textarea", "Response & Action"),
      F("first_piece_result", "First-piece / first-run result", "select", "Response & Action", true, ["Accepted", "Accepted with documented condition", "Rejected - adjust and repeat", "Pending inspection", "Not required by controlled plan"]),
      F("first_piece_record", "First-piece record / inspection reference", "text", "Response & Action", true),
      F("release_status", "Production release status", "select", "Closure", true, ["Released for production", "Conditional release", "Held pending approval", "Rejected / setup incomplete"]),
      F("released_at", "Released at", "datetime-local", "Closure"),
      F("released_by", "Released by", "text", "Closure", true),
      F("follow_up", "Follow-up action / changeover improvement", "textarea", "Closure"),
    ],
    controls: ["Line clearance prevents mix, misidentification, and prior-job carryover", "Tooling, material, documents, program, and safety controls match the new order", "First-piece acceptance is documented before normal production", "Authorized personnel released the setup and any conditional restrictions are visible"],
    approvalRoles: ["Setup Technician / Operator", "Production Supervisor", "Quality Inspector", "Manufacturing Engineer"],
    evidenceRequired: true,
    evidenceGuidance: ["Line-clearance and setup photographs", "Tooling, material, label, and revision evidence", "Program / parameter or checklist evidence", "First-piece inspection and production-release evidence"],
    escalations: [
      escalation("Wrong material, document revision, program, or tooling is identified", "Hold setup and notify Quality / Engineering"),
      escalation("First piece is rejected twice or target time is materially exceeded", "Supervisor, Quality, and Manufacturing Engineering"),
      escalation("Safety guard, interlock, or safe-start condition is not verified", "Stop work and route to EHS / Maintenance"),
    ],
  },
  {
    id: "visual",
    name: "Visual Management Update",
    group: "Leadership",
    description: "Keep the operating board current, source-validated, visually clear, linked to abnormalities and actions, and ready for the next tier review.",
    icon: "BarChart3",
    kind: "planning",
    procedure: procedure("OP-09.01", "Tiered Daily Management and Production Review", "Operations Leadership", ["ISO 9001:2015 7.4", "ISO 9001:2015 9.1.1", "ISO 9001:2015 10.3"]),
    stages: ["Collect data", "Validate", "Update SQDCP", "Highlight abnormality", "Link actions", "Communicate", "Set next update"],
    fields: [
      F("board", "Board / dashboard / area name", "text", "Record Context", true),
      F("area", "Department / production area", "text", "Record Context", true),
      F("board_owner", "Board owner", "text", "Record Context", true),
      F("data_cutoff", "Data cutoff time", "datetime-local", "Record Context", true),
      F("update_time", "Board updated at", "datetime-local", "Record Context", true),
      F("safety_status", "Safety status", "select", "Evaluation", true, SQDCP),
      F("safety_result", "Safety actual, target, and abnormality", "textarea", "Evaluation"),
      F("quality_status", "Quality status", "select", "Evaluation", true, SQDCP),
      F("quality_result", "Quality actual, target, and abnormality", "textarea", "Evaluation"),
      F("delivery_status", "Delivery status", "select", "Evaluation", true, SQDCP),
      F("delivery_result", "Delivery actual, target, and abnormality", "textarea", "Evaluation"),
      F("cost_status", "Cost / productivity status", "select", "Evaluation", true, SQDCP),
      F("cost_result", "Cost / productivity actual, target, and abnormality", "textarea", "Evaluation"),
      F("people_status", "People / readiness status", "select", "Evaluation", true, SQDCP),
      F("people_result", "People / readiness actual, target, and abnormality", "textarea", "Evaluation"),
      F("source_validation", "Source data validated?", "select", "Evaluation", true, ["Validated", "Validated with known limitation", "Not validated / do not publish"]),
      F("abnormalities", "Red / yellow abnormalities and business impact", "textarea", "Evaluation", true),
      F("countermeasures", "Countermeasures and action owners", "textarea", "Response & Action", true),
      F("linked_records", "Linked action, NCR, downtime, or escalation records", "textarea", "Response & Action"),
      F("communication", "Board reviewed / communicated with team", "select", "Response & Action", true, ["Completed", "Scheduled", "Not completed"]),
      F("next_update", "Next required update", "datetime-local", "Closure", true),
      F("board_status", "Board status", "select", "Closure", true, ["Current and ready", "Current with open abnormalities", "Stale / update required", "Data validation hold"]),
      F("verification", "Independent data / board verification", "textarea", "Closure", true),
    ],
    controls: ["Published values are current and traceable to validated source data", "All SQDCP categories have clear status and actual-versus-target context", "Red and yellow abnormalities are linked to accountable action", "The board was communicated and the next update time is controlled"],
    approvalRoles: ["Board Owner", "Production Supervisor", "Area Manager", "Operations Excellence Leader"],
    evidenceRequired: false,
    evidenceGuidance: ["Board / dashboard photograph or screenshot", "Validated source report", "Linked action and countermeasure evidence", "Team-review or tier-meeting evidence"],
    escalations: [
      escalation("Source data cannot be validated", "Do not publish; route to data owner and leadership"),
      escalation("Red condition has no owner, timing, or linked action", "Area Manager / next tier"),
      escalation("Board remains stale beyond required cadence", "Board owner's next-level leader"),
    ],
  },
  {
    id: "resource",
    name: "Resource Request",
    group: "Resources",
    description: "Request labor, tooling, engineering, maintenance, material, equipment, or leadership support with clear timing, impact, alternatives, approval, and fulfillment status.",
    icon: "PackageCheck",
    kind: "planning",
    procedure: procedure("OP-07.01", "Operational Resource and Support Request", "Operations", ["ISO 9001:2015 7.1", "ISO 9001:2015 8.1", "ISO 9001:2015 7.4"]),
    stages: ["Define need", "Assess impact", "Check alternatives", "Request", "Commit", "Deliver", "Verify"],
    fields: [
      F("requester", "Requester", "text", "Record Context", true),
      F("area", "Department / production area", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, SHIFT),
      F("resource_type", "Resource type", "select", "Record Context", true, ["Labor / qualified operator", "Maintenance", "Engineering", "Quality", "Material", "Tooling / fixture", "Equipment / rental", "IT / system", "Logistics", "Leadership decision", "External specialist", "Other / customer-defined"]),
      F("specific_resource", "Specific resource / capability required", "textarea", "Record Context", true),
      F("quantity", "Quantity / headcount", "number", "Evaluation"),
      F("needed_from", "Needed from", "datetime-local", "Evaluation", true),
      F("needed_until", "Needed until", "datetime-local", "Evaluation"),
      F("urgency", "Urgency", "select", "Evaluation", true, ["Routine / plan ahead", "Needed this week", "Needed next shift", "Needed this shift", "Immediate - production stopped"]),
      F("affected_order", "Affected work order / customer / commitment", "text", "Evaluation"),
      F("impact_if_unmet", "Impact if request is not fulfilled", "textarea", "Evaluation", true),
      F("impact_level", "Business impact", "select", "Evaluation", true, RISK),
      F("alternatives_attempted", "Alternatives checked or attempted", "textarea", "Evaluation", true),
      F("approval_required", "Special approval required?", "select", "Evaluation", true, YNA),
      F("requested_from", "Requested from function / leader", "text", "Response & Action", true),
      F("fulfillment_status", "Fulfillment status", "select", "Response & Action", true, ["Submitted", "Acknowledged", "Committed", "Partially fulfilled", "Fulfilled", "Declined", "Escalated"]),
      F("assigned_provider", "Assigned person / provider", "text", "Response & Action"),
      F("committed_eta", "Committed arrival / response time", "datetime-local", "Response & Action"),
      F("interim_plan", "Interim operating / recovery plan", "textarea", "Response & Action"),
      F("delivered_at", "Resource delivered / response completed", "datetime-local", "Closure"),
      F("outcome", "Outcome and impact on production", "textarea", "Closure", true),
      F("effectiveness", "Resource met the operational need?", "select", "Closure", true, ["Yes", "Partially", "No", "Pending use / verification"]),
      F("request_status", "Request status", "select", "Closure", true, ["Closed", "Open", "Escalated", "Canceled", "Converted to longer-term action"]),
    ],
    controls: ["Resource need, timing, quantity, and required capability are clear", "Impact and reasonable alternatives were evaluated", "Request has an acknowledged owner and committed response or escalation", "Fulfillment and operational effectiveness were verified"],
    approvalRoles: ["Requesting Supervisor", "Providing Function Leader", "Area Manager", "Operations Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Production schedule / affected-order evidence", "Photograph or record of the condition creating the need", "Approval / commitment communication", "Delivered-resource and effectiveness evidence"],
    escalations: [
      escalation("Immediate need is stopping production or protecting safety / quality", "Responsible function and Operations Manager immediately"),
      escalation("No response or commitment before need-by time", "Providing function's next-level leader"),
      escalation("Repeated resource need indicates systemic capacity gap", "Bottleneck, workforce, maintenance, or capital review"),
    ],
  },
];

export const smartOperationsConfig = {
  discipline: "operations",
  slug: "smart-operations",
  name: "Smart Operations",
  tag: "PRODUCTION EXECUTION & VISIBILITY",
  description: "Run the manufacturing floor through purpose-built shift, production, downtime, escalation, leadership, capacity, labor, changeover, visual-management, and resource workflows.",
  health: 86,
  healthText: "Stable · execution attention required",
  attention: "6 conditions need ownership",
  startToolId: "handoff",
  metrics: [["Schedule attainment", "91%", "Target 95%"], ["OEE", "78.4%", "-2.1%"], ["Downtime", "7", "2 critical"], ["Throughput", "126", "Today"], ["Labor utilization", "88%", "3 gaps"], ["Open actions", "19", "5 overdue"], ["Quality holds", "4", "Blocking flow"], ["On-time starts", "93%", "This shift"]],
  insights: [["Atlas", "Two production cells are likely to miss schedule without sequence or labor adjustment.", "High"], ["Forge", "Recurring Line 2 downtime is concentrated around the same changeover step.", "High"], ["Beacon", "Five operational actions have no recent update.", "Medium"], ["Ledger", "Current downtime represents an estimated $18,700 shift exposure.", "Medium"]],
  queues: [["Shift handoff", "8", "3 need review"], ["Production risks", "11", "4 high"], ["Downtime events", "7", "2 critical"], ["Escalations", "6", "2 overdue"], ["Leadership actions", "19", "5 overdue"]],
  tools,
} as unknown as WorkspaceConfig;
