import { smartWorkspaceConfigs } from "@/lib/smart-workflow-config";
import { F, RISK, RESULT, YES_NO, YES_NO_NA, escalation, procedure, specializeWorkspace, type ToolProfiles } from "@/lib/smart-specialization-helpers";

const profiles: ToolProfiles = {
  observation: {
    procedure: procedure("EHS-01", "Safety Observation and Coaching", "EHS / Operations", ["Company EHS requirements", "ISO 45001-aligned control"]),
    stages: ["Observe", "Classify", "Engage", "Correct", "Recognize", "Assign follow-up", "Close"],
    fields: [
      F("area", "Area / work location", "text", "Record Context", true), F("observer", "Observer", "text", "Record Context", true), F("observed_role", "Observed employee / contractor role", "text", "Record Context"), F("task", "Task / activity observed", "text", "Record Context", true),
      F("observation_type", "Observation type", "select", "Evaluation", true, ["Safe behavior", "At-risk behavior", "Unsafe condition", "Positive system practice", "Coaching opportunity"]), F("category", "Safety category", "select", "Evaluation", true, ["PPE", "Line of fire", "Energy isolation", "Mobile equipment", "Lifting / ergonomics", "Tools / machinery", "Housekeeping", "Work at height", "Chemical / environmental", "Procedure / permit"]), F("description", "What was observed", "textarea", "Evaluation", true), F("potential", "Potential severity", "select", "Evaluation", true, RISK),
      F("conversation", "Coaching / recognition conversation", "textarea", "Response & Action", true), F("immediate_correction", "Immediate correction or reinforcement", "textarea", "Response & Action", true), F("work_stopped", "Work stopped?", "select", "Response & Action", true, YES_NO), F("system_issue", "Procedure, equipment, design, or training issue?", "select", "Response & Action", true, YES_NO), F("follow_up", "Follow-up action / owner / due", "textarea", "Response & Action", undefined, undefined, undefined, { field: "system_issue", equals: "Yes" }),
      F("employee_feedback", "Employee feedback / improvement idea", "textarea", "Closure"), F("closure", "Observation outcome", "select", "Closure", true, ["Safe behavior recognized", "Corrected at point of work", "Action assigned", "Stop-work escalation", "No action required"]),
    ],
    controls: ["Observation is based on direct behavior / condition", "Employee engagement is respectful and specific", "Immediate risk is controlled before work continues", "System issues create accountable follow-up"],
    approvalRoles: ["Observer", "Area Supervisor", "EHS Representative", "Operations Manager"], evidenceRequired: false,
    evidenceGuidance: ["Condition photograph where appropriate", "Coaching / recognition note", "Immediate correction evidence", "Linked hazard / action record"],
    escalations: [escalation("High-potential or stop-work condition", "Area leadership and EHS immediately"), escalation("Repeated behavior reflects system weakness", "Training / procedure / engineering review")],
  },
  hazard: {
    procedure: procedure("EHS-02", "Hazard Identification and Control", "EHS / Process Owner", ["Company EHS requirements", "ISO 45001-aligned control"]),
    stages: ["Identify", "Make safe", "Assess risk", "Select controls", "Assign", "Verify", "Close"],
    fields: [
      F("area", "Area / exact location", "text", "Record Context", true), F("reported_by", "Reported by", "text", "Record Context", true), F("hazard_type", "Hazard type", "select", "Evaluation", true, ["Mechanical", "Electrical", "Chemical", "Fire / explosion", "Ergonomic", "Slip / trip / fall", "Mobile equipment", "Work at height", "Pressure / stored energy", "Environmental", "Behavioral / procedural"]), F("description", "Hazard and exposure scenario", "textarea", "Evaluation", true), F("people_exposed", "People / frequency of exposure", "textarea", "Evaluation", true),
      F("severity", "Potential severity (1-5)", "number", "Evaluation", true), F("likelihood", "Likelihood / exposure (1-5)", "number", "Evaluation", true), F("current_controls", "Current controls", "textarea", "Evaluation", true), F("risk", "Initial risk level", "select", "Evaluation", true, RISK),
      F("immediate_control", "Immediate control / isolation", "textarea", "Response & Action", true), F("control_hierarchy", "Primary permanent-control level", "select", "Response & Action", true, ["Eliminate", "Substitute", "Engineering control", "Administrative control", "PPE", "Interim monitoring"]), F("permanent_action", "Permanent corrective action", "textarea", "Response & Action", true), F("work_order", "Work order / action reference", "text", "Response & Action"),
      F("residual_severity", "Residual severity (1-5)", "number", "Closure", true), F("residual_likelihood", "Residual likelihood (1-5)", "number", "Closure", true), F("residual_risk", "Residual risk", "select", "Closure", true, RISK), F("verification", "Control verification / employee feedback", "textarea", "Closure", true), F("status", "Hazard status", "select", "Closure", true, ["Closed", "Interim control active", "Permanent action pending", "Accepted with monitoring", "Escalated"]),
    ],
    controls: ["Hazard, exposure, and potential consequence are clear", "Immediate control protects people before permanent action", "Control hierarchy is applied", "Residual risk and effectiveness are verified"],
    approvalRoles: ["Area Supervisor", "EHS Professional", "Engineering / Facilities Authority", "Operations Manager"], evidenceRequired: true,
    evidenceGuidance: ["Hazard photographs / location", "Risk assessment", "Interim control evidence", "Permanent correction and effectiveness verification"],
    escalations: [escalation("Critical risk or uncontrolled exposure", "Stop work and notify EHS / leadership immediately"), escalation("Residual risk remains high / critical", "Executive risk acceptance or additional control")],
  },
  incident: {
    procedure: procedure("EHS-03", "Incident Reporting, Investigation, and Corrective Action", "EHS", ["Company EHS requirements", "OSHA recordkeeping as applicable", "ISO 45001-aligned control"]),
    stages: ["Respond", "Make safe", "Provide care", "Notify", "Preserve evidence", "Investigate", "Correct", "Verify", "Close"],
    fields: [
      F("event_type", "Incident type", "select", "Record Context", true, ["Injury / illness", "Property damage", "Environmental release", "Fire / emergency", "Vehicle / mobile equipment", "Security", "Process safety event"]), F("area", "Location", "text", "Record Context", true), F("event_time", "Event date / time", "datetime-local", "Record Context", true), F("reported_by", "Reported by", "text", "Record Context", true),
      F("person", "Person(s) involved / role", "textarea", "Evaluation"), F("description", "What happened", "textarea", "Evaluation", true), F("task", "Task / work being performed", "textarea", "Evaluation", true), F("actual_severity", "Actual severity", "select", "Evaluation", true, RISK), F("potential_severity", "Potential severity", "select", "Evaluation", true, RISK), F("injury_detail", "Body part / injury / treatment", "textarea", "Evaluation", undefined, undefined, undefined, { field: "event_type", equals: "Injury / illness" }),
      F("emergency_response", "First aid / medical / emergency response", "textarea", "Response & Action", true), F("area_control", "Scene control and immediate corrective action", "textarea", "Response & Action", true), F("notifications", "Supervisor, EHS, leadership, customer, or agency notifications", "textarea", "Response & Action", true), F("regulatory", "Regulatory reporting status", "select", "Response & Action", true, ["Not reportable", "Pending EHS determination", "Reportable / completed", "External counsel review"]),
      F("evidence_preserved", "Evidence, equipment, photographs, and witness statements preserved", "textarea", "Evaluation", true), F("investigation_method", "Investigation method", "select", "Evaluation", true, ["5-Why", "TapRooT / cause mapping", "Fishbone", "Human performance", "Event and causal factor chart", "Multi-method"]), F("causes", "Immediate, contributing, and systemic causes", "textarea", "Evaluation", true), F("corrective_actions", "Corrective and preventive actions", "textarea", "Response & Action", true),
      F("work_status", "Employee / operation work status", "select", "Closure", true, ["Normal work", "Restricted / modified duty", "Lost time", "Operation restricted", "Operation released"]), F("effectiveness", "Corrective-action effectiveness verification", "textarea", "Closure", true), F("closure", "Investigation status", "select", "Closure", true, ["Closed", "Actions open", "Medical / claim open", "Regulatory review open", "Management review pending"]),
    ],
    controls: ["Care, scene control, and notifications occur promptly", "Evidence and witness information are preserved", "Investigation addresses systemic and human-performance factors", "Corrective action and regulatory / work-status requirements are verified"],
    approvalRoles: ["EHS Professional", "Area Manager", "HR / Claims", "Operations Leader", "Executive / Legal Authority"], evidenceRequired: true,
    evidenceGuidance: ["Scene photographs / video", "Witness statements and timeline", "Medical / emergency and regulatory records", "Investigation and corrective-action evidence"],
    escalations: [escalation("Fatality, hospitalization, amputation, environmental release, or major fire", "Emergency, executive, legal, and regulatory response"), escalation("High-potential event or repeat cause", "Management review and systemic action")],
  },
  nearmiss: {
    procedure: procedure("EHS-04", "Near-Miss and High-Potential Event Review", "EHS / Operations", ["Company EHS requirements", "ISO 45001-aligned control"]),
    stages: ["Report", "Make safe", "Assess potential", "Reconstruct event", "Identify controls", "Assign action", "Share learning", "Close"],
    fields: [
      F("area", "Location / process", "text", "Record Context", true), F("event_time", "Date / time", "datetime-local", "Record Context", true), F("reported_by", "Reported by", "text", "Record Context", true), F("event_category", "Near-miss category", "select", "Evaluation", true, ["Line of fire", "Dropped object", "Mobile equipment", "Energy release", "Slip / trip / fall", "Chemical / environmental", "Machine / tooling", "Ergonomic", "Procedure / communication"]),
      F("description", "What nearly happened", "textarea", "Evaluation", true), F("potential_outcome", "Credible worst-case outcome", "textarea", "Evaluation", true), F("potential", "Potential severity", "select", "Evaluation", true, RISK), F("barrier_failure", "Failed / missing barriers", "textarea", "Evaluation", true),
      F("immediate_control", "Immediate control", "textarea", "Response & Action", true), F("learning_team", "People involved in review", "textarea", "Response & Action"), F("causes", "Conditions, actions, and system factors", "textarea", "Evaluation", true), F("actions", "Barrier improvements / corrective actions", "textarea", "Response & Action", true), F("shared_learning", "How learning was communicated", "textarea", "Closure", true), F("verification", "Action verification", "textarea", "Closure", true), F("status", "Status", "select", "Closure", true, ["Closed", "Actions open", "High-potential review", "Management review"]),
    ],
    controls: ["Potential consequence is assessed—not only actual outcome", "Failed barriers and system conditions are identified", "High-potential events receive investigation depth equal to risk", "Learning and corrective action are shared and verified"],
    approvalRoles: ["Area Supervisor", "EHS Professional", "Operations Manager", "Learning Team Lead"], evidenceRequired: true,
    evidenceGuidance: ["Scene / condition evidence", "Barrier diagram or timeline", "Corrective-action evidence", "Learning communication"],
    escalations: [escalation("High or critical potential severity", "EHS and leadership investigation"), escalation("Similar near misses recur", "Systemic corrective action")],
  },
  ppe: {
    procedure: procedure("EHS-05", "PPE Hazard Assessment and Verification", "EHS / Operations", ["OSHA 29 CFR 1910 Subpart I", "Company EHS requirements"]),
    stages: ["Define task", "Assess hazards", "Select PPE", "Inspect condition", "Verify fit / training", "Correct gap", "Authorize task"],
    fields: [
      F("task", "Task / operation", "text", "Record Context", true), F("area", "Area / location", "text", "Record Context", true), F("employee", "Employee / role", "text", "Record Context"), F("hazards", "Hazards requiring PPE", "textarea", "Evaluation", true),
      F("eye_face", "Eye / face protection", "select", "Evaluation", true, ["Not required", "Safety glasses", "Goggles", "Face shield plus safety glasses", "Welding hood / shade", "Specialized / customer-defined"]), F("hearing", "Hearing protection", "select", "Evaluation", true, ["Not required", "Ear plugs", "Ear muffs", "Dual protection"]), F("respiratory", "Respiratory protection", "select", "Evaluation", true, ["Not required", "Filtering facepiece", "Half-face APR", "Full-face APR", "PAPR", "Supplied air / SCBA"]), F("hands_body", "Hand / body / chemical protection", "textarea", "Evaluation", true), F("feet_head_fall", "Foot, head, high-visibility, and fall protection", "textarea", "Evaluation", true),
      F("condition", "PPE condition and compatibility", "select", "Evaluation", true, RESULT), F("training", "Training / medical / fit-test current?", "select", "Evaluation", true, RESULT), F("gap", "PPE gap / incorrect use", "textarea", "Response & Action"), F("correction", "Replacement, coaching, or task control", "textarea", "Response & Action"), F("task_status", "Task authorization", "select", "Closure", true, ["Authorized", "Authorized with correction", "Not authorized / stop work"]),
    ],
    controls: ["PPE selection is based on task hazard assessment", "PPE condition, compatibility, and limitations are checked", "Required training, medical evaluation, and fit testing are current", "Task does not proceed with unresolved PPE gap"],
    approvalRoles: ["Employee / User", "Supervisor", "EHS Authority", "Respiratory Program Administrator"], evidenceRequired: false,
    evidenceGuidance: ["Task / hazard photograph", "PPE condition", "Fit-test / training record", "Replacement / correction evidence"],
    escalations: [escalation("Respiratory, fall, arc-flash, or chemical PPE requirement is not met", "Stop task and EHS review"), escalation("Repeated nonuse or selection issue", "Training / engineering / enforcement review")],
  },
  jha: {
    procedure: procedure("EHS-06", "Job Safety Analysis / Job Hazard Analysis", "EHS / Process Owner", ["Company EHS requirements", "ISO 45001-aligned control"]),
    stages: ["Define job", "Break into steps", "Identify hazards", "Select controls", "Assess residual risk", "Brief crew", "Authorize", "Review change"],
    fields: [
      F("job", "Job / task", "text", "Record Context", true), F("area", "Work location", "text", "Record Context", true), F("crew", "Crew / roles involved", "textarea", "Record Context", true), F("job_type", "Job type", "select", "Evaluation", true, ["Routine", "Non-routine", "Maintenance", "Contractor", "Emergency", "New / changed process"]),
      F("steps", "Task steps in sequence", "textarea", "Evaluation", true), F("hazards", "Hazards for each step", "textarea", "Evaluation", true), F("initial_risk", "Initial risk", "select", "Evaluation", true, RISK), F("controls", "Controls by hierarchy for each hazard", "textarea", "Response & Action", true), F("permits", "Required permits / isolations", "textarea", "Response & Action"), F("ppe", "Required PPE", "textarea", "Response & Action", true), F("emergency", "Emergency / rescue / stop-work plan", "textarea", "Response & Action", true),
      F("residual_risk", "Residual risk", "select", "Closure", true, RISK), F("crew_briefed", "Crew reviewed and understood JHA?", "select", "Closure", true, YES_NO), F("change_trigger", "Stop and revise when conditions change?", "select", "Closure", true, YES_NO), F("authorization", "Job authorization", "select", "Closure", true, ["Authorized", "Authorized with conditions", "Not authorized"]),
    ],
    controls: ["Job is broken into observable steps", "Hazards are identified for people, equipment, energy, and environment", "Controls follow hierarchy and include emergency needs", "Crew understanding and change-management expectations are verified"],
    approvalRoles: ["Job Leader", "Affected Employees", "Supervisor", "EHS / Permit Authority"], evidenceRequired: true,
    evidenceGuidance: ["Work-area photographs / layout", "JHA / risk worksheet", "Crew acknowledgement", "Permit / isolation evidence"],
    escalations: [escalation("Residual risk remains high / critical", "Do not authorize without additional control and leadership acceptance"), escalation("Scope or conditions change", "Stop and revalidate JHA")],
  },
  audit: {
    procedure: procedure("EHS-07", "Safety and Environmental Audit", "EHS", ["Company EHS requirements", "ISO 45001 / ISO 14001-aligned control"]),
    stages: ["Plan", "Define criteria", "Inspect", "Interview / sample", "Classify findings", "Assign", "Verify", "Close"],
    fields: [
      F("audit_type", "Audit type", "select", "Record Context", true, ["General safety", "Machine guarding", "LOTO", "Chemical / environmental", "Ergonomics", "Fire / emergency", "Contractor", "Compliance", "Focused follow-up"]), F("area", "Area / process", "text", "Record Context", true), F("auditor", "Auditor / team", "text", "Record Context", true), F("criteria", "Audit criteria / regulation / company standard", "textarea", "Evaluation", true), F("scope", "Scope and sampling", "textarea", "Evaluation", true),
      F("checks", "Checks performed", "number", "Evaluation", true), F("conforming", "Conforming checks", "number", "Evaluation", true), F("findings", "Findings / observations", "number", "Evaluation", true), F("critical_findings", "Critical / stop-work findings", "number", "Evaluation", true), F("finding_detail", "Requirement, evidence, and gap", "textarea", "Evaluation", true),
      F("immediate_control", "Immediate correction / containment", "textarea", "Response & Action"), F("action_required", "Corrective action required?", "select", "Response & Action", true, YES_NO), F("verification_method", "Closure verification method", "select", "Closure", true, ["Evidence review", "Follow-up inspection", "Interview / demonstration", "Performance trend", "Management review"]), F("closure", "Closure status", "select", "Closure", true, ["Closed", "Actions open", "Reaudit required", "Management escalation"]),
    ],
    controls: ["Criteria, scope, and sampling are documented", "Findings are tied to objective requirements and evidence", "Immediate risk is controlled", "Closure is independently verified"],
    approvalRoles: ["EHS Auditor", "Area Manager", "EHS Manager", "Management Representative"], evidenceRequired: true,
    evidenceGuidance: ["Audit checklist / plan", "Condition photographs", "Finding and action evidence", "Follow-up verification"],
    escalations: [escalation("Critical / stop-work finding", "Immediate area control and leadership notification"), escalation("Repeated or overdue finding", "Management review")],
  },
  forklift: {
    procedure: procedure("EHS-08", "Powered Industrial Truck Pre-Use Inspection", "Operations / EHS", ["OSHA 29 CFR 1910.178"]),
    stages: ["Identify truck", "Visual check", "Operational check", "Classify defect", "Tag out", "Release"],
    fields: [
      F("truck_id", "Forklift / PIT ID", "text", "Record Context", true), F("operator", "Qualified operator", "text", "Record Context", true), F("shift", "Shift", "select", "Record Context", true, ["1st", "2nd", "3rd", "Weekend / alternate"]), F("hours", "Hour-meter reading", "number", "Evaluation"),
      F("forks_mast", "Forks, mast, chains, carriage, attachments", "select", "Evaluation", true, RESULT), F("tires", "Tires / wheels", "select", "Evaluation", true, RESULT), F("power", "Battery / propane / fuel / leaks", "select", "Evaluation", true, RESULT), F("guards_plate", "Guard, load backrest, capacity plate", "select", "Evaluation", true, RESULT), F("controls", "Steering, brakes, horn, lights, alarms", "select", "Evaluation", true, RESULT), F("restraint", "Seat belt / restraint", "select", "Evaluation", true, RESULT),
      F("defect", "Defect detail", "textarea", "Response & Action"), F("removed", "Removed from service?", "select", "Response & Action", true, YES_NO), F("tag_workorder", "Tag / work order", "text", "Response & Action", undefined, undefined, undefined, { field: "removed", equals: "Yes" }), F("decision", "Operating decision", "select", "Closure", true, ["Safe for use", "Restricted use authorized", "Out of service"]),
    ],
    controls: ["Operator and truck are correctly identified", "Visual and operational checks are complete", "Safety-critical defect removes truck from service", "Release / restriction is authorized"],
    approvalRoles: ["Qualified Operator", "Supervisor", "Maintenance Technician", "EHS Authority"], evidenceRequired: true,
    evidenceGuidance: ["Defect photographs", "Out-of-service tag", "Maintenance work order", "Repair / return-to-service evidence"],
    escalations: [escalation("Safety-critical defect", "Tag out immediately"), escalation("Unqualified operator or missing inspection", "Stop operation and supervisor / EHS review")],
  },
  permit: {
    procedure: procedure("EHS-09", "Permit to Work", "EHS / Operations", ["Company EHS requirements", "Applicable OSHA standards"]),
    stages: ["Define work", "Select permit", "Assess hazards", "Verify controls", "Authorize", "Monitor", "Restore", "Close"],
    fields: [
      F("permit_type", "Permit type", "select", "Record Context", true, ["Hot work", "Confined space", "Electrical / energized", "LOTO", "Work at height", "Excavation", "Line break", "Critical lift", "Roof access"]), F("location", "Work location", "text", "Record Context", true), F("scope", "Work scope", "textarea", "Record Context", true), F("crew", "Employees / contractor / attendant", "textarea", "Record Context", true),
      F("hazards", "Hazards and energy sources", "textarea", "Evaluation", true), F("controls", "Required controls / isolation / ventilation / fire watch / rescue", "textarea", "Evaluation", true), F("atmosphere", "Atmospheric test / electrical absence / other required verification", "textarea", "Evaluation"), F("ppe", "PPE and equipment", "textarea", "Evaluation", true), F("emergency", "Emergency / rescue plan", "textarea", "Evaluation", true),
      F("start", "Permit start", "datetime-local", "Response & Action", true), F("expiration", "Permit expiration", "datetime-local", "Response & Action", true), F("conditions_changed", "Conditions changed?", "select", "Response & Action", true, YES_NO), F("revalidation", "Stop-work / revalidation", "textarea", "Response & Action", undefined, undefined, undefined, { field: "conditions_changed", equals: "Yes" }),
      F("work_complete", "Work complete and area inspected", "select", "Closure", true, RESULT), F("systems_restored", "Guards, isolations, alarms, and area restored", "select", "Closure", true, RESULT), F("permit_status", "Permit status", "select", "Closure", true, ["Closed", "Suspended", "Extended / revalidated", "Cancelled"]),
    ],
    controls: ["Permit type, scope, hazards, and required roles are correct", "Controls and required tests are verified before work", "Conditions are monitored and change triggers stop / revalidation", "Restoration and permit closeout are complete"],
    approvalRoles: ["Permit Issuer", "Performing Authority", "Area Owner", "EHS / Rescue Authority"], evidenceRequired: true,
    evidenceGuidance: ["Permit and risk assessment", "Isolation / test evidence", "Work-area conditions", "Closeout / restoration evidence"],
    escalations: [escalation("Required test or control fails", "Do not issue / suspend permit"), escalation("Unexpected condition or emergency", "Stop work and activate response plan")],
  },
  emergency: {
    procedure: procedure("EHS-10", "Emergency Drill and Preparedness Evaluation", "EHS / Emergency Response", ["Company emergency plan", "ISO 45001-aligned control"]),
    stages: ["Plan scenario", "Brief controllers", "Initiate", "Observe response", "Account", "Evaluate", "Assign improvement", "Close"],
    fields: [
      F("scenario", "Drill scenario", "select", "Record Context", true, ["Fire / evacuation", "Medical emergency", "Chemical spill", "Severe weather", "Security / active threat", "Confined-space rescue", "Power / utility loss", "Business continuity"]), F("area", "Area / site", "text", "Record Context", true), F("drill_date", "Drill date / time", "datetime-local", "Record Context", true), F("participants", "Participants / departments / responders", "textarea", "Record Context", true),
      F("objectives", "Drill objectives and success criteria", "textarea", "Evaluation", true), F("alarm_time", "Alarm / notification time", "datetime-local", "Evaluation"), F("response_time", "Initial response time", "text", "Evaluation"), F("evacuation_time", "Evacuation / accountability time", "text", "Evaluation"), F("accountability", "Personnel accountability result", "select", "Evaluation", true, RESULT), F("communications", "Communication and command effectiveness", "select", "Evaluation", true, RESULT), F("equipment", "Emergency equipment / access / readiness", "select", "Evaluation", true, RESULT),
      F("strengths", "What worked well", "textarea", "Response & Action", true), F("gaps", "Gaps, delays, confusion, or unsafe acts", "textarea", "Response & Action", true), F("actions", "Improvement actions and owners", "textarea", "Response & Action", true), F("plan_changes", "Emergency-plan / training / equipment changes", "textarea", "Closure"), F("verification", "Improvement verification / next drill", "textarea", "Closure", true), F("result", "Drill result", "select", "Closure", true, ["Effective", "Effective with improvements", "Ineffective / repeat drill required"]),
    ],
    controls: ["Scenario and objectives are realistic and controlled", "Response, accountability, communication, and equipment are evaluated", "Actual emergencies are not confused with drill activity", "Improvements are assigned and verified"],
    approvalRoles: ["Emergency Coordinator", "EHS Manager", "Site Leader", "Response Team Lead"], evidenceRequired: true,
    evidenceGuidance: ["Drill plan / scenario", "Observer notes / timing", "Photographs / video where safe", "Improvement action and repeat-drill evidence"],
    escalations: [escalation("Accountability, alarm, or emergency equipment fails", "Immediate corrective action and management review"), escalation("Drill reveals life-safety system failure", "Facility restriction until controlled")],
  },
  training: {
    procedure: procedure("EHS-11", "Safety Training and Qualification", "EHS / Training", ["OSHA training requirements as applicable", "Company EHS requirements"]),
    stages: ["Define requirement", "Assign", "Train", "Evaluate competence", "Authorize", "Track expiration"],
    fields: [
      F("person", "Employee / contractor", "text", "Record Context", true), F("role", "Role / assignment", "text", "Record Context", true), F("training", "Required safety training / qualification", "text", "Evaluation", true), F("regulation", "Regulation / company standard / procedure", "text", "Evaluation", true), F("method", "Training method", "select", "Evaluation", true, ["Instructor-led", "Hands-on practical", "Online / CBT", "Toolbox talk", "External certification", "Refresher / remedial"]), F("trainer", "Qualified trainer / evaluator", "text", "Evaluation", true), F("completion", "Completion date", "date", "Response & Action", true),
      F("competence_method", "Competence verification", "select", "Response & Action", true, ["Written assessment", "Practical demonstration", "Observed task", "License / external credential", "Supervisor verification"]), F("result", "Qualification result", "select", "Closure", true, ["Qualified", "Qualified with restrictions", "In progress", "Not qualified"]), F("restrictions", "Restrictions / supervision", "textarea", "Closure", undefined, undefined, undefined, { field: "result", equals: "Qualified with restrictions" }), F("expiration", "Expiration / refresher date", "date", "Closure"), F("authorization", "Authorized task / equipment / permit role", "textarea", "Closure", true),
    ],
    controls: ["Training need is tied to role / hazard / regulation", "Trainer and content are current", "Competence is verified—not attendance alone", "Authorization, restriction, and expiration are visible"],
    approvalRoles: ["Qualified Trainer", "Supervisor", "EHS Authority", "Training Administrator"], evidenceRequired: true,
    evidenceGuidance: ["Training content / revision", "Assessment / practical demonstration", "Certificate / license", "Authorization signoff"],
    escalations: [escalation("Person is unqualified for assigned high-risk work", "Restrict assignment immediately"), escalation("Critical certification is expiring", "Supervisor and Workforce Readiness alert")],
  },
  chemical: {
    procedure: procedure("EHS-12", "Chemical Approval, SDS, Labeling, and Storage", "EHS / Operations", ["OSHA Hazard Communication", "Company chemical-management requirements"]),
    stages: ["Request chemical", "Review hazards", "Approve / reject", "Receive SDS", "Label / store", "Train", "Audit use", "Remove"],
    fields: [
      F("chemical", "Chemical / product name", "text", "Record Context", true), F("manufacturer", "Manufacturer / supplier", "text", "Record Context", true), F("use", "Intended use / process / quantity", "textarea", "Record Context", true), F("sds_revision", "SDS revision / date", "text", "Evaluation", true), F("hazards", "GHS hazards / exposure routes", "textarea", "Evaluation", true), F("substitution", "Less hazardous substitute evaluated?", "select", "Evaluation", true, YES_NO), F("regulatory", "Regulatory / environmental restrictions", "textarea", "Evaluation"),
      F("controls", "Ventilation, handling, spill, fire, and emergency controls", "textarea", "Response & Action", true), F("ppe", "Required PPE / respiratory protection", "textarea", "Response & Action", true), F("storage", "Approved storage / segregation / quantity limit", "textarea", "Response & Action", true), F("labeling", "Container / secondary-container labeling", "select", "Response & Action", true, RESULT), F("training", "Affected employee training / communication", "textarea", "Response & Action", true),
      F("approval", "Chemical approval status", "select", "Closure", true, ["Approved", "Approved with restrictions", "Trial only", "Rejected", "Obsolete / remove"]), F("inventory_location", "Inventory / storage location", "text", "Closure"), F("disposal", "Waste / disposal route", "textarea", "Closure", true), F("review_date", "Next review / SDS update date", "date", "Closure"),
    ],
    controls: ["Current SDS and intended use are reviewed before introduction", "Substitution and regulatory impacts are evaluated", "Controls, PPE, labeling, storage, and training are defined", "Approval, inventory location, and disposal route are controlled"],
    approvalRoles: ["EHS Chemical Coordinator", "Process Owner", "Industrial Hygiene / Environmental Authority", "Purchasing"], evidenceRequired: true,
    evidenceGuidance: ["Current SDS", "Label / storage photographs", "Risk / substitution review", "Training and approval record"],
    escalations: [escalation("Chemical is carcinogenic, highly toxic, reactive, or environmentally restricted", "Specialist / leadership approval before purchase"), escalation("Unlabeled container or missing SDS", "Stop use and quarantine")],
  },
};

export const smartSafetyConfig = specializeWorkspace(
  smartWorkspaceConfigs.safety,
  profiles,
  "Prevent injury and loss through purpose-built observation, hazard, incident, near-miss, PPE, JHA, audit, mobile-equipment, permit, emergency, training, and chemical-control workflows.",
  "SAFETY EXECUTION, HAZARD CONTROL & EMERGENCY READINESS",
);
