import { smartWorkspaceConfigs } from "@/lib/smart-workflow-config";
import { F, RISK, RESULT, YES_NO, YES_NO_NA, escalation, procedure, specializeWorkspace, type ToolProfiles } from "@/lib/smart-specialization-helpers";

const profiles: ToolProfiles = {
  ncr: {
    procedure: procedure("QP-08.03", "Control of Nonconforming Outputs", "Quality", ["ISO 9001:2015 8.7", "ISO 9001:2015 10.2"]),
    stages: ["Identify", "Contain", "Evaluate", "Disposition", "Verify", "Release / close"],
    fields: [
      F("source", "Detection source", "select", "Record Context", true, ["Incoming inspection", "In-process", "Final inspection", "Customer / field", "Audit", "Supplier", "Warranty / return", "Other / customer-defined"]),
      F("area", "Department / process / work center", "text", "Record Context", true),
      F("product", "Part / product / service", "text", "Record Context", true),
      F("work_order", "Work order / job / batch", "text", "Record Context"),
      F("lot_serial", "Lot / serial / heat / batch", "text", "Record Context"),
      F("requirement", "Requirement not met", "textarea", "Evaluation", true, undefined, "Reference the drawing, specification, procedure, customer requirement, or acceptance criterion."),
      F("category", "Nonconformance category", "select", "Evaluation", true, ["Dimensional", "Material", "Workmanship", "Functional", "Process deviation", "Documentation", "Identification / traceability", "Packaging / preservation", "Other / customer-defined"]),
      F("qty_inspected", "Quantity inspected", "number", "Evaluation", true),
      F("qty_affected", "Quantity affected", "number", "Evaluation", true),
      F("risk", "Product / customer risk", "select", "Evaluation", true, RISK),
      F("shipped", "Potentially affected product already shipped?", "select", "Evaluation", true, YES_NO),
      F("customer_scope", "Customer / field scope and notification assessment", "textarea", "Evaluation", true, undefined, undefined, { field: "shipped", equals: "Yes" }),
      F("containment", "Immediate containment and segregation", "textarea", "Response & Action", true),
      F("extent", "Extent-of-condition review", "textarea", "Response & Action", true),
      F("disposition", "Disposition", "select", "Response & Action", true, ["Rework", "Repair", "Use as-is / concession", "Return to supplier", "Scrap", "Regrade", "Sort / screen", "Pending MRB review"]),
      F("disposition_instructions", "Disposition instructions and acceptance criteria", "textarea", "Response & Action", true),
      F("capa_required", "CAPA / systemic action required?", "select", "Response & Action", true, ["No", "Yes", "Pending review"]),
      F("verification", "Post-disposition verification result", "textarea", "Closure", true),
      F("release_status", "Final status / release decision", "select", "Closure", true, ["Released", "Rejected / scrapped", "Returned", "Held pending approval"]),
    ],
    controls: ["Affected output is positively identified and controlled", "Quantity and extent of condition are reconciled", "Disposition authority is documented", "Post-action verification and release are complete"],
    approvalRoles: ["Quality Manager", "MRB Authority", "Engineering Authority", "Operations Manager", "Customer Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Condition photographs or marked drawing", "Hold / segregation evidence", "Inspection or test results", "Disposition and verification evidence"],
    escalations: [escalation("Potential customer escape or critical product risk", "Quality leadership and authorized customer-response owner immediately"), escalation("Use-as-is, repair, or concession is proposed", "Engineering / MRB and customer approval as required"), escalation("Repeat or systemic condition is detected", "CAPA and management review")],
  },
  capa: {
    procedure: procedure("QP-10.02", "Corrective Action and Systemic Improvement", "Quality", ["ISO 9001:2015 10.2", "ISO 9001:2015 10.3"]),
    stages: ["Initiate", "Contain", "Define problem", "Analyze", "Correct", "Implement", "Verify effectiveness", "Close"],
    fields: [
      F("source", "CAPA source", "select", "Record Context", true, ["NCR", "Customer complaint", "Audit finding", "Supplier issue", "Trend / KPI", "Management review", "Safety / reliability event", "Other / customer-defined"]),
      F("area", "Process owner / affected area", "text", "Record Context", true),
      F("linked_record", "Linked NCR, audit, complaint, or event", "text", "Record Context"),
      F("problem", "Evidence-based problem statement", "textarea", "Evaluation", true, undefined, "Describe what happened, where, when, magnitude, expected condition, and evidence."),
      F("impact", "Customer, product, compliance, cost, or delivery impact", "textarea", "Evaluation", true),
      F("risk", "Risk level", "select", "Evaluation", true, RISK),
      F("containment", "Immediate containment", "textarea", "Response & Action", true),
      F("extent", "Extent-of-condition and similar-process review", "textarea", "Evaluation", true),
      F("analysis_method", "Root-cause method", "select", "Evaluation", true, ["5-Why", "Fishbone", "Is / Is Not", "Fault tree", "Process mapping", "Data / Pareto analysis", "Human performance review", "Multi-method investigation"]),
      F("root_cause", "Verified occurrence root cause", "textarea", "Evaluation", true),
      F("escape_cause", "Escape / detection-system cause", "textarea", "Evaluation", true),
      F("systemic_cause", "Systemic / management-system cause", "textarea", "Evaluation"),
      F("correction", "Correction of the specific condition", "textarea", "Response & Action", true),
      F("corrective_action", "Action preventing recurrence", "textarea", "Response & Action", true),
      F("escape_action", "Action strengthening detection / escape prevention", "textarea", "Response & Action", true),
      F("horizontal", "Horizontal deployment to similar products or processes", "textarea", "Response & Action"),
      F("implementation_date", "Implementation completion date", "date", "Closure", true),
      F("effectiveness_criteria", "Measurable effectiveness criterion and target", "textarea", "Closure", true),
      F("effectiveness_date", "Effectiveness review date", "date", "Closure", true),
      F("effectiveness_result", "Effectiveness result", "select", "Closure", true, ["Effective", "Partially effective", "Ineffective", "Pending review"]),
      F("additional_action", "Additional action / reopening plan", "textarea", "Closure", true, undefined, undefined, { field: "effectiveness_result", equals: ["Partially effective", "Ineffective"] }),
    ],
    controls: ["Problem and causes are supported by objective evidence", "Correction, occurrence cause, and escape cause are addressed", "Implementation evidence is attached", "Effectiveness was verified after sufficient operating time"],
    approvalRoles: ["Quality Manager", "Process Owner", "Operations Leader", "Engineering Authority", "Management Representative"],
    evidenceRequired: true,
    evidenceGuidance: ["Containment evidence", "Analysis data and cause validation", "Completed-action evidence", "Effectiveness trend, audit, or verification evidence"],
    escalations: [escalation("Critical risk or external notification is involved", "Executive and authorized customer / regulatory review"), escalation("Effectiveness is partial or ineffective", "Reopen CAPA and escalate to management review"), escalation("Action is overdue", "Process owner and department leader")],
  },
  fivewhy: {
    procedure: procedure("QP-10.03", "Structured Root Cause Analysis", "Quality / Operations", ["ISO 9001:2015 10.2"]),
    stages: ["Define", "Collect evidence", "Why 1", "Why 2", "Why 3", "Why 4", "Why 5", "Verify cause", "Link action"],
    fields: [
      F("area", "Process / area", "text", "Record Context", true),
      F("linked_record", "Linked issue / CAPA / NCR", "text", "Record Context"),
      F("problem", "Specific problem statement", "textarea", "Evaluation", true),
      F("evidence", "Facts, timeline, and data supporting the problem", "textarea", "Evaluation", true),
      F("why1", "Why did the observed problem occur?", "textarea", "Evaluation", true),
      F("why1_evidence", "Evidence validating Why 1", "textarea", "Evaluation", true),
      F("why2", "Why did that condition exist?", "textarea", "Evaluation", true),
      F("why2_evidence", "Evidence validating Why 2", "textarea", "Evaluation", true),
      F("why3", "Why was the process or control unable to prevent it?", "textarea", "Evaluation", true),
      F("why3_evidence", "Evidence validating Why 3", "textarea", "Evaluation", true),
      F("why4", "Why did the system permit that weakness?", "textarea", "Evaluation", true),
      F("why4_evidence", "Evidence validating Why 4", "textarea", "Evaluation", true),
      F("why5", "Why was the systemic condition not previously addressed?", "textarea", "Evaluation", true),
      F("why5_evidence", "Evidence validating Why 5", "textarea", "Evaluation", true),
      F("verified_cause", "Verified root cause conclusion", "textarea", "Closure", true),
      F("escape_point", "Where should the issue have been detected?", "textarea", "Closure", true),
      F("contributing_factors", "Contributing factors not identified as root cause", "textarea", "Closure"),
      F("action_link", "Corrective-action record / action plan", "text", "Closure", true),
    ],
    controls: ["Each why is causal and supported by evidence", "The analysis did not stop at blame or operator error", "Occurrence and escape causes are distinguished", "Verified cause is linked to corrective action"],
    approvalRoles: ["Quality Engineer", "Process Owner", "Operations Manager", "Technical SME"],
    evidenceRequired: true,
    evidenceGuidance: ["Timeline and process evidence", "Data, photographs, or records validating each causal step", "Process map or fishbone when used", "Corrective-action linkage"],
    escalations: [escalation("Evidence does not support the proposed cause", "Facilitated multi-method investigation"), escalation("Cause crosses departments or management systems", "Cross-functional leadership review")],
  },
  audit: {
    procedure: procedure("QP-09.02", "Internal and Process Auditing", "Quality", ["ISO 9001:2015 9.2"]),
    stages: ["Plan", "Prepare", "Conduct", "Record evidence", "Classify findings", "Assign action", "Verify", "Close"],
    fields: [
      F("audit_type", "Audit type", "select", "Record Context", true, ["QMS system", "Process", "Product", "Special process", "Compliance", "Follow-up", "Readiness"]),
      F("area", "Audited function / process", "text", "Record Context", true),
      F("auditor", "Lead auditor", "text", "Record Context", true),
      F("auditee", "Process owner / auditee", "text", "Record Context", true),
      F("audit_date", "Audit date", "date", "Record Context", true),
      F("scope", "Scope and boundaries", "textarea", "Evaluation", true),
      F("criteria", "Audit criteria / procedures / clauses", "textarea", "Evaluation", true),
      F("sampling", "Sampling plan and records reviewed", "textarea", "Evaluation", true),
      F("objective_evidence", "Objective evidence and observations", "textarea", "Evaluation", true),
      F("result", "Finding classification", "select", "Evaluation", true, ["Conforming", "Opportunity for improvement", "Minor nonconformity", "Major nonconformity", "Immediate risk / stop condition"]),
      F("finding", "Finding statement", "textarea", "Evaluation", true, undefined, "State requirement, evidence, and gap without prescribing a solution."),
      F("immediate_correction", "Immediate correction / containment", "textarea", "Response & Action"),
      F("capa_required", "Corrective action required?", "select", "Response & Action", true, YES_NO),
      F("response_due", "Response due date", "date", "Response & Action", true),
      F("verification_method", "Closure verification method", "select", "Closure", true, ["Evidence review", "Follow-up audit", "Performance trend", "On-site verification", "Management review"]),
      F("closure_result", "Closure result", "select", "Closure", true, ["Accepted", "Rejected / reopen", "Pending verification"]),
    ],
    controls: ["Auditor independence and competence are confirmed", "Scope, criteria, and sampling are documented", "Findings are tied to objective requirements and evidence", "Closure is independently verified"],
    approvalRoles: ["Lead Auditor", "Quality Manager", "Process Owner", "Management Representative"],
    evidenceRequired: true,
    evidenceGuidance: ["Audit plan and checklist", "Interview and record evidence", "Finding evidence", "Corrective action and closure evidence"],
    escalations: [escalation("Major nonconformity or immediate risk is found", "Management Representative and affected leadership immediately"), escalation("Finding remains overdue or is rejected", "Department leader and management review")],
  },
  lpa: {
    procedure: procedure("QP-09.03", "Layered Process Audits", "Operations / Quality", ["ISO 9001:2015 8.5.1", "ISO 9001:2015 9.1.1"]),
    stages: ["Select layer", "Observe work", "Answer checks", "Correct now", "Escalate repeat", "Verify", "Close"],
    fields: [
      F("layer", "Audit layer", "select", "Record Context", true, ["Layer 1 - front-line leader", "Layer 2 - department manager", "Layer 3 - plant leadership", "Special focused layer"]),
      F("area", "Process / cell / work center", "text", "Record Context", true),
      F("shift", "Shift", "select", "Record Context", true, ["1st", "2nd", "3rd", "Weekend / alternate"]),
      F("auditor", "Auditor", "text", "Record Context", true),
      F("checklist_revision", "Checklist / process-control revision", "text", "Evaluation", true),
      F("checks_planned", "Checks planned", "number", "Evaluation", true),
      F("checks_conforming", "Checks conforming", "number", "Evaluation", true),
      F("checks_nonconforming", "Checks nonconforming", "number", "Evaluation", true),
      F("checks_not_observed", "Checks not observed / not applicable", "number", "Evaluation", true),
      F("abnormality", "Observed abnormality / failed check", "textarea", "Evaluation", true, undefined, undefined, { field: "checks_nonconforming", equals: "1" }),
      F("immediate_correction", "Correction completed at point of work", "textarea", "Response & Action"),
      F("repeat_issue", "Repeat condition?", "select", "Response & Action", true, YES_NO),
      F("escalation", "Escalation / systemic action", "textarea", "Response & Action", true, undefined, undefined, { field: "repeat_issue", equals: "Yes" }),
      F("verification", "Follow-up verification", "textarea", "Closure", true),
      F("result", "Audit result", "select", "Closure", true, ["Conforming", "Corrected during audit", "Open action required", "Stop / immediate escalation"]),
    ],
    controls: ["Audit was performed at the point of work", "Questions were answered by observation rather than opinion", "Every failed check received immediate response", "Repeat conditions were escalated beyond local correction"],
    approvalRoles: ["Layer Auditor", "Area Supervisor", "Operations Manager", "Quality Manager"],
    evidenceRequired: false,
    evidenceGuidance: ["Checklist results", "Photographs of abnormalities", "Immediate correction evidence", "Repeat-condition trend or linked action"],
    escalations: [escalation("Stop condition or critical process-control failure", "Operations and Quality leadership immediately"), escalation("Repeat condition is identified", "Corrective action / process-owner review")],
  },
  inspection: {
    procedure: procedure("QP-08.06", "Inspection, Testing, and Product Release", "Quality", ["ISO 9001:2015 8.5.1", "ISO 9001:2015 8.6"]),
    stages: ["Identify product", "Verify plan", "Inspect / test", "Record results", "Control failure", "Release"],
    fields: [
      F("inspection_type", "Inspection type", "select", "Record Context", true, ["Receiving", "In-process", "Final", "First-off", "Patrol", "Reinspection", "Functional test"]),
      F("product", "Part / product / service", "text", "Record Context", true),
      F("work_order", "Work order / job / batch", "text", "Record Context", true),
      F("lot_serial", "Lot / serial / heat / batch", "text", "Record Context"),
      F("operation", "Operation / inspection point", "text", "Record Context", true),
      F("plan_revision", "Inspection plan / drawing revision", "text", "Evaluation", true),
      F("sample_size", "Sample size", "number", "Evaluation", true),
      F("characteristic", "Characteristic / requirement", "textarea", "Evaluation", true),
      F("specification", "Specification / tolerance / acceptance criteria", "textarea", "Evaluation", true),
      F("measurement_result", "Measured or observed result", "textarea", "Evaluation", true),
      F("gage_id", "Gage / test-equipment ID", "text", "Evaluation"),
      F("gage_status", "Measurement equipment status", "select", "Evaluation", true, ["Current / acceptable", "Limited use", "Past due", "Not required", "Status unknown"]),
      F("result", "Inspection result", "select", "Evaluation", true, RESULT),
      F("qty_accepted", "Quantity accepted", "number", "Evaluation", true),
      F("qty_rejected", "Quantity rejected", "number", "Evaluation", true),
      F("ncr", "NCR / hold record", "text", "Response & Action", true, undefined, undefined, { field: "result", equals: ["Fail", "Conditional", "Unable to verify"] }),
      F("release", "Product release decision", "select", "Closure", true, ["Released", "Released with approved condition", "Held", "Rejected"]),
    ],
    controls: ["Current requirements and sampling plan were used", "Measurement equipment status was verified", "Results are traceable to product and operation", "Nonconforming output is controlled before release"],
    approvalRoles: ["Qualified Inspector", "Quality Technician", "Quality Engineer", "Authorized Release Personnel"],
    evidenceRequired: true,
    evidenceGuidance: ["Inspection plan or marked drawing", "Measurement / test results", "Product identification and condition", "Release, hold, or NCR evidence"],
    escalations: [escalation("Measurement equipment is past due or status is unknown", "Stop inspection and Quality / Calibration review"), escalation("Failure or conditional result is recorded", "Product hold and NCR workflow")],
  },
  firstarticle: {
    procedure: procedure("QP-08.07", "First Article and First-Piece Approval", "Quality / Engineering", ["ISO 9001:2015 8.5.1", "ISO 9001:2015 8.6"]),
    stages: ["Confirm trigger", "Verify configuration", "Review material / process", "Inspect characteristics", "Resolve gaps", "Approve production"],
    fields: [
      F("trigger", "FAI trigger", "select", "Record Context", true, ["New part / product", "Engineering revision", "Process relocation", "Tooling / program change", "Long production lapse", "Customer requirement", "Corrective action / revalidation"]),
      F("part_number", "Part number / product", "text", "Record Context", true),
      F("revision", "Drawing / specification revision", "text", "Record Context", true),
      F("work_order", "Work order / batch", "text", "Record Context", true),
      F("serial_lot", "Serial / lot / heat", "text", "Record Context"),
      F("balloon_revision", "Ballooned drawing / characteristic list revision", "text", "Evaluation", true),
      F("material_status", "Material certification and identity", "select", "Evaluation", true, RESULT),
      F("process_docs", "Router, work instructions, control plan, and programs", "select", "Evaluation", true, RESULT),
      F("tooling_status", "Tooling, fixture, and gage readiness", "select", "Evaluation", true, RESULT),
      F("characteristics_total", "Characteristics required", "number", "Evaluation", true),
      F("characteristics_passed", "Characteristics accepted", "number", "Evaluation", true),
      F("characteristics_failed", "Characteristics failed", "number", "Evaluation", true),
      F("deviation", "Deviation / discrepancy and linked NCR", "textarea", "Response & Action", true, undefined, undefined, { field: "characteristics_failed", equals: "1" }),
      F("capability_required", "Capability study required?", "select", "Response & Action", true, YES_NO_NA),
      F("capability_result", "Capability result / reference", "textarea", "Response & Action", true, undefined, undefined, { field: "capability_required", equals: "Yes" }),
      F("fai_result", "FAI result", "select", "Closure", true, ["Approved", "Approved with documented condition", "Rejected", "Pending correction / reinspection"]),
      F("production_release", "Release to normal production", "select", "Closure", true, ["Authorized", "Not authorized", "Limited / conditional production"]),
    ],
    controls: ["Configuration and FAI trigger are verified", "Material, process documentation, tooling, and gages are current", "Every required characteristic is accounted for", "Production release is authorized only after acceptance"],
    approvalRoles: ["Quality Engineer", "Manufacturing Engineer", "Customer / Source Inspector", "Operations Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Ballooned drawing and results", "Material and special-process certifications", "Tooling / setup evidence", "Customer or internal approval record"],
    escalations: [escalation("Characteristic failure or configuration mismatch", "Stop release; NCR and Engineering review"), escalation("Customer source approval is required", "Do not release until customer authority is documented")],
  },
  calibration: {
    procedure: procedure("QP-07.01", "Monitoring and Measuring Resources", "Quality / Calibration", ["ISO 9001:2015 7.1.5"]),
    stages: ["Identify gage", "Verify status", "Calibrate", "Record as-found", "Assess impact", "Label / release"],
    fields: [
      F("gage_id", "Gage / instrument ID", "text", "Record Context", true),
      F("gage_type", "Gage / instrument type", "text", "Record Context", true),
      F("location", "Assigned location / custodian", "text", "Record Context", true),
      F("activity", "Activity", "select", "Evaluation", true, ["Calibration", "Intermediate verification", "Repair / adjustment", "Out-of-tolerance evaluation", "Recall / custody update"]),
      F("due_date", "Current due date", "date", "Evaluation", true),
      F("standard", "Reference standard / method", "text", "Evaluation", true),
      F("traceability", "Standard traceability / certificate", "text", "Evaluation", true),
      F("as_found", "As-found condition / data", "textarea", "Evaluation", true),
      F("tolerance", "Required tolerance / acceptance criteria", "textarea", "Evaluation", true),
      F("result", "Calibration result", "select", "Evaluation", true, ["Acceptable", "Limited use", "Out of tolerance", "Unable to calibrate"]),
      F("adjustment", "Adjustment / repair and as-left condition", "textarea", "Response & Action"),
      F("impact_required", "Product-impact evaluation required?", "select", "Response & Action", true, YES_NO),
      F("affected_period", "Potential affected period and product scope", "textarea", "Response & Action", true, undefined, undefined, { field: "impact_required", equals: "Yes" }),
      F("impact_result", "Product-impact conclusion / linked records", "textarea", "Response & Action", true, undefined, undefined, { field: "impact_required", equals: "Yes" }),
      F("final_status", "Final equipment status", "select", "Closure", true, ["In service", "Restricted use", "Out of service", "Scrapped / replaced"]),
      F("next_due", "Next calibration / review date", "date", "Closure", true),
    ],
    controls: ["Identity, status, method, and traceability are verified", "As-found data was recorded before adjustment", "Out-of-tolerance product impact is completed when required", "Status label and next due date are controlled"],
    approvalRoles: ["Calibration Technician", "Quality Engineer", "Quality Manager", "Technical Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Calibration certificate / results", "As-found and as-left data", "Product-impact evaluation", "Status label or custody evidence"],
    escalations: [escalation("Out-of-tolerance condition may affect released product", "Quality Manager and affected product owners immediately"), escalation("Reference standard traceability is unacceptable", "Quarantine results and technical review")],
  },
  msa: {
    procedure: procedure("QP-07.02", "Measurement System Analysis", "Quality Engineering", ["ISO 9001:2015 7.1.5", "ISO 9001:2015 9.1.1"]),
    stages: ["Define study", "Verify system", "Collect trials", "Calculate", "Interpret", "Improve / approve"],
    fields: [
      F("study_type", "Study type", "select", "Record Context", true, ["Variable Gage R&R", "Attribute agreement", "Bias", "Linearity", "Stability", "Correlation"]),
      F("gage_id", "Gage / measurement system", "text", "Record Context", true),
      F("characteristic", "Measured characteristic", "text", "Record Context", true),
      F("tolerance", "Tolerance / process variation", "text", "Evaluation", true),
      F("operators", "Number of appraisers / operators", "number", "Evaluation", true),
      F("parts", "Number of parts / samples", "number", "Evaluation", true),
      F("trials", "Trials per part", "number", "Evaluation", true),
      F("study_method", "Study method / software / reference", "text", "Evaluation", true),
      F("grr_percent", "% Gage R&R / agreement result", "number", "Evaluation"),
      F("ndc", "Number of distinct categories", "number", "Evaluation"),
      F("bias_linearity", "Bias / linearity / stability result", "textarea", "Evaluation"),
      F("result", "Measurement system decision", "select", "Evaluation", true, ["Acceptable", "Conditionally acceptable", "Unacceptable", "Insufficient data"]),
      F("restriction", "Use restriction / interim control", "textarea", "Response & Action", true, undefined, undefined, { field: "result", equals: ["Conditionally acceptable", "Unacceptable", "Insufficient data"] }),
      F("improvement", "Measurement-system improvement action", "textarea", "Response & Action"),
      F("retest_date", "Re-study / review date", "date", "Closure"),
      F("approval", "Final authorization", "select", "Closure", true, ["Approved for intended use", "Approved with restriction", "Not approved"]),
    ],
    controls: ["Study design matches measurement-system use", "Appraisers, samples, and trials are representative", "Calculations and acceptance criteria are documented", "Restrictions and improvement actions are controlled"],
    approvalRoles: ["Quality Engineer", "Metrology / Calibration SME", "Process Engineer", "Quality Manager"],
    evidenceRequired: true,
    evidenceGuidance: ["Raw study data", "Calculation / software report", "Gage and sample identification", "Approval, restriction, or improvement evidence"],
    escalations: [escalation("Measurement system is unacceptable for product acceptance", "Stop use for release and establish alternate verification"), escalation("Insufficient discrimination or unstable results", "Engineering and Quality improvement plan")],
  },
  supplier: {
    procedure: procedure("QP-08.04", "Supplier Nonconformance and Corrective Action", "Supplier Quality / Purchasing", ["ISO 9001:2015 8.4", "ISO 9001:2015 8.7"]),
    stages: ["Identify supplier issue", "Contain receipt", "Notify supplier", "Disposition", "Receive response", "Verify effectiveness", "Close"],
    fields: [
      F("supplier", "Supplier", "text", "Record Context", true),
      F("po_receipt", "PO / receipt / packing list", "text", "Record Context", true),
      F("part_lot", "Part / lot / heat / serial", "text", "Record Context", true),
      F("qty_received", "Quantity received", "number", "Evaluation", true),
      F("qty_affected", "Quantity affected", "number", "Evaluation", true),
      F("defect", "Defect and requirement not met", "textarea", "Evaluation", true),
      F("risk", "Supply / product / customer risk", "select", "Evaluation", true, RISK),
      F("internal_containment", "Internal containment / inventory scope", "textarea", "Response & Action", true),
      F("supplier_containment", "Supplier containment and certification plan", "textarea", "Response & Action", true),
      F("notification_date", "Supplier notification date", "date", "Response & Action", true),
      F("response_due", "Supplier response due", "date", "Response & Action", true),
      F("disposition", "Material disposition", "select", "Response & Action", true, ["Return to supplier", "Sort / screen", "Rework", "Use as-is / concession", "Scrap", "Replacement / expedite", "Pending review"]),
      F("root_cause", "Supplier verified root cause", "textarea", "Evaluation"),
      F("supplier_action", "Supplier corrective action", "textarea", "Response & Action"),
      F("effectiveness", "Effectiveness verification", "textarea", "Closure", true),
      F("status", "Supplier issue status", "select", "Closure", true, ["Closed", "Open containment", "Response pending", "Action implementation", "Effectiveness monitoring", "Escalated"]),
    ],
    controls: ["Affected receipt and inventory are controlled", "Supplier notification includes requirement, evidence, and due date", "Disposition and recovery are authorized", "Supplier action is verified before closure"],
    approvalRoles: ["Supplier Quality Engineer", "Quality Manager", "Purchasing Manager", "Engineering / MRB Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Defect photographs and inspection results", "PO, receipt, and traceability", "Supplier response / 8D", "Disposition and effectiveness evidence"],
    escalations: [escalation("Production or customer commitment is threatened", "Purchasing, Operations, Quality, and Delivery Assurance"), escalation("Repeat issue or supplier response is overdue", "Supplier leadership escalation / SCAR")],
  },
  scorecard: {
    procedure: procedure("QP-08.05", "Supplier Performance Monitoring", "Supplier Quality / Purchasing", ["ISO 9001:2015 8.4.1"]),
    stages: ["Define period", "Collect data", "Validate", "Score", "Review risk", "Set status", "Communicate"],
    fields: [
      F("supplier", "Supplier", "text", "Record Context", true),
      F("period", "Review period", "text", "Record Context", true),
      F("receipts", "Receipts / lots received", "number", "Evaluation"),
      F("defective_qty", "Defective quantity", "number", "Evaluation"),
      F("ppm", "Supplier PPM", "number", "Evaluation", true),
      F("otd", "On-time delivery (%)", "number", "Evaluation", true),
      F("response_score", "Responsiveness score (%)", "number", "Evaluation", true),
      F("audit_score", "Audit / compliance score (%)", "number", "Evaluation"),
      F("cost_impact", "Supplier COPQ / disruption cost ($)", "number", "Evaluation"),
      F("risk", "Overall supplier risk", "select", "Evaluation", true, RISK),
      F("trend", "Performance trend", "select", "Evaluation", true, ["Improving", "Stable", "Declining", "Insufficient history"]),
      F("improvement", "Required supplier improvement commitments", "textarea", "Response & Action"),
      F("status", "Approved supplier status", "select", "Closure", true, ["Approved", "Approved with conditions", "Probation", "Restricted", "Disqualified / removed"]),
      F("next_review", "Next review date", "date", "Closure", true),
    ],
    controls: ["Source data and calculations are validated", "Rating criteria are consistently applied", "High-risk or declining performance has an improvement plan", "Final status is approved and communicated"],
    approvalRoles: ["Supplier Quality Engineer", "Purchasing Manager", "Quality Manager", "Operations / Supply Chain Leader"],
    evidenceRequired: false,
    evidenceGuidance: ["Validated receipt, defect, and delivery data", "Trend charts", "Improvement commitments", "Approval-status communication"],
    escalations: [escalation("Rating is restricted, probationary, or unacceptable", "Cross-functional supplier review and sourcing decision"), escalation("Supplier creates critical continuity risk", "Executive supply-chain escalation")],
  },
  complaint: {
    procedure: procedure("QP-08.08", "Customer Complaint and Response", "Quality / Customer Service", ["ISO 9001:2015 8.2.1", "ISO 9001:2015 9.1.2", "ISO 9001:2015 10.2"]),
    stages: ["Receive", "Acknowledge", "Assess severity", "Contain", "Investigate", "Respond", "Recover", "Close"],
    fields: [
      F("customer", "Customer", "text", "Record Context", true),
      F("contact", "Customer contact", "text", "Record Context", true),
      F("received_date", "Complaint received date", "date", "Record Context", true),
      F("product", "Product / part / service", "text", "Record Context", true),
      F("order_serial", "Order / shipment / serial / lot", "text", "Record Context"),
      F("complaint_type", "Complaint type", "select", "Evaluation", true, ["Product quality", "Performance / function", "Documentation", "Packaging / damage", "Delivery", "Service / communication", "Warranty", "Other / customer-defined"]),
      F("description", "Customer-reported condition and requirement", "textarea", "Evaluation", true),
      F("severity", "Customer / business severity", "select", "Evaluation", true, RISK),
      F("field_status", "Product / field condition", "select", "Evaluation", true, ["Product secured", "Product remains in use", "Production stopped", "Safety concern", "Unknown / awaiting customer"]),
      F("scope", "Affected customer, shipment, and product scope", "textarea", "Evaluation", true),
      F("acknowledged", "Customer acknowledgement date", "date", "Response & Action", true),
      F("containment", "Immediate customer and internal containment", "textarea", "Response & Action", true),
      F("rma", "RMA / return / field-support reference", "text", "Response & Action"),
      F("response_due", "Committed response date", "date", "Response & Action", true),
      F("investigation", "Investigation / linked NCR or CAPA", "textarea", "Response & Action", true),
      F("resolution", "Resolution, replacement, credit, repair, or technical response", "textarea", "Response & Action", true),
      F("customer_response", "Final customer response date", "date", "Closure", true),
      F("customer_acceptance", "Customer acceptance / recovery status", "select", "Closure", true, ["Accepted / satisfied", "Accepted with follow-up", "Disputed / unresolved", "No response", "Commercial closure only"]),
    ],
    controls: ["Complaint is traceable to customer and product", "Severity and external exposure are assessed", "Containment and committed response are documented", "Investigation, resolution, and customer recovery are verified"],
    approvalRoles: ["Customer Quality Engineer", "Quality Manager", "Customer Service / Account Owner", "Operations / Executive Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Customer email, report, or photographs", "Product / shipment traceability", "Containment and investigation evidence", "Final response and customer acceptance"],
    escalations: [escalation("Safety, regulatory, or broad field exposure is possible", "Executive, Quality, and legal / regulatory review"), escalation("Committed response date is at risk", "Customer owner and leadership immediately")],
  },
  warranty: {
    procedure: procedure("QP-08.09", "Warranty and Claim Determination", "Quality / Service", ["ISO 9001:2015 8.5.5", "ISO 9001:2015 9.1.2"]),
    stages: ["Receive claim", "Verify coverage", "Inspect evidence", "Determine cause", "Assign responsibility", "Authorize disposition", "Close"],
    fields: [
      F("claim", "Claim / RMA number", "text", "Record Context", true),
      F("customer", "Customer / end user", "text", "Record Context", true),
      F("product_serial", "Product / model / serial", "text", "Record Context", true),
      F("ship_date", "Ship date", "date", "Evaluation"),
      F("install_date", "Install / in-service date", "date", "Evaluation"),
      F("failure_date", "Failure date", "date", "Evaluation", true),
      F("failure_mode", "Reported and verified failure mode", "textarea", "Evaluation", true),
      F("operating_conditions", "Application, duty, environment, and operating conditions", "textarea", "Evaluation", true),
      F("evidence_review", "Returned product / field evidence review", "textarea", "Evaluation", true),
      F("coverage", "Warranty coverage", "select", "Evaluation", true, ["Within warranty", "Outside warranty", "Goodwill consideration", "Contract / customer-specific", "Unable to determine"]),
      F("responsibility", "Responsibility determination", "select", "Evaluation", true, ["Manufacturing defect", "Design / application", "Supplier", "Installation / misuse", "Normal wear", "No defect found", "Shared / undetermined"]),
      F("claim_value", "Estimated claim exposure ($)", "number", "Evaluation"),
      F("disposition", "Claim disposition", "select", "Response & Action", true, ["Approve replacement", "Approve repair", "Approve credit", "Deny claim", "Return as no defect found", "Technical assistance / goodwill", "Pending review"]),
      F("rationale", "Technical and contractual rationale", "textarea", "Response & Action", true),
      F("capa_required", "Corrective action required?", "select", "Response & Action", true, YES_NO),
      F("closure", "Claim closure status", "select", "Closure", true, ["Closed", "Awaiting customer", "Awaiting product return", "Commercial action pending", "Engineering / CAPA pending"]),
    ],
    controls: ["Coverage terms and product identity are verified", "Failure conclusion is supported by evidence", "Responsibility and disposition authority are documented", "Systemic-action need and financial exposure are evaluated"],
    approvalRoles: ["Warranty / Service Manager", "Quality Manager", "Engineering Authority", "Commercial / Finance Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Claim and warranty terms", "Returned-product or field photographs", "Inspection / test / teardown results", "Disposition and customer communication"],
    escalations: [escalation("Claim suggests systemic or safety-related failure", "CAPA, Engineering, and executive review"), escalation("Claim value exceeds customer-defined authority", "Finance / executive approval")],
  },
  documents: {
    procedure: procedure("QP-07.05", "Documented Information Control", "Quality Systems", ["ISO 9001:2015 7.5"]),
    stages: ["Request", "Assess impact", "Draft", "Review", "Approve", "Train", "Release", "Remove obsolete"],
    fields: [
      F("doc_number", "Document number", "text", "Record Context", true),
      F("doc_title", "Document title", "text", "Record Context", true),
      F("doc_type", "Document type", "select", "Record Context", true, ["Policy", "Procedure", "Work instruction", "Form / record", "Specification", "Control plan", "Training material", "External document"]),
      F("current_revision", "Current revision", "text", "Evaluation", true),
      F("proposed_revision", "Proposed revision", "text", "Evaluation", true),
      F("change_reason", "Change reason and detailed summary", "textarea", "Evaluation", true),
      F("affected_processes", "Affected products, processes, sites, and systems", "textarea", "Evaluation", true),
      F("risk", "Change risk", "select", "Evaluation", true, RISK),
      F("external_approval", "Customer / regulatory approval required?", "select", "Response & Action", true, YES_NO_NA),
      F("training_required", "Training / read-and-understand required?", "select", "Response & Action", true, YES_NO),
      F("training_plan", "Training and communication plan", "textarea", "Response & Action", true, undefined, undefined, { field: "training_required", equals: "Yes" }),
      F("effective_date", "Effective date", "date", "Closure", true),
      F("system_release", "Controlled-system release / distribution", "textarea", "Closure", true),
      F("obsolete_control", "Obsolete copies removed / prevented from use", "select", "Closure", true, YES_NO),
      F("post_release", "Post-release verification", "textarea", "Closure", true),
    ],
    controls: ["Need, scope, and risk of change are assessed", "Required technical and external reviews are complete", "Training / communication is complete before effective use", "Obsolete versions are prevented from unintended use"],
    approvalRoles: ["Document Owner", "Quality Systems Manager", "Technical Approver", "Department Manager", "Customer / Regulatory Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Redline / revised document", "Review and approval evidence", "Training / communication records", "Controlled release and obsolete-copy verification"],
    escalations: [escalation("High-risk change affects customer, regulatory, or special-process requirements", "Cross-functional and external approval before release"), escalation("Obsolete version remains available at point of use", "Immediate containment and process-owner verification")],
  },
  training: {
    procedure: procedure("QP-07.02", "Competence, Qualification, and Awareness", "Operations / HR / Quality", ["ISO 9001:2015 7.2", "ISO 9001:2015 7.3"]),
    stages: ["Define requirement", "Assign", "Train", "Evaluate competence", "Authorize", "Monitor expiration"],
    fields: [
      F("person", "Employee / contractor", "text", "Record Context", true),
      F("employee_id", "Employee / contractor ID", "text", "Record Context"),
      F("role", "Role / job classification", "text", "Record Context", true),
      F("requirement", "Required qualification / skill", "text", "Evaluation", true),
      F("procedure_revision", "Procedure / work-instruction revision", "text", "Evaluation", true),
      F("training_method", "Training method", "select", "Evaluation", true, ["Instructor-led", "On-the-job", "Read and understand", "Practical demonstration", "External certification", "Refresher / remedial"]),
      F("trainer", "Qualified trainer / evaluator", "text", "Evaluation", true),
      F("completion_date", "Training completion date", "date", "Response & Action", true),
      F("competence_method", "Competence verification", "select", "Response & Action", true, ["Written assessment", "Observed demonstration", "First-piece / work sample", "Supervisor verification", "External credential"]),
      F("score_result", "Assessment score / observed result", "text", "Response & Action", true),
      F("result", "Qualification result", "select", "Closure", true, ["Qualified", "Qualified with restrictions", "Training in progress", "Not qualified"]),
      F("restrictions", "Restrictions / supervision requirements", "textarea", "Closure", true, undefined, undefined, { field: "result", equals: "Qualified with restrictions" }),
      F("authorization_scope", "Authorized equipment, process, product, or task scope", "textarea", "Closure", true),
      F("expiration", "Expiration / review date", "date", "Closure"),
      F("retraining_trigger", "Retraining trigger / next action", "textarea", "Closure"),
    ],
    controls: ["Requirement is tied to role and current controlled documents", "Trainer / evaluator is qualified", "Competence is verified—not attendance alone", "Authorization, restrictions, and expiration are visible"],
    approvalRoles: ["Qualified Trainer", "Supervisor / Process Owner", "Quality Authority", "Training Administrator"],
    evidenceRequired: true,
    evidenceGuidance: ["Training material / procedure revision", "Assessment or observed-demonstration evidence", "Qualification signoff", "External certificate where applicable"],
    escalations: [escalation("Person is not qualified for assigned work", "Restrict assignment and notify supervisor"), escalation("Critical qualification is expiring without coverage", "Workforce Readiness and Operations leadership")],
  },
  risk: {
    procedure: procedure("QP-06.01", "Quality Risk and Opportunity Management", "Leadership / Quality", ["ISO 9001:2015 6.1"]),
    stages: ["Identify", "Analyze", "Score", "Evaluate controls", "Treat", "Rescore", "Review / accept"],
    fields: [
      F("area", "Process / product / project", "text", "Record Context", true),
      F("risk_statement", "Risk statement (cause–event–impact)", "textarea", "Evaluation", true),
      F("severity", "Severity (1-10)", "number", "Evaluation", true),
      F("occurrence", "Occurrence / likelihood (1-10)", "number", "Evaluation", true),
      F("detection", "Detection weakness (1-10)", "number", "Evaluation", true),
      F("current_controls", "Current prevention and detection controls", "textarea", "Evaluation", true),
      F("risk_class", "Initial risk class", "select", "Evaluation", true, RISK),
      F("treatment", "Risk treatment", "select", "Response & Action", true, ["Avoid", "Reduce", "Transfer", "Accept with monitoring", "Exploit opportunity", "Escalate"]),
      F("action", "Mitigation / opportunity action", "textarea", "Response & Action", true),
      F("residual_severity", "Residual severity (1-10)", "number", "Closure", true),
      F("residual_occurrence", "Residual occurrence (1-10)", "number", "Closure", true),
      F("residual_detection", "Residual detection weakness (1-10)", "number", "Closure", true),
      F("residual_class", "Residual risk class", "select", "Closure", true, RISK),
      F("acceptance_rationale", "Residual-risk acceptance rationale", "textarea", "Closure", true),
      F("review_date", "Next review date", "date", "Closure", true),
    ],
    controls: ["Risk is clearly stated with cause and impact", "Prevention and detection controls are distinguished", "High / critical risk has approved treatment", "Residual risk and review cadence are authorized"],
    approvalRoles: ["Process Owner", "Quality / Risk Manager", "Operations Leader", "Executive Authority"],
    evidenceRequired: false,
    evidenceGuidance: ["FMEA / risk analysis", "Supporting performance or failure data", "Mitigation evidence", "Leadership acceptance record"],
    escalations: [escalation("Initial or residual risk is critical", "Executive and process-owner action"), escalation("Risk affects customer, regulatory, or safety commitments", "Cross-functional review")],
  },
  change: {
    procedure: procedure("QP-08.05", "Controlled Product and Process Change", "Quality / Engineering", ["ISO 9001:2015 6.3", "ISO 9001:2015 8.5.6"]),
    stages: ["Request", "Classify", "Assess impact", "Validate", "Approve", "Implement", "Verify effectiveness"],
    fields: [
      F("change_type", "Change type", "select", "Record Context", true, ["Product / design", "Process / method", "Equipment / tooling", "Material / supplier", "Software / data", "Document / procedure", "Facility / layout", "Organization / role"]),
      F("area", "Affected product / process / site", "text", "Record Context", true),
      F("current_state", "Current state", "textarea", "Evaluation", true),
      F("proposed_state", "Proposed change", "textarea", "Evaluation", true),
      F("reason", "Business / technical reason", "textarea", "Evaluation", true),
      F("affected_requirements", "Affected specifications, customers, controls, and records", "textarea", "Evaluation", true),
      F("risk", "Change risk", "select", "Evaluation", true, RISK),
      F("quality_impact", "Quality / validation impact", "textarea", "Evaluation", true),
      F("safety_delivery_impact", "Safety, capacity, delivery, and continuity impact", "textarea", "Evaluation", true),
      F("customer_approval", "Customer / regulatory approval required?", "select", "Response & Action", true, YES_NO_NA),
      F("validation_plan", "Trial / validation / verification plan", "textarea", "Response & Action", true),
      F("document_training", "Document, training, ERP, and communication updates", "textarea", "Response & Action", true),
      F("implementation_date", "Approved implementation date", "date", "Closure", true),
      F("validation_result", "Validation result", "select", "Closure", true, ["Accepted", "Accepted with restrictions", "Rejected", "Pending"]),
      F("post_review", "Post-implementation effectiveness review", "textarea", "Closure", true),
      F("rollback", "Rollback / contingency status", "select", "Closure", true, ["Not required", "Available and verified", "Activated", "Incomplete"]),
    ],
    controls: ["Affected functions and requirements are identified", "Risk, validation, and external approval are complete", "Documents, systems, and training are updated before use", "Post-implementation effectiveness and rollback readiness are verified"],
    approvalRoles: ["Process Owner", "Quality Manager", "Engineering Authority", "Operations Leader", "Customer / Regulatory Authority"],
    evidenceRequired: true,
    evidenceGuidance: ["Change request and impact assessment", "Trial / validation results", "Approvals and training evidence", "Post-implementation review"],
    escalations: [escalation("High-risk change affects released product or customer requirements", "Executive / customer authority before implementation"), escalation("Validation is rejected or post-review is ineffective", "Rollback and corrective action")],
  },
};

export const smartQualityConfig = specializeWorkspace(
  smartWorkspaceConfigs.quality,
  profiles,
  "Control defects, inspection, measurement, audits, supplier and customer quality, competence, risk, change, and systemic improvement through purpose-built quality workflows.",
  "QUALITY EXECUTION, ASSURANCE & SYSTEM CONTROL",
);
